objects/AttendeeSummary__c.object
<CustomObject>
    <fields>
        <fullName>AS_Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AS_Email__c</fullName>
        <description>Mallikarjuna Set-Up  Email Field As External ID</description>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AS_FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AS_LastName__c</fullName>
        <label>LastName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>customer_key__c</fullName>
        <label>customer key</label>
        <referenceTo>Constomer__c</referenceTo>
        <relationshipLabel>AttendeeSummary</relationshipLabel>
        <relationshipName>AttendeeSummary</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AttendeeSummary</label>
    <nameField>
        <displayFormat>QR_AT_{dd}{yy}_{0000000}</displayFormat>
        <label>AS_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AttendeeSummary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Company__c.object
<CustomObject>
    <description>user companyWhen company information is null in input form. create a company with just user name and assign user role of company admin.</description>
    <label>BLN Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Constomer__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Uniq_Number__c</fullName>
        <label>Uniq Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Transaction Info</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>customer key Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Dummay__c.object
<CustomObject>
    <fields>
        <fullName>AttendeeSummary__c</fullName>
        <label>Attendee</label>
        <referenceTo>AttendeeSummary__c</referenceTo>
        <relationshipLabel>Registration Info</relationshipLabel>
        <relationshipName>Registration_Info</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_number__c</fullName>
        <label>Check number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Dummays</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InvoiceEmail__c</fullName>
        <label>InvoiceEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guest</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Profile__c</fullName>
        <label>Profile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TicketTypes__c</fullName>
        <label>TicketTypes</label>
        <referenceTo>TicketTypes__c</referenceTo>
        <relationshipName>Dummays</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>customer_key__c</fullName>
        <label>customer key</label>
        <referenceTo>Constomer__c</referenceTo>
        <relationshipName>Dummays</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Registration Info</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Dummay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>EV_Title__c</fullName>
        <description>Changed By Phani on 09/07/2012</description>
        <label>Title</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_WebsiteURL__c</fullName>
        <defaultValue>&apos;www.boothleads.com&apos;</defaultValue>
        <label>WebsiteURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Is_MatchMaking_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is MatchMaking Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Event in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Registration Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Registration Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Profile__c.object
<CustomObject>
    <fields>
        <fullName>PR_Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PR_Version__c</fullName>
        <label>Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Profile name</label>
    <nameField>
        <displayFormat>PR_{000}</displayFormat>
        <label>profile_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profile cus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TicketTypes__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>TicketTypes</relationshipLabel>
        <relationshipName>TicketTypes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Tickets_per_Order__c</fullName>
        <label>Max Tickets per Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section_Name__c</fullName>
        <label>Section Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TT_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TT_Available__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TT_Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TT_TicketType__c</fullName>
        <label>TicketType</label>
        <picklist>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ticket_Category__c</fullName>
        <label>Ticket Category</label>
        <picklist>
            <picklistValues>
                <fullName>Attendee</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non – Attendee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Non-Member/Guest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSDC Member Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSDC Certified MBE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TicketTypes</label>
    <nameField>
        <displayFormat>TT_{0000000}</displayFormat>
        <label>TT_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TicketTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Profile_Event__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventAdmin_Id__c</fullName>
        <label>EventAdmin</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Profile_Event2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile_id__c</fullName>
        <label>Profile</label>
        <referenceTo>Profile__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InActive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile only access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile and Portal Access</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_id__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User_Profile_Event</label>
    <nameField>
        <displayFormat>UPE_{00000000}</displayFormat>
        <label>UPE_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Profile_Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_BL_Special_Needs_Expos_Success_Con.cls
@isTest
public class Test_BL_Special_Needs_Expos_Success_Con{

 public static TestMethod void testMe(){
 Account Acc = new Account();
  Acc.Name = 'Booth Leads';
  insert Acc;

 Contact C = new Contact();
 C.LastName = 'Test';
 C.Accountid = Acc.id;
 insert C;
     Profile p = [select id from profile where name='Standard User'];

User u = new User(alias = 'test123', email='test123huh@noemail.com',
                 emailencodingkey='UTF-8',profileid = p.Id,lastname='Testing', languagelocalekey='en_US',
                  localesidkey='en_US',country='United States',
                  timezonesidkey='America/Los_Angeles', username='test123huh@noemail.com');
                  insert u;

                  Id eventAdminId=u.id;   

Profile__c customProfileBooth= new Profile__c (PR_Name__c='EventAdmin',PR_Version__c='3.0');        
       insert  customProfileBooth;
   
 
       
    
  Event__c eve = new Event__c(EV_Title__c='TestEvent',EV_WebsiteURL__c='https://www.globalnest.com',Is_MatchMaking_Event__c=True);
  insert eve;
  
   User_Profile_Event__c upeEA = new User_Profile_Event__c(EV_id__c=eve.id,EventAdmin_Id__c=eventAdminId,
    Profile_id__c=customProfileBooth.id,Status__c='Active',User_id__c=eventAdminId);         
      insert upeEA;   
      
       
  //Event__c eve = new Event__c(EV_Title__c='Aged Care 2014',EV_WebsiteURL__c='http://AgedCare2014.com',Is_MatchMaking_Event__c='true');
  //insert eve;
  
  
   Profile__c profileBA = new Profile__c(PR_Name__c='BoothAdmin');
   insert profileBA;
   
  TicketTypes__c tic = new TicketTypes__c(EV_id__c=eve.id,  TT_Name__c='TestEvent',TT_TicketType__c='Paid',Ticket_Category__c='Attendee',TT_Available__c=20,User_Type__c='MSDC Member Corporation',Max_Tickets_per_Order__c=5,TT_Amount__c=500,Section_Name__c ='ONE DAY CONFERENCE ATTENDEE');
  insert tic;
  
  TicketTypes__c tic2 = new TicketTypes__c(EV_id__c=eve.id,  TT_Name__c='TestEvent',TT_TicketType__c='Paid',Ticket_Category__c='Non – Attendee',TT_Available__c=20,User_Type__c='MSDC Member Corporation',Max_Tickets_per_Order__c=5,TT_Amount__c=500,Section_Name__c ='ONE DAY CONFERENCE ATTENDEE');
  insert tic2;
  
   Constomer__c cus2 = new  Constomer__c();
   cus2.Uniq_Number__c ='test';
   insert cus2;
  
   
  
  Dummay__c com2 = new Dummay__c(TicketTypes__c=tic.id,Phone__c='1234567899',Payment_Type__c='Invoice',Last_Name__c='Lame',InvoiceEmail__c='test123@noemail.com',First_Name__c='FName',Event__c=eve.id,Email__c='test@salesforce.com',Company__c='globa',Check_number__c='1234',customer_key__c=cus2.id);
  insert com2;
  
  
   AttendeeSummary__c att = new AttendeeSummary__c(AS_firstNAme__c='FName',AS_LastName__c='Lame',AS_Email__C='test@salesforce.com',AS_Company__c='Com');
   insert att;
  
   Constomer__c cus = new  Constomer__c();
   cus.Uniq_Number__c ='test';
   insert cus;
   
  Dummay__c com = new Dummay__c(TicketTypes__c=tic.id,Profile__c='BoothAdmin',Phone__c='1234567899',Payment_Type__c='Invoice',Last_Name__c='Lame',InvoiceEmail__c='test@salesforce.com',First_Name__c='FName',Event__c=eve.id,Email__c='test1@salesforce.com',Company__c='globa',Check_number__c='1234',customer_key__c=cus.id);
  insert com;
 

  AttendeeSummary__c att1 = new AttendeeSummary__c(AS_firstNAme__c='FName',AS_LastName__c='Lame',AS_Email__C='test1@salesforce.com',AS_Company__c='Com');
   insert att1;
  
 
  PageReference pg = Page.BL_RegistrationSuccess;
   Test.setCurrentPage(pg); 
       ApexPages.currentPage().getParameters().put('paykey', cus.id);
   
   BL_Special_Needs_Expos_Success_Con con = new BL_Special_Needs_Expos_Success_Con();
   con.MainMethod();
   con.redirectPage();
   Test.startTest();
   ApexPages.currentPage().getParameters().put('paykey', cus2.id);
   con.MainMethod();
   Test.stopTest();
     
 }


}