objects/AttendeeSummary__c.object
<CustomObject>
    <fields>
        <fullName>AS_FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AS_LastName__c</fullName>
        <label>LastName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AttendeeSummary</label>
    <nameField>
        <displayFormat>QR_AT_{dd}{yy}_{0000000}</displayFormat>
        <label>AS_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AttendeeSummary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Booth__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Booth</relationshipLabel>
        <relationshipName>Booth</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MM_TableNo__c</fullName>
        <label>MM_TableNo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Booth</label>
    <nameField>
        <displayFormat>BT_{00000000}</displayFormat>
        <label>Booth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>MM_End_Date__c</fullName>
        <label>MM End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MM_Slot_Timeperiod__c</fullName>
        <label>MM_Slot_Timeperiod</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MM_Start_Date__c</fullName>
        <label>MM Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MatchMaking_Type__c</fullName>
        <label>MatchMaking Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Match_Making_Schedules__c</fullName>
        <label>Match Making Schedules</label>
        <picklist>
            <picklistValues>
                <fullName>Live</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stop_Schedule_for_Mobile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stop Schedule for Mobile</label>
        <type>Checkbox</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event_Attendee_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>AS_id__c</fullName>
        <label>AttendeeSummary</label>
        <referenceTo>AttendeeSummary__c</referenceTo>
        <relationshipLabel>Event_Attendee_Mapping</relationshipLabel>
        <relationshipName>Event_Attendee_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event_Attendee_Mapping</relationshipLabel>
        <relationshipName>Event_Attendee_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event_Attendee_Mapping</label>
    <nameField>
        <displayFormat>EA{0000000000}</displayFormat>
        <label>EA_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event_Attendee_Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EventSchedule__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>EventSchedule</relationshipLabel>
        <relationshipName>EventSchedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Matchmaking__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Matchmaking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MM_Slot_End_Time__c</fullName>
        <label>MM Slot End Time</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MM_Slot_Status__c</fullName>
        <label>MM_Slot_Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rescheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MM_To_EAM__c</fullName>
        <label>Event_Attendee_Mapping</label>
        <referenceTo>Event_Attendee_Mapping__c</referenceTo>
        <relationshipLabel>EventSchedule</relationshipLabel>
        <relationshipName>EventSchedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MM_To_UPE__c</fullName>
        <label>User_Profile_Event</label>
        <referenceTo>User_Profile_Event__c</referenceTo>
        <relationshipLabel>EventSchedule</relationshipLabel>
        <relationshipName>EventSchedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MM_slot_Date__c</fullName>
        <label>MM slot Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MM_slot_StartTime__c</fullName>
        <label>MM slot StartTime</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>EventSchedule</label>
    <nameField>
        <displayFormat>ES_{00000000}</displayFormat>
        <label>ES_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventSchedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MatchLeads_Days__c.object
<CustomObject>
    <description>It is save no of days Match Leads will be and the timings when the matching will be started.</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>MatchLeads_Days</relationshipLabel>
        <relationshipName>MatchLeads_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAX_noOf_appontments__c</fullName>
        <label>MAX noOf appontments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MatchLeads_Date__c</fullName>
        <description>Date of match leads</description>
        <label>MatchLeads Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Slot_Time_period__c</fullName>
        <description>Time duration of slot.</description>
        <label>Slot Time period</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>MatchLeads_Days</label>
    <nameField>
        <displayFormat>D-{000}</displayFormat>
        <label>MatchLeads_Days Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MatchLeads_Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Profile_Event__c.object
<CustomObject>
    <fields>
        <fullName>Attendee_Summary__c</fullName>
        <label>Attendee_Summary</label>
        <referenceTo>AttendeeSummary__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BT_id__c</fullName>
        <label>Booth</label>
        <referenceTo>Booth__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsMatchMakingUser__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMatchMakingUser</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MAtchMakingProfile__c</fullName>
        <label>MAtchMakingProfile</label>
        <picklist>
            <picklistValues>
                <fullName>MBE</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CorporateStaff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WaitingList</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MM_TableNo__c</fullName>
        <label>MM_TableNo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User_id__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User_Profile_Event</label>
    <nameField>
        <displayFormat>UPE_{00000000}</displayFormat>
        <label>UPE_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Profile_Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MMScheduleReq.cls
@RestResource(urlMapping='/MMScheduleReq/*')


global without Sharing class MMScheduleReq{

@httpPost
global static AllDetails doPost(){
 
     RestRequest req = RestContext.request;
     RestResponse res = RestContext.response;
     string eveid;     
     string exhid;
     String attid;
     Date dateval;
     String CompDate;
     String timeval;
     String comments;
     String status;
     String loginid;
     
     
     eveid =req.params.get('eveid');
     exhid = req.params.get('exhid');
     attid = req.params.get('attid');
     CompDate = req.params.get('dateval');
     dateval = Date.Valueof(req.params.get('dateval'));     
     timeval = req.params.get('timeval');
     comments = req.params.get('comments');
     status = req.params.get('status');
     loginid = req.params.get('loginid');
     
     List<string> timesplit =timeval.split('-');
     
  system.debug('eveid------'+eveid);
   system.debug('exhibitorid------'+exhid );
    system.debug('dateval ------'+dateval );
     system.debug('attid------'+attid); // this is Event Attendee Mapping ID
      system.debug('timeval------'+timeval); 
       system.debug('status------'+status);
        system.debug('loginid ------'+loginid );
      
      AllDetails alDetail = new AllDetails();
      alDetail.eventscheduleStatus ='Live';
        FetchEventdetails evedetails= new FetchEventdetails();
        Event__c EventDet = new Event__c();
       
        if(eveid!=null && eveid!=''){  
          try{
            if(null !=evedetails.evedetails(eveid)){
                 EventDet = evedetails.evedetails(eveid);
                 alDetail.eventscheduleStatus = evedetails.evedetails(eveid).Match_Making_Schedules__c;
                 if(alDetail.eventscheduleStatus=='Closed'){
                   return alDetail;
                 }
            }
           }catch(exception er){} 
          } 
      
      
     
      //Eent_Attendee_Mapping__c eam = [SELECT Id FROM Event_Attendee_Mapping__c WHERE AS_id__r.Id =:attid AND EV_id__r.Id =: eveid];
      
     /* 
     // DateTime dt1 = DateTime.newInstance(2014,m,d,h,m,s,a);
     LIST<String> splitdt = CompDate.split('-');
     Integer cony = integer.valueOf(splitdt[0]);
     Integer conm = integer.valueOf(splitdt[1]);
     Integer cond = integer.valueOf(splitdt[2]);
     //Datetime dt1 = datetime.valueOf(splitdt[0]+'-'+splitdt[1]+'-'+splitdt[2]+' '+'00:00:00');
     
      system.debug('System.now()================='+System.now());
      //system.debug('Date()================='+ date());
      Integer ssplit;
      List<string> splitTm = timeval.split(':');
      system.debug('splitTm[0]========='+splitTm[0]);
      system.debug('splitTm[1]========='+splitTm[1]);
      if(timeval.Contains('PM' )){
          Integer sh = integer.valueOf(splitTm[0]);
          Integer sh1 = sh + 12;
          if(sh1==24){
                  ssplit = 00;
          }else{
              ssplit = sh1;
          }
      }else{
          Integer sh1 = integer.valueOf(splitTm[0]);
          ssplit = sh1;
      }
      
      Integer smsplit = Integer.Valueof(splitTm[1].subString(0, splitTm[1].IndexOf(' ')));
      system.debug('splittime=========    hrs=='+ssplit+'        minuts=='+smsplit);
      //Datetime dt1 = datetime.valueOf(splitdt[0]+'-'+splitdt[1]+'-'+splitdt[2]+' '+ssplit+':'+smsplit+':00');
       //system.debug('dt1================='+dt1);
      
      datetime cdt = datetime.newInstance(cony,conm,cond, ssplit, smsplit, 00);
      datetime cdtGmt = datetime.newInstanceGmt(cony,conm,cond, ssplit, smsplit, 00);
      datetime cdtlocal = datetime.valueOf(cony+'-'+conm+'-'+cond+' '+ssplit+':'+smsplit+':'+00);
       system.debug('condt================='+cdt);
       system.debug('condtGmt================='+cdtGmt);
       system.debug('cdtlocal ================='+cdtlocal );
       if(cdt<System.now()){
            system.debug('req time is less than current time');
            GlobalUtillClass.globalMessage mssge = new GlobalUtillClass.globalMessage('Invalid Date or time');
            alDetail.globalMessage.add(mssge);
            return alDetail;
       }else{
           
           system.debug('reqtime is greater than current time');
       }
       */
       
       
      
      /* This code works only for "Shelly" Event - "Connecticut Business Advantage 2014 Training and Matchmaker Event", This should be deleted after the event. */ 
      if((EventDet.Match_Making_Schedules__c == 'Closed' || EventDet.Stop_Schedule_for_Mobile__c) && status!='cancelled'){
          GlobalUtillClass.globalMessage mssge = new GlobalUtillClass.globalMessage('You are not authorized to schedule for this event. Please down load the latest version of app.');
          alDetail.globalMessage.add(mssge);
          return alDetail;
      }
      /* This code works only for "Shelly" Event - "Connecticut Business Advantage 2014 Training and Matchmaker Event", This should be deleted after the event. */ 
       
       
       
      List<MatchLeads_Days__c> checkEveDate = [SELECT Id, MAX_noOf_appontments__c FROM MatchLeads_Days__c WHERE Event__r.Id =:eveid AND MatchLeads_Date__c =:dateval ];
      if(checkEveDate.size()>0){     
          
      Integer appnmntsPerDay = Integer.Valueof(checkEveDate[0].MAX_noOf_appontments__c);
      system.debug('appnmntsPerDay======'+appnmntsPerDay);
      
      List<EventSchedule__c> eamAppntmnts = [SELECT Id, EV_id__c,MM_To_UPE__c,MM_slot_Date__c, MM_slot_StartTime__c 
                             FROM EventSchedule__c 
                             WHERE EV_id__c=:eveid 
                             AND MM_To_EAM__r.Id=:attid
                             AND MM_slot_Date__c =: dateval 
                             AND Is_Matchmaking__c =: TRUE 
                             AND (MM_Slot_Status__c = 'Accepted' or MM_Slot_Status__c = 'Pending') ];
      
       system.debug('eamAppntmnts======'+eamAppntmnts.size());          
       //totalExeAppntmnts = upeAppntmnts.size();
       //system.debug('upeAppntmnts======'+totalExeAppntmnts);                     
       if(eamAppntmnts.size()>=appnmntsPerDay){
           system.debug('You have reached maximum number of Appointments for that day');
           GlobalUtillClass.globalMessage mssge = new GlobalUtillClass.globalMessage('You have reached maximum number of Appointments for the day');
           alDetail.globalMessage.add(mssge);
           return alDetail;
       }                     
      
      User_Profile_Event__c upe = [SELECT Id,MAtchMakingProfile__c, EV_id__r.MM_Slot_Timeperiod__c, EV_id__r.MM_Start_Date__c,EV_id__r.MM_End_Date__c  FROM User_Profile_Event__c WHERE IsMatchMakingUser__c = true AND User_id__r.Id =:exhid AND EV_id__r.Id =: eveid];
      
      Date checkeveate = Date.ValueOf(dateval);
      
      List<EventSchedule__c> checkattslot = [SELECT Id, EV_id__c,MM_To_UPE__c,MM_slot_Date__c, MM_slot_StartTime__c 
                             FROM EventSchedule__c 
                             WHERE EV_id__c=:eveid 
                             AND MM_To_EAM__r.Id =: attid /* AND MM_To_UPE__r.User_id__r.Id=:exhid */ 
                             AND MM_slot_StartTime__c =: timeval AND MM_slot_Date__c =: dateval 
                             AND Is_Matchmaking__c =: TRUE 
                             AND (MM_Slot_Status__c = 'Accepted' or MM_Slot_Status__c = 'Pending') ];
                             
      if(checkattslot.size()>0){
      system.debug('slot is booked');
      GlobalUtillClass.globalSuccess mssge = new GlobalUtillClass.globalSuccess(checkattslot[0].Id, 'You already have an appointment at this time');
      alDetail.globalSuccess.add(mssge);
      return alDetail;
      }else {      
     
      List<EventSchedule__c> checkslot = [SELECT Id, EV_id__c,MM_To_UPE__c,MM_slot_Date__c, MM_slot_StartTime__c 
                             FROM EventSchedule__c 
                             WHERE EV_id__c=:eveid 
                             AND MM_To_EAM__r.Id =: attid 
                             AND MM_To_UPE__r.User_id__r.Id=:exhid 
                             AND /* MM_slot_StartTime__c =: timeval AND*/ MM_slot_Date__c =: dateval 
                             AND Is_Matchmaking__c =: TRUE 
                             AND (MM_Slot_Status__c = 'Accepted' or MM_Slot_Status__c = 'Pending') ];
      if(checkslot.size()>0){
      system.debug('slot is booked');
      GlobalUtillClass.globalSuccess mssge = new GlobalUtillClass.globalSuccess(checkslot[0].Id, 'You have reached the maximum appointment limit with '); /* You cannot schedule more than one appointment with a Exhibitor */ 
      alDetail.globalSuccess.add(mssge);
      return alDetail;
      }else{
      system.debug('slot is not booked yet');
      system.debug('--------------Event Id------: '+eveid);
      Event__c E = new Event__c ();
      E = [select id,MatchMaking_Type__c from Event__c Where id =: eveid ];
      
      MatchLeads_Days__c ed = new MatchLeads_Days__c();
      ed = [SELECT Id,MatchLeads_Date__c,Slot_Time_period__c, MAX_noOf_appontments__c FROM MatchLeads_Days__c WHERE Event__c =:eveid AND MatchLeads_Date__c=:dateval];
      system.debug('--------------Match Making Type------: '+E.MatchMaking_Type__c);
      EventSchedule__c ESCH= new  EventSchedule__c();
      ESCH.EV_id__c  = eveid;
      ESCH.MM_To_UPE__c = upe.id ;
      ESCH.MM_slot_Date__c = dateval ;
      //ESCH.MM_slot_StartTime__c = timeval;
      ESCH.MM_slot_StartTime__c = timesplit[0];
      ESCH.Is_Matchmaking__c = TRUE;
      ESCH.Comments__c = comments;
      if(E.MatchMaking_Type__c == 'Semi Open'){
      ESCH.MM_Slot_Status__c = 'Pending';
      }else if(E.MatchMaking_Type__c == 'Open'){
      ESCH.MM_Slot_Status__c = 'accepted';
      }
      else if(E.MatchMaking_Type__c == 'Closed'){
      ESCH.MM_Slot_Status__c = 'accepted';
      }
      ESCH.OwnerId = loginid;
      //ESCH.LastModifiedBy.Id = loginid;      
      ESCH.MM_To_EAM__c = attid;
      
      /*List<string> sthour =new List<string>();
      sthour =timeval.split(':'); 
      integer hh = integer.valueof(sthour[0]);
      integer mm =  integer.valueof(sthour[1].subString(0, sthour[1].IndexOf(' ')));
      
      system.debug(hh+'    11111111111111111     '+ mm);
      
      if(mm+integer.valueOf(ed.Slot_Time_period__c) >= 60){
          hh+=1;
          mm = mm+integer.valueOf(ed.Slot_Time_period__c);
          mm-= 60;
           
      }else{
          mm = mm+integer.valueOf(ed.Slot_Time_period__c);
      
      }
    
      String scheduleEndTime='';
      if(hh < 12 && timeval.Contains('AM' )){
                 if(hh<=9){
                  scheduleEndTime = string.valueOf('0'+hh+':'+mm +' AM');
              }else{
                  scheduleEndTime = string.valueOf(hh+':'+mm +' AM');
              }
      }else{
       if(hh<=9){
                   scheduleEndTime = string.valueOf('0'+hh+':'+mm +' PM');
               }else{
                   scheduleEndTime = string.valueOf(hh+':'+mm +' PM');
               }
      }
     
     
      Time mmstartTime = Time.newInstance(hh, mm, 00, 00);
      //Time scheduleEndTime = Time.newInstance(hh, mm, 00, 00);
       system.debug('   333333333333333333333   '+ scheduleEndTime );
       
      //time endtime = mmstartTime.addMinutes(integer.valueOf(upe.EV_id__r.MM_Slot_Timeperiod__c));
      //ESCH.MM_Slot_End_Time__c = string.valueof(endtime);
      
      */
      //ESCH.MM_Slot_End_Time__c = scheduleEndTime;
      ESCH.MM_Slot_End_Time__c = timesplit[1];
      insert ESCH;
      system.debug(' esid '+ESCH.id);
      Id resultid = ESCH.id;
      
      
      if(resultid != NULL){
      
      GlobalUtillClass.globalSuccess mssge = new GlobalUtillClass.globalSuccess(ESCH.id, 'Succesfully Scheduled');
      alDetail.globalSuccess.add(mssge);
      
      if(upe.MAtchMakingProfile__c == 'MBE'){
      
              EventSchedule__c newSlotDet = [SELECT Id, MM_slot_Date__c, MM_slot_StartTime__c, MM_Slot_End_Time__c, 
                  MM_Slot_Status__c, MM_To_UPE__r.BT_id__r.MM_TableNo__c, MM_To_UPE__r.Attendee_Summary__r.Id, 
                  MM_To_EAM__r.AS_id__r.AS_FirstName__c, MM_To_EAM__r.AS_id__r.AS_LastName__c, OwnerId 
                  FROM EventSchedule__c WHERE Id =: ESCH.id ];
         
          GlobalUtillClass.NewSlotDetils nsd = new GlobalUtillClass.NewSlotDetils(newSlotDet, 'Corporate');
          alDetail.NewSlotDetils.add(nsd);
      }else  if(upe.MAtchMakingProfile__c == 'Corporate'){
      
              EventSchedule__c newSlotDet = [SELECT Id, MM_slot_Date__c, MM_slot_StartTime__c, MM_Slot_End_Time__c, 
                  MM_Slot_Status__c, MM_To_UPE__r.BT_id__r.MM_TableNo__c, MM_To_UPE__r.Attendee_Summary__r.Id, 
                  MM_To_UPE__r.Attendee_Summary__r.AS_FirstName__c, MM_To_UPE__r.Attendee_Summary__r.AS_LastName__c, OwnerId 
                  FROM EventSchedule__c WHERE Id =: ESCH.id ];
         
          GlobalUtillClass.NewSlotDetils nsd = new GlobalUtillClass.NewSlotDetils(newSlotDet, 'MBE');
          alDetail.NewSlotDetils.add(nsd);
      }
      
      
      return alDetail;
      }else{
      GlobalUtillClass.globalSuccess mssge = new GlobalUtillClass.globalSuccess(ESCH.id, 'Scheduling Failed');
     alDetail.globalSuccess.add(mssge);
     return alDetail;
      }
      }
      }
      
      
    }else{
      GlobalUtillClass.globalSuccess mssge = new GlobalUtillClass.globalSuccess('', 'Invalid Date for this event');
      alDetail.globalSuccess.add(mssge);
      return alDetail;
    }
      
 return null;

 }
 
 
 
global class AllDetails{
List<GlobalUtillClass.globalMessage> globalMessage = new List<GlobalUtillClass.globalMessage>();
List<GlobalUtillClass.globalSuccess> globalSuccess = new List<GlobalUtillClass.globalSuccess>();
List<GlobalUtillClass.NewSlotDetils> NewSlotDetils = new List<GlobalUtillClass.NewSlotDetils>();
string eventscheduleStatus = '';
}
  

 }