objects/AttendeeSummary__c.object
<CustomObject>
    <fields>
        <fullName>AS_CellPhone__c</fullName>
        <label>CellPhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>AS_Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AS_Email__c</fullName>
        <description>Mallikarjuna Set-Up  Email Field As External ID</description>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AS_FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AS_HomeCity__c</fullName>
        <label>HomeCity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AS_HomeState__c</fullName>
        <label>HomeState</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AS_ImageUrl__c</fullName>
        <label>ImageUrl</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>AS_LastName__c</fullName>
        <label>LastName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AS_WorkCity__c</fullName>
        <label>WorkCity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AS_Work_Country__c</fullName>
        <label>Work_Country</label>
        <picklist>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States Of America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sweden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uzbekistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Africa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sverige</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Netherlands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portugal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Switzerland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AS_Work_States__c</fullName>
        <label>Work_States</label>
        <picklist>
            <controllingField>AS_Work_Country__c</controllingField>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nebraska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nevada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Hampshire</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AS_uniqueField__c</fullName>
        <label>AS uniqueField</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>AttendeeSummary</label>
    <nameField>
        <displayFormat>QR_AT_{dd}{yy}_{0000000}</displayFormat>
        <label>AS_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AttendeeSummary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <label>BLN Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SaveUserProfile.cls
@RestResource(urlMapping='/SaveUserProfile/*')

/*
 * AUTHOR : Venkatesh 
 * Email :  venkatesh@globalnest.com
 * AIM :    To update the User information from the mobile  clients
 ***/  
 
            global class SaveUserProfile{
    
            global static List<UserInfo> UserInfos = new List<UserInfo>();
            
            global static UserInfo UserInfoDetails = new UserInfo();
            
            global Static list<String> userInfostr =  new list<String>();
            global static User LoginUser  = new User();
            global static AttendeeSummary__c  AttSummary= new AttendeeSummary__c();
            
            global static Attachment attachOne= new  Attachment();
            
            
            
        
            @HttpPost
            global static UserInfo doPost(){
                
               //Request Context
               
             
                RestRequest req = RestContext.request;
                RestResponse res = RestContext.response;
                String UserId= req.params.get('UserID');
    Blob reqbody =req.requestBody;
    String UserProfile= reqbody.toString();
          
 system.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'+UserProfile);
   
               // String UserProfile= req.headers.get('UserProfile');
                String Firstname;
                String Lastname;
                String Email;
                
                //String UserProfile ='[{"FirstName":"Ap","LastName":"S","Company":"James","City":"soi.venkatesh@gmail.com","State":"India","Phoneno":"Hyd"}]';
                
                JSONParser Parser = JSON.createParser(UserProfile);
                
                
                
                While(parser.nextToken()!= null){
        
                     if(Parser.getCurrenttoken() == JSONToken.START_ARRAY){
                     while(parser.nextToken() != null){
                        if(parser.getCurrenttoken() == JSONToken.START_OBJECT){
                     UserInfoDetails  = (SaveUserProfile.UserInfo)parser.readValueAs(SaveUserProfile.UserInfo.class);}     
            }}}

                LoginUser = [select id,firstName,LastName,Email,CompanyName,Phone,City,State from User where id=:UserId];
                AttSummary =[Select id,AS_FirstName__c,AS_LastName__c,AS_Company__c,AS_CellPhone__c,AS_HomeCity__c,AS_HomeState__c from AttendeeSummary__c where   AS_Email__c=:LoginUser.Email];
                 
                Firstname = LoginUser.firstName;
                Lastname  = LoginUser.LastName; 
     
               if(!(String.isEmpty(UserInfoDetails.firstName))){
                 LoginUser.firstName= UserInfoDetails.firstName;
                 AttSummary.AS_FirstName__c =UserInfoDetails.firstName;
                 Firstname  =  UserInfoDetails.firstName;
                 }
               
               if(!(String.isEmpty(UserInfoDetails.LastName))){
                  LoginUser.Lastname = UserInfoDetails.LastName;
                  AttSummary.AS_LastName__c =UserInfoDetails.LastName;
                  Lastname = UserInfoDetails.LastName;
                  } 
                 
                 if(!(String.isEmpty(UserInfoDetails.Company))){
                 
                  LoginUser.CompanyName=UserInfoDetails.Company;
                  AttSummary.AS_Company__c = UserInfoDetails.Company;
                  }
                 
                 if(!(String.isEmpty(UserInfoDetails.City))){
                 
                  LoginUser.City = UserInfoDetails.City;
                  AttSummary.AS_WorkCity__c= UserInfoDetails.City;                
                 }
                 
             if(!(String.isEmpty(UserInfoDetails.State))){    
                 
                 LoginUser.States__c  = UserInfoDetails.State;
                 AttSummary.AS_Work_States__c= UserInfoDetails.State;
                 
                 }
                 
                 if(!(String.isEmpty(UserInfoDetails.Phoneno))){  
                  LoginUser.Phone= UserInfoDetails.Phoneno;
                  AttSummary.AS_CellPhone__c = UserInfoDetails.Phoneno;
                  }
                
                if(!(String.isEmpty(UserInfoDetails.Country))){
                
                LoginUser.Country__c = UserInfoDetails.Country;
                AttSummary.AS_Work_Country__c= UserInfoDetails.Country;
               }                
                
                  
             
             
             
                 AttSummary.AS_uniqueField__c = String.valueOf(FirstName+LastName+LoginUser.email).toLowerCase();
                 
              
                   
                   /**
                   Document UserImageDoc = new Document();
                   UserImageDoc.Body = EncodingUtil.base64Decode(UserInfoDetails.ImageBlob);
                   UserImageDoc.FolderId ='00l90000001APdg';
                   UserImageDoc.Name = Firstname +' '+Lastname+' Image'; 
                   UserImageDoc.IsPublic =true;
                   Database.SaveResult UseImageSaveresult =  Database.insert(UserImageDoc);
                   
                   if (UseImageSaveresult.isSuccess()== True){                
                    AttSummary.AS_ImageUrl__c = UseImageSaveresult.getId();
                    }
                    **/

                 
                 
                      
                try{
                
                System.debug('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@beforeUpdate'+LoginUser);
                 //update LoginUser;
                 Database.saveResult  updateLoginUser = Database.update(LoginUser);
                  System.debug('DDDDDDDDDDDDDDDDDDDD'+updateLoginUser );
                 Database.saveResult  updateAttSummary = Database.update(AttSummary);
                  System.debug('FFFFFFFFFFFFFFFFFFFFFFFFFFFFF '+updateAttSummary );
                //update AttSummary;
                 
                 if(updateAttSummary.isSuccess() == true && !(String.isEmpty(UserInfoDetails.ImageBlob))){
                      attachOne.Name = LoginUser.id+'Image';
                      attachOne.Body = EncodingUtil.base64Decode(UserInfoDetails.ImageBlob);
                
                      attachOne.ParentId =updateAttSummary.getId();
                      
                      Schema.SObjectField f = Attachment.Fields.Name;
                      
                      Database.upsertResult attachmentUpsert = Database.upsert(attachOne,f,false);
                   
                      
                UserInfo Uin = new UserInfo();
                 Uin.Message ='Update successFully';
                 return Uin; 
                   
                   }
                   
                 }
                 
                 
                 
                
                catch(Exception ex){
                
                system.debug('@@@@@@@@@@@@@@@@'+ex.getmessage());
                UserInfo Uin = new UserInfo();
                 Uin.Message ='Update unsuccessFully';
                 return Uin; 
                
                }
                
                
                
                
                 return null; 
                
                }
                
                
                global class UserInfo{
                String Message;
                
                String FirstName;
                
                String LastName;
                
                String Company;
                
                String City;
                
                String State;
                
                String Phoneno;
                
                String UserImage;
                
                String ImageBlob;
                String Country;
              
                                
                }
                
                
           
                
                 
                
                }