objects/AttendeeSummary__c.object
<CustomObject>
    <fields>
        <fullName>AS_Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AS_WorkPhone__c</fullName>
        <label>WorkPhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Exhibitor_company_imageUrl__c</fullName>
        <label>Exhibitor company imageUrl</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>FullName__c</fullName>
        <formula>AS_FirstName__c  &amp; &apos; &apos; &amp; AS_LastName__c</formula>
        <label>FullName</label>
        <type>Text</type>
    </fields>
    <label>AttendeeSummary</label>
    <nameField>
        <displayFormat>QR_AT_{dd}{yy}_{0000000}</displayFormat>
        <label>AS_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AttendeeSummary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Booth__c.object
<CustomObject>
    <fields>
        <fullName>BT_Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BT_Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Booth</relationshipLabel>
        <relationshipName>Booth</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MM_TableNo__c</fullName>
        <label>MM_TableNo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Table_Room_No__c</fullName>
        <label>Table/Room-No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Booth</label>
    <nameField>
        <displayFormat>BT_{00000000}</displayFormat>
        <label>Booth Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booth</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>AS_HostingCity__c</fullName>
        <label>HostingCity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_EventLogo__c</fullName>
        <label>EventLogo</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>EV_HistingAddr1__c</fullName>
        <label>HistingAddr1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_HostingLocation__c</fullName>
        <label>HostingLocation</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_HostingState__c</fullName>
        <label>HostingState</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_HostingZipcode__c</fullName>
        <label>HostingZipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Title__c</fullName>
        <description>Changed By Phani on 09/07/2012</description>
        <label>Title</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Webank_event__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Webank event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MatchMaking_Type__c</fullName>
        <label>MatchMaking Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Event in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Registration Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Registration Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event_Attendee_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event_Attendee_Mapping</relationshipLabel>
        <relationshipName>Event_Attendee_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event_Attendee_Mapping</label>
    <nameField>
        <displayFormat>EA{0000000000}</displayFormat>
        <label>EA_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event_Attendee_Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EventSchedule__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>EventSchedule</relationshipLabel>
        <relationshipName>EventSchedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MM_Slot_EndTime__c</fullName>
        <label>MM_Slot_EndTime(DEL)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MM_Slot_End_Time__c</fullName>
        <label>MM Slot End Time</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MM_Slot_Status__c</fullName>
        <label>MM_Slot_Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rescheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MM_Slot_Time__c</fullName>
        <label>MM_Slot_StartTime(Del)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MM_To_EAM__c</fullName>
        <label>Event_Attendee_Mapping</label>
        <referenceTo>Event_Attendee_Mapping__c</referenceTo>
        <relationshipLabel>EventSchedule</relationshipLabel>
        <relationshipName>EventSchedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MM_To_UPE__c</fullName>
        <label>User_Profile_Event</label>
        <referenceTo>User_Profile_Event__c</referenceTo>
        <relationshipLabel>EventSchedule</relationshipLabel>
        <relationshipName>EventSchedule</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MM_slot_Date__c</fullName>
        <label>MM slot Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MM_slot_StartTime__c</fullName>
        <label>MM slot StartTime</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>starttimein24hrs__c</fullName>
        <formula>If(RIGHT(MM_slot_StartTime__c,2) == &apos;PM&apos; , IF(LEFT(MM_slot_StartTime__c,2) != &apos;12&apos; , 
TEXT(VALUE(LEFT(MM_slot_StartTime__c, 2))+12)+  RIGHT(MM_slot_StartTime__c, 6), 
MM_slot_StartTime__c)



 ,MM_slot_StartTime__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MM_Slot_Starttimein24hrs</label>
        <type>Text</type>
    </fields>
    <label>EventSchedule</label>
    <nameField>
        <displayFormat>ES_{00000000}</displayFormat>
        <label>ES_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventSchedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tags__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Tags</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Matchleads Tabs</label>
    <nameField>
        <displayFormat>Tag-{000}</displayFormat>
        <label>Tags Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matchleads Tabs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Profile_Event__c.object
<CustomObject>
    <fields>
        <fullName>Attendee_Summary__c</fullName>
        <label>Attendee_Summary</label>
        <referenceTo>AttendeeSummary__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BT_id__c</fullName>
        <label>Booth</label>
        <referenceTo>Booth__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BoothAdmin_id__c</fullName>
        <label>BoothAdmin</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Profile_Event1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventAdmin_Id__c</fullName>
        <label>EventAdmin</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Profile_Event2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsBoothPersonnel__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsBoothPersonnel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMatchMakingUser__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMatchMakingUser</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MAtchMakingProfile__c</fullName>
        <label>MAtchMakingProfile</label>
        <picklist>
            <picklistValues>
                <fullName>MBE</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CorporateStaff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WaitingList</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MM_TableNo__c</fullName>
        <label>MM_TableNo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profile_id__c</fullName>
        <label>Profile</label>
        <referenceTo>Profile__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_for_upgrade_profile__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this check box will be fiiled from sign up page if the user is already exist with attendee and from sign up he selected as Corporate.</description>
        <label>Request for upgrade profile</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Slot_Time_Interval__c</fullName>
        <label>Slot Time Interval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InActive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile only access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile and Portal Access</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UEP_isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_id__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isFirstBoothAdmin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isFirstBoothAdmin</label>
        <type>Checkbox</type>
    </fields>
    <label>User_Profile_Event</label>
    <nameField>
        <displayFormat>UPE_{00000000}</displayFormat>
        <label>UPE_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Profile_Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PrimeContractorAllSlotsSchedules.cls
public with sharing class PrimeContractorAllSlotsSchedules {
        
        
        public LIST<CorporateSchedules> MatchLeadsschedules{get; set;}
        public String eventSelected{get;set;} 
        public list<Tags__c> tagslist {get; set ;}
        public string attendeealias {get ; set ;}
        public string exhibitoralias {get ; set ;}
        public Event__c attach{get;set;}
        
        public  PrimeContractorAllSlotsSchedules(){
           attendeealias ='';
           exhibitoralias ='';      
                LIST<User_Profile_Event__c> corporateUsers = new LIST<User_Profile_Event__c>();
               Cookie k = ApexPages.currentPage().getCookies().get('counter');
               eventSelected = k.getValue();
                
                attach = [select EV_EventLogo__c,MatchMaking_Type__c, EV_Title__c,EV_HostingLocation__c, EV_HistingAddr1__c, AS_HostingCity__c, EV_HostingZipcode__c, 
                          EV_StartDate__c, EV_EndDate__c, EV_HostingState__c from Event__c where id = : eventSelected];
                          
                corporateUsers = [Select u.isFirstBoothAdmin__c, u.User_id__c, u.UEP_isActive__c, u.Status__c, 
                                u.Slot_Time_Interval__c, u.Request_for_upgrade_profile__c, u.Profile_id__c, u.OwnerId, u.Name, u.MM_TableNo__c, 
                                u.MAtchMakingProfile__c, u.IsMatchMakingUser__c, u.IsBoothPersonnel__c,u.Id, 
                                u.BT_id__r.BT_Name__c, u.EventAdmin_Id__c, u.EV_id__c, u.BoothAdmin_id__c,
                                u.EV_id__r.EV_Title__c,  u.EV_id__r.EV_StartDate__c, u.EV_id__r.EV_EndDate__c, u.EV_id__r.EV_HostingLocation__c, u.EV_id__r.EV_HistingAddr1__c,u.EV_id__r.Is_Webank_event__c,
                                u.EV_id__r.AS_HostingCity__c, u.EV_id__r.EV_HostingState__c, u.EV_id__r.EV_HostingZipcode__c ,u.EV_id__r.EV_EventLogo__c,
                                u.Attendee_Summary__r.Exhibitor_company_imageUrl__c, u.Attendee_Summary__r.AS_Company__c, u.Attendee_Summary__r.FullName__c,
                                u.Attendee_Summary__r.AS_WorkPhone__c,u.BT_id__r.Table_Room_No__c, u.BT_id__r.MM_TableNo__c,u.BT_id__r.BT_Location__c,
                                (Select e.starttimein24hrs__c, e.SystemModstamp, e.OwnerId, e.Name, e.MM_slot_StartTime__c, e.MM_slot_Date__c, e.MM_To_UPE__c, 
                                e.MM_To_EAM__c, e.MM_Slot_Time__c, e.MM_Slot_Status__c, e.MM_Slot_End_Time__c, e.MM_Slot_EndTime__c, e.Is_Matchmaking__c, 
                                e.IsDeleted, e.Id, e.EV_id__c,e.EV_id__r.Is_Webank_event__c, e.ES_StartTime__c, e.ES_StartDate__c, e.ES_ProgramName__c, e.ES_Presenter__c, e.ES_Location__c, 
                                e.ES_EndTime__c, e.ES_EndDate__c, e.ES_Description__c, e.CreatedDate, e.CreatedById, e.Comments__c,e.MM_To_EAM__r.MBE_Profile__r.AS_FirstName__c,e.MM_To_EAM__r.MBE_Profile__r.AS_LastName__c,e.MM_To_EAM__r.MBE_Profile__r.AS_WorkPhone__c,e.MM_To_EAM__r.MBE_Profile__r.FullName__c,
                                e.MM_To_EAM__r.MBE_Profile__r.AS_Email__c,e.MM_To_EAM__r.MBE_Profile__r.AS_Company__c,e.MM_To_EAM__r.MBE_Profile__r.AS_CellPhone__c, 
                                e.MM_To_EAM__r.AS_id__r.AS_Company__c,e.MM_To_EAM__r.AS_id__r.FullName__c,e.MM_To_EAM__r.AS_id__r.AS_Email__c, e.MM_To_EAM__r.AS_id__r.AS_CellPhone__c From EventSchedule__r e WHERE e.MM_Slot_Status__c='Accepted' ORDER BY e.MM_slot_Date__c, e.MM_slot_StartTime__c )
                  FROM User_Profile_Event__c u WHERE MAtchMakingProfile__c ='Corporate'  AND Ev_id__c =: eventSelected   ];
                        
                 
                MAP<Date , LIST<String>> getSlotsFromUtility = MM_Utility.giveEventTimingsWithDates(eventSelected ,null);
                LIST<String> eventSchedules = new LIST<String>();
                for(Date d: getSlotsFromUtility.keySet()){
                   eventSchedules.addAll(getSlotsFromUtility.get(d));
                }
                
                
                
                MatchLeadsschedules = new  LIST<CorporateSchedules>();  
                
                 for(User_Profile_Event__c u: corporateUsers){
                        
                        LIST<displayUPESchedules> upeBasedSchedules = new LIST<displayUPESchedules>();
                        
                        
                        MAP<String, EventSchedule__c> upeEventScheduleMap = new MAP<String, EventSchedule__c>();
                        
                        for(EventSchedule__c es: u.EventSchedule__r){
                                upeEventScheduleMap.put( es.MM_slot_StartTime__c+'-'+  es.MM_Slot_End_Time__c , es  );
                        }
                        
                        for(String s: eventSchedules){
                                
                                if(upeEventScheduleMap.containsKey(s)){
                                        upeBasedSchedules.add(new displayUPESchedules(s, upeEventScheduleMap.get(s)));
                                }else{
                                        EventSchedule__c emptySchedule = new EventSchedule__c();
                                        upeBasedSchedules.add(new displayUPESchedules(s, emptySchedule));
                                }
                                
                        }
                        
                        
                        MatchLeadsschedules.add(new CorporateSchedules(u, upeBasedSchedules));
                        
                        
                 }
                 
       tagslist = [select id,Default_Name__c,Alias_Name__c from Tags__c where Event__c = : eventSelected];
       for(Tags__c tt: tagslist ){
       if(tt.Default_Name__c == 'Attendee'){
       attendeealias = tt.Alias_Name__c;
       }else if(tt.Default_Name__c == 'Exhibitor'){
       exhibitoralias = tt.Alias_Name__c;
       }
       
       }
                 
                 
        }
        
        
        public class displayUPESchedules{
                
                public String slotTime{get; set;}
        //      public User_Profile_Event__c corporate{get; set;}
                public EventSchedule__c schedule{get; set;}
                
                
                public displayUPESchedules(String scheduleTime, EventSchedule__c sch  ){
                        
                        slotTime = scheduleTime;
                         
                        schedule = sch;
                        
                        
                }
        }
        
        public class CorporateSchedules{
                public User_Profile_Event__c corporate{get; set;}
                public LIST<displayUPESchedules> displaySchedules{get; set;}
                
                public CorporateSchedules( User_Profile_Event__c upp, LIST<displayUPESchedules> sch ){
                        
                        corporate = upp;
                        displaySchedules = new LIST<displayUPESchedules>();
                        displaySchedules = sch;
                        
                }
                
                
                
        }
        
        
        

}