objects/AttendeeSummary__c.object
<CustomObject>
    <fields>
        <fullName>AS_Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AS_Email__c</fullName>
        <description>Mallikarjuna Set-Up  Email Field As External ID</description>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AS_FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AS_LastName__c</fullName>
        <label>LastName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AttendeeSummary</label>
    <nameField>
        <displayFormat>QR_AT_{dd}{yy}_{0000000}</displayFormat>
        <label>AS_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AttendeeSummary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event_Attendee_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>AS_id__c</fullName>
        <label>AttendeeSummary</label>
        <referenceTo>AttendeeSummary__c</referenceTo>
        <relationshipLabel>Event_Attendee_Mapping</relationshipLabel>
        <relationshipName>Event_Attendee_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attendee_Source__c</fullName>
        <label>Attendee Source</label>
        <picklist>
            <picklistValues>
                <fullName>Walk Ins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre Registered</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event_Attendee_Mapping</relationshipLabel>
        <relationshipName>Event_Attendee_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event_Attendee_Mapping</label>
    <nameField>
        <displayFormat>EA{0000000000}</displayFormat>
        <label>EA_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event_Attendee_Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Walkinsreportcon.cls
public without sharing class Walkinsreportcon {

 
 public list< Event_Attendee_Mapping__c> lieam{get;set;}
 public list< Event_Attendee_Mapping__c> eamexp{get;set;}
 public string selectedEvent{get;set;}
 
 public Walkinsreportcon()
 {
  selectedEvent =Apexpages.CurrentPage().getParameters().get('id'); 
  lieam= new list< Event_Attendee_Mapping__c>();
  lieam=[SELECT id,AS_id__r.id,AS_id__r.AS_Email__c,AS_id__r.AS_Company__c,AS_id__r.AS_FirstName__c,Createddate,AS_id__r.AS_LastName__c from Event_Attendee_Mapping__c 
         WHERE EV_id__c =:selectedEvent AND Attendee_Source__c='Walk Ins'];
  
 }

 public pagereference export()
 {
  eamexp= new list< Event_Attendee_Mapping__c>();
  eamexp=[SELECT id,AS_id__r.id,AS_id__r.AS_Email__c,AS_id__r.AS_Company__c,AS_id__r.AS_FirstName__c,Createddate,AS_id__r.AS_LastName__c from Event_Attendee_Mapping__c 
         WHERE EV_id__c =:selectedEvent AND Attendee_Source__c='Walk Ins'];
         
    PageReference pageRef= new PageReference('/apex/Exportwalkins');
    pageRef.setredirect(false);
    return pageRef;   
         
 }


}