objects/Badge__c.object
<CustomObject>
    <fields>
        <fullName>Cancel_Reason__c</fullName>
        <label>Cancel Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stolen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forgot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Exp_time__c</fullName>
        <label>Exp time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ticket_id__c</fullName>
        <label>ticket id</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipName>badges</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Badge</label>
    <nameField>
        <displayFormat>BDG-{0000000}</displayFormat>
        <label>Badge Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Event__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <description>Password invited guests</description>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>item_type__c</fullName>
        <label>Item type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Track__c.object
<CustomObject>
    <description>Various Tracks within event
This can be a morning session or evening session for an event
This can be Java Track or .Net track for seminars</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Tracks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Company__c.object
<CustomObject>
    <description>user companyWhen company information is null in input form. create a company with just user name and assign user role of company admin.</description>
    <label>BLN Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipName>Countries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Display of the countries in list</description>
        <label>Display Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Currency__c.object
<CustomObject>
    <label>BLN Currency</label>
    <nameField>
        <label>Currency Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Currency</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GN_User__c.object
<CustomObject>
    <description>The address fields belong to user home address
This should be the only link between gnuser and salesforce user. salesforce user table should not be accessible any where else in db except this table.</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BLN GN User</label>
    <nameField>
        <displayFormat>GNU-{000000}</displayFormat>
        <label>GN User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN GN Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Scan__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Lead_Scans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scan_Time__c</fullName>
        <label>Scan Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scanner_Company__c</fullName>
        <label>Scanner Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Lead_Scans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scanner_User__c</fullName>
        <label>Scanner User</label>
        <referenceTo>GN_User__c</referenceTo>
        <relationshipName>Lead_Scans1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>country__c</fullName>
        <label>country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>state</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>BLN Lead Scan</label>
    <nameField>
        <displayFormat>LS-{00000000}</displayFormat>
        <label>Lead Scan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Lead Scans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>BLN Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>State</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN State</label>
    <nameField>
        <label>State Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Badge_ID__c</fullName>
        <label>Badge ID</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_ID__c</fullName>
        <label>Parent ID</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tkt_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Tickets</relationshipLabel>
        <relationshipName>BLN_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tkt_profile__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN TKT profile</label>
    <nameField>
        <displayFormat>TP-{0000000}</displayFormat>
        <label>tkt profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN TKT profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_BLN_Ls_Addlead.cls
@istest
public class Test_BLN_Ls_Addlead{
     static testmethod void Test_BLN_Ls_Addlead(){
     
    globalForTestClass globalTest= new globalForTestClass();
    
   Profile p = [select id from profile where name='System Administrator'];
         userRole r=[SELECT ID FROM userRole WHERE name =: 'CEO'];   
         
  
         User u = new User(alias = 'Tes8t', email='testc8ode123x1@noemail.com',
                           emailencodingkey='UTF-8',profileid = p.Id,lastname='codeTesting', Firstname='codeTesting', languagelocalekey='en_US',
                           localesidkey='en_US',country='United States Of America', userRoleId= r.id, CompanyName= 'GlobalNest',password__c='rajendra',
                           timezonesidkey='America/Los_Angeles', username='testc8ode123x1@noemail.com');
                           
        system.runas(U){
                            
            User userForGN= new User();
            userForGN= globalTest.createUserForGNUser();
            
            Tkt_profile__c  tktprof = new Tkt_profile__c();
            tktprof=globalTest.createTktprofile(userForGN);
            
            Company__c companyInfo= new Company__c();
            
            companyInfo= globalTest.createCompany(u.Companyname);
            
            Currency__c currenyInfo= new Currency__c();
            currenyInfo= globalTest.createCurrency();             
            
            Country__c countryInfo= new Country__c();
            countryInfo= globalTest.createCountry(currenyInfo.Id);  
            
            State__c stateInfo= new State__c ();
            stateInfo= globalTest.createState(countryInfo.Id);
            
            GN_User__c  gnUserInfo= new GN_User__c();
            gnUserInfo= globalTest.createGNUser(u, countryInfo.Id, stateInfo.Id);
            
            GN_User__c  gnUser= new GN_User__c();
            gnUser = globalTest.createGNUser(userForGN,countryInfo.Id, Stateinfo.Id);
            
          BLN_Event__c eventInfo= new  BLN_Event__c();
            eventInfo= globalTest.createEvent(countryInfo.Id, Stateinfo.Id ,CompanyInfo.id); 
            Order__c insertOrder1= new Order__c();
            insertOrder1= globalTest.createOrder(tktprof.Id, userForGN.id, companyInfo.Id, eventInfo.Id, currenyInfo.Id);
            
            Item_Type__c itemType= new Item_Type__c();
            itemType= globalTest.createItemType();
            
            BLN_Track__c trackInfo= new BLN_Track__c();
            trackInfo= globalTest.createTrack(eventInfo.Id);
            
            Item_Pool__c ItemPool= new Item_Pool__c();
            ItemPool= globalTest.createItemPool(eventInfo.id, itemType.Id, NULL, trackInfo.Id);
            
            Item_Pool__c ItemPool2= new Item_Pool__c();
            ItemPool2= globalTest.createItemPool(eventInfo.id, itemType.Id, ItemPool.Id, trackInfo.Id);
            
            BLN_Item__c item= new BLN_Item__c();
            item= globalTest.createItem(ItemPool.Id, itemType.Id, eventInfo.id);
            
                                Ticket__c ticket= new Ticket__c();
            ticket= globalTest.createTicket(eventInfo.id, item.Id, itemPool.Id, itemType.Id, insertOrder1.Id, tktprof.Id);
            //ticket.Client_Company__c= companyInfo.id;
            update ticket;
            
            Lead_Scan__c ls=new Lead_Scan__c();
            ls.First_Name__c='testa';
            ls.Last_Name__c='testb';
            ls.Event__c=eventInfo.id;
            //ls.Scanee_User__c=gnUser.id;
            ls.Scanner_Company__c=companyInfo.id;
            ls.Scanner_User__c=gnUserInfo.id;
            ls.scan_time__c=system.today();
            ls.Lead_Status__c='Active';
            insert ls;
            
            ticket.Event__c=eventInfo.id;
            update ticket;
            
            badge__c badge=new badge__c();
            //badge=globalTest.createBadge(ticket.id);
            badge.ticket_id__c=ticket.id;
            insert badge;
            
            badge.tickets__r.add(ticket);
            update badge;
            
            System.RestContext.request = new RestRequest();
            
            //RestRequest req = new RestRequest(); 
            String sfbaseURL = URL.getSalesforceBaseUrl().toExternalForm();
            RestContext.request.addParameter('barcodeid',badge.id);
            RestContext.request.addParameter('loginUserId',u.id);
            RestContext.request.addParameter('eventId',eventInfo.id);
            RestContext.request.addParameter('luCompId',companyInfo.id);
            //RestContext.request.addParameter('sTime',string.valueOf(ls.scan_time__c));
            RestContext.request.addParameter('sTime','11/12/2015  5:43 AM');
            
            RestContext.request.requestURI =  sfbaseURL+'/services/apexrest/BLN_Ls_Addlead';  
            RestContext.request.httpMethod = 'POST';
            
            BLN_Ls_Addlead blnascitem = new BLN_Ls_Addlead();
        // try {   BLN_Ls_Addlead.doPost(); } catch (exception e) {}
         BLN_Ls_Addlead.doPost();
            
            badge.Cancel_Reason__c='cancel_test';
            update badge;
            try {   BLN_Ls_Addlead.doPost(); } catch (exception e) {}
            
            badge.Exp_time__c=system.today()-2;
            badge.Cancel_Reason__c=null;
            update badge;
            try {   BLN_Ls_Addlead.doPost(); } catch (exception e) {}
            
            badge.ticket_id__c=null;
            update badge;
           try {   BLN_Ls_Addlead.doPost(); } catch (exception e) {}
           
            ticket.Event__c=null;
            update ticket;
        try {   BLN_Ls_Addlead.doPost(); } catch (exception e) {}
            
            
        }
    }
}