objects/Badge__c.object
<CustomObject>
    <fields>
        <fullName>Badge_Label__c</fullName>
        <label>Badge Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Print_status__c</fullName>
        <label>Print status</label>
        <picklist>
            <picklistValues>
                <fullName>Printed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Not Printed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Badge</label>
    <nameField>
        <displayFormat>BDG-{0000000}</displayFormat>
        <label>Badge Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Event__c.object
<CustomObject>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <picklist>
            <picklistValues>
                <fullName>America/New_York</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Kolkata</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Badge_Label__c</fullName>
        <label>Badge Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Pool_Name__c</fullName>
        <label>Item Pool Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <fields>
        <fullName>Badge_Label__c</fullName>
        <label>Badge Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>BLN_TKT_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Orders</relationshipLabel>
        <relationshipName>BLN_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reg_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Column_Name__c</fullName>
        <label>Column Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Label_Name__c</fullName>
        <label>Label Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Display Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Reg Setting</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Reg Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Reg Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Badge_ID__c</fullName>
        <label>Badge ID</label>
        <referenceTo>Badge__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Badge_Label__c</fullName>
        <label>Badge Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Barcode__c</fullName>
        <label>Custom Barcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tag_No__c</fullName>
        <description>This field holds either the serial number or complete item location tag number
eg. for a seat it will say zone A, Row 3, Seat 47</description>
        <label>Seat No</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tstatus_Id__c</fullName>
        <label>Tstatus_Id</label>
        <referenceTo>Tstatus__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tkt_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Tickets</relationshipLabel>
        <relationshipName>BLN_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tkt_profile__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>TKT_Company__c</fullName>
        <label>TKT Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TKT_Job_Title__c</fullName>
        <label>TKT Job Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN TKT profile</label>
    <nameField>
        <displayFormat>TP-{0000000}</displayFormat>
        <label>tkt profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN TKT profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tstatus__c.object
<CustomObject>
    <description>This will hold the history of ticket status
This maintains the state of the ticket such as checked in, checked out and the times
we can have multiple checkins and checkouts -</description>
    <fields>
        <fullName>Ticket__c</fullName>
        <label>Ticket</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipName>Tstatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tstatus_name__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tstatus_name</label>
        <type>Checkbox</type>
    </fields>
    <label>BLN Tstatus</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Tstatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tstatus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_ExportAttendeesBatch.cls
global without sharing class BLN_ExportAttendeesBatch implements Database.batchable<sObject>
{
   global final String Query;
    global final List<Reg_Setting__c> RegListBatch;
    global final Map<Id,String> tagsmapBatch;
    global final Map<Id,String> tickettagsmapBatch;
    global final Set<Id> checkrcds;
    global Map<String,String> ColmnvsLabel;
   
   private static final Integer SCOPE_SIZE = 100;
    public BLN_ExportAttendeesBatch (String q,List<Reg_Setting__c> RegList1,Map<Id,String> tagsmap1, Map<Id,String> tickettagsmap1){
    system.debug('DBDBDBD::'+q);
    Query=q;
    RegListBatch=RegList1;
    tagsmapBatch=tagsmap1;
    tickettagsmapBatch=tickettagsmap1;
    ColmnvsLabel = new Map<String,String>();
    
    for( Reg_Setting__c rgset : RegListBatch ){
        
        ColmnvsLabel.put(rgset.Column_Name__c, rgset.Label_Name__c);
    }
    ColmnvsLabel.put('admissions', 'Attendee');
    
    
   }
   
    public BLN_ExportAttendeesBatch(String q,List<Reg_Setting__c> RegList1,Map<Id,String> tagsmap1, Map<Id,String> tickettagsmap1,set<id> idset){
        
    checkrcds = idset;
   
    q = q+' and id in : checkrcds';
    system.debug('DBDBDBD::'+q);
    Query=q;
    RegListBatch=RegList1;
    tagsmapBatch=tagsmap1;
    tickettagsmapBatch=tickettagsmap1;
    
        ColmnvsLabel = new Map<String,String>();
    
    for( Reg_Setting__c rgset : RegListBatch ){
        
        ColmnvsLabel.put(rgset.Column_Name__c, rgset.Label_Name__c);
    }
    ColmnvsLabel.put('admissions', 'Attendee');

   }
   
   
   global Iterable<sObject> start(Database.batchableContext batchableContext)
   { 
       return Database.getQueryLocator(query);
      

   }
   global void execute(Database.BatchableContext batchableContext, List<sObject> scope)  
   {
      system.debug('DBDBDBD::'+scope);
      String temp='Attendee Name,Email,Phone,Company,Designation,Ticket Type,Ticket Name,Badge Label,Seat No.,Badge Status,Checkin Status,Buyer Name,Tag,Order Date,Order Id,Ticket Id,Custom Barcode\n';
 
for(sObject tickets:scope)
      {
      Ticket__c tkt = (Ticket__c)tickets;
      String shwpackg='';
       System.debug('EEEEMMMMLLL::'+tkt.tkt_profile__r.email__c);
       temp+='"'+tkt.tkt_profile__r.first_name__c+' '+tkt.tkt_profile__r.last_name__c +'",';
        temp+='"'+tkt.tkt_profile__r.email__c+'",';
        temp+='"'+tkt.tkt_profile__r.Mobile__c+'",';
        temp+='"'+tkt.tkt_profile__r.TKT_Company__c+'",';
        temp+='"'+tkt.tkt_profile__r.TKT_Job_Title__c+'",';

        String ticketType='';
        if(tkt.Item_Pool__r.Item_Type__r.Name=='Admissions'){
                
            ticketType=ColmnvsLabel.get(tkt.Item_Pool__r.Item_Type__r.Name.toLowercase());
            }
        
        if(tkt.Item_Pool__r.Item_Type__r.Name=='Exhibitor'){

            ticketType=ColmnvsLabel.get(tkt.Item_Pool__r.Item_Type__r.Name);
            }
        
        if(tkt.Item_Pool__r.Item_Type__r.Name=='Sponsor'){

            ticketType=ColmnvsLabel.get(tkt.Item_Pool__r.Item_Type__r.Name);
        }
        
        if(tkt.Item_Pool__r.Item_Type__r.Name=='Speaker'){

            ticketType=ColmnvsLabel.get(tkt.Item_Pool__r.Item_Type__r.Name);
        }
        temp+='"'+ticketType+'",'; 
        
        temp+='"'+tkt.Item_Pool__r.Item_Pool_Name__c+'",';
        temp+='"'+tkt.Badge_Label__c+'",';
        temp+='"'+tkt.Tag_No__c+'",';
        temp+='"'+tkt.Badge_ID__r.Print_status__c+'",';
        
        if(tkt.Tstatus_Id__r.Tstatus_name__c==true){
            temp+='"'+'Checked In'+'",';
        }else if(tkt.Tstatus_Id__r.Tstatus_name__c==false){
            temp+='"'+'Checked Out'+'",';
        }
        temp+='"'+tkt.Order__r.BLN_TKT_profile__r.First_Name__c+' '+tkt.Order__r.BLN_TKT_profile__r.Last_Name__c+'",';
        //temp+='"'+' '+'",';
        
        String tagNameBatch='';
        

        
        if(tagsmapBatch.ContainsKey(tkt.item_pool__c)){
            
            tagNameBatch+=tagsmapBatch.get(tkt.item_pool__c);
            }
        
        tagNameBatch+=' ';
        
        
        if(tickettagsmapBatch.containsKey(tkt.id)){
            
            tagNameBatch+=tickettagsmapBatch.get(tkt.id);
            
            }
        
        temp+='"'+tagNameBatch+'",';
        if(tkt.Order__r.createdDate !=NULL && tkt.Event__r.Time_Zone__c !=NULL){
        temp+='"'+tkt.Order__r.createdDate.format('MMMM d,  yyyy h:mm a', tkt.Event__r.Time_Zone__c)+'",';
        }else{
        temp+='"'+' '+'",';
        }
        temp+='"'+tkt.Order__r.Name+'",';
        temp+='"'+tkt.name+'",'; 
        temp+='"'+tkt.Custom_Barcode__c+'",';  
        temp+='\n';
        
      }
      
      try{
     Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
attachment.setFileName('ExportAttendees.csv');
attachment.setBody(Blob.valueOf(temp));
attachment.setContentType('text/csv');          
         
                
               String emailMessage = 'Please find attached your exported data as an attachment';                      
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setFileAttachments(new Messaging.EmailFileAttachment[] { attachment } );
                
                OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where DisplayName = 'supporteventdex'];

                    if ( owea.size() > 0 ) {
                        mail.setOrgWideEmailAddressId(owea.get(0).Id);
                        //emailTOea.setOrgWideEmailAddressId(owea.get(0).Id);
                    }
                
                 String[] toAddresses = new String[] {UserInfo.getUserName()};
                 mail.setToAddresses(toAddresses);
                 mail.setReplyTo('support@eventdex.com');
                 mail.setSubject('Export Attendees');
                 //mail.setPlainTextBody(emailMessage);
                 mail.setHtmlBody(emailMessage);
                
                 
                 Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                 }catch(Exception e){}
   }
      
      
       global void finish(Database.BatchableContext batchableContext){
       
       }
 
}