objects/BLN_Event__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>item_type__c</fullName>
        <label>Item type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Room__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Room</label>
    <nameField>
        <label>BLN_Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Sponsorships__c.object
<CustomObject>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Logo_Size__c</fullName>
        <label>Logo Size</label>
        <picklist>
            <picklistValues>
                <fullName>Large</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Small</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sponsorship_Category__c</fullName>
        <label>Sponsorship Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ticket_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ticket ID</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipLabel>BLN Sponsorships</relationshipLabel>
        <relationshipName>BLN_Sponsorships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Sponsorship</label>
    <nameField>
        <label>BLN Sponsorships Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Sponsorships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Track__c.object
<CustomObject>
    <description>Various Tracks within event
This can be a morning session or evening session for an event
This can be Java Track or .Net track for seminars</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Tracks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Booth_Map__c.object
<CustomObject>
    <description>This table is used for both Booth and Kiosk</description>
    <fields>
        <fullName>BLN_Room__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BLN Room</label>
        <referenceTo>BLN_Room__c</referenceTo>
        <relationshipLabel>BLN Booth Maps</relationshipLabel>
        <relationshipName>BLN_Booth_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Booth_Size__c</fullName>
        <label>Booth Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ticket_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ticket id</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipName>booth_maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Booth Map</label>
    <nameField>
        <label>Booth Kiosk Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Booth Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Company__c.object
<CustomObject>
    <description>user companyWhen company information is null in input form. create a company with just user name and assign user role of company admin.</description>
    <label>BLN Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipName>Countries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>BLN Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Currency__c.object
<CustomObject>
    <label>BLN Currency</label>
    <nameField>
        <label>Currency Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Currency</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GN_User__c.object
<CustomObject>
    <description>The address fields belong to user home address
This should be the only link between gnuser and salesforce user. salesforce user table should not be accessible any where else in db except this table.</description>
    <label>BLN GN User</label>
    <nameField>
        <displayFormat>GNU-{000000}</displayFormat>
        <label>GN User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN GN Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>old Item</label>
    <nameField>
        <displayFormat>item-{0000}</displayFormat>
        <label>iteam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>State</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN State</label>
    <nameField>
        <label>State Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>tkt_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Tickets</relationshipLabel>
        <relationshipName>BLN_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tkt_profile__c.object
<CustomObject>
    <label>BLN TKT profile</label>
    <nameField>
        <displayFormat>TP-{0000000}</displayFormat>
        <label>tkt profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN TKT profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_BLN_BoothsCon.cls
@isTest
public without sharing class Test_BLN_BoothsCon{

public static testMethod void TestMethod_BLN_BoothsCon(){

     globalForTestClass globalTest= new globalForTestClass();
        Account acc= new Account(Name='Globalnestcom');
         insert acc;
    
        contact con = new contact(firstname='gne',lastname='usere',AccountId=acc.id);
        insert con;
        Profile p = [select id from profile where name='Attendee'];


         User U= new User(alias = 'gn', email='BLN_BoothsCon@noemail.com', firstname= 'fngn', Phone= '9652563232',ContactId= con.Id,
                                  emailencodingkey='UTF-8',profileid = p.Id,lastname='gnusere', languagelocalekey='en_US',
                                  localesidkey='en_US',country='United States Of America', CompanyName= 'GlobalNest llc',
                                  timezonesidkey='America/Los_Angeles', username='BLN_BoothsCon@noemail.com', Title= 'SFDC Developer');
        database.insert(U,false);
        system.runas(u){
        Currency__c currenyInfo= new Currency__c();
        currenyInfo= globalTest.createCurrency();             
          
        Country__c countryInfo= new Country__c();
        countryInfo= globalTest.createCountry(currenyInfo.Id);  
            
        State__c stateInfo= new State__c ();
        stateInfo= globalTest.createState(countryInfo.Id);
        Company__c     companyInfo= new Company__c();
        companyInfo= globalTest.createCompany(u.Companyname);
       // GN_User__c  gnUser= new GN_User__c();
           // gnUser= globalTest.createGNUser(userForGN,countryInfo.Id, Stateinfo.Id);
            
        BLN_Event__c eventInfo= new  BLN_Event__c();
            eventInfo= globalTest.createEvent(countryInfo.Id, Stateinfo.Id ,CompanyInfo.id);        

         Item_Type__c itemType2= new Item_Type__c();
            itemType2= globalTest.createItemType();
            BLN_Track__c trackInfo= new BLN_Track__c();
            trackInfo= globalTest.createTrack(eventInfo.id);
        

             Item_Pool__c  ItemPool= new Item_Pool__c();
            ItemPool= globalTest.createItemPool(eventInfo.id, itemType2.Id, NULL, trackInfo.id);
            
             BLN_Item__c   item= new BLN_Item__c();
            item= globalTest.createItem(ItemPool.Id, itemType2.Id, eventInfo.id);

            Ticket__c ticket =new Ticket__c(Event__c = eventInfo.id,Item__c = item.id ,Item_Pool__c = ItemPool.id,Item_Type__c = itemType2.id, Ticket_Status__c = 'Available');
                 insert ticket ;
             
            BLN_Room__c broom=new BLN_Room__c ();
            broom = globalTest.createRoom(eventInfo.id);     
            
         Booth_Map__c    BoothMap=new Booth_Map__c(Name = 'Public Booth',BLN_Room__c = broom.id ,Ticket_id__c = ticket.id,Booth_Size__c = '5'  );
            insert BoothMap;   
            
          Booth_Map__c    BoothMap1=new Booth_Map__c(Name = 'Public Booth',BLN_Room__c = broom.id ,Ticket_id__c = ticket.id,Booth_Size__c = '5'  );
            insert BoothMap1;   
            list<Booth_Map__c> blist = new list<Booth_Map__c>();
            blist.add(BoothMap);
            blist.add(BoothMap1);
                
Ticket__c tctn=[select Name from Ticket__c where id = : ticket.id];
BLN_Room__c  nroom=[select Name from BLN_Room__c  where id = : broom.id];
 Tkt_profile__c  tktprof = new Tkt_profile__c();
            tktprof=globalTest.createTktprofile(u);
            
BLN_Sponsorships__c spn1 = new BLN_Sponsorships__c(Sponsorship_Category__c='textbc',Ticket_ID__c=tctn.id,Logo_Size__c='Large');
 insert spn1;
 BLN_Sponsorships__c spn = new BLN_Sponsorships__c(Sponsorship_Category__c='textba',Ticket_ID__c=tctn.id,Logo_Size__c='Large');
 insert spn;
 BLN_Sponsorships__c spn2 = new BLN_Sponsorships__c(Sponsorship_Category__c='textb',Ticket_ID__c=tctn.id,Logo_Size__c='Large');
 insert spn2;
 
 list<BLN_Sponsorships__c> listsp= new list<BLN_Sponsorships__c>();
 listsp.add(spn1);
 listsp.add(spn);
 listsp.add(spn2);
 Document document = new Document();
document.AuthorId = UserInfo.getUserId();
document.FolderId = UserInfo.getUserId();
        Attachment attach=new Attachment();     
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=tktprof.id;
        insert attach;
        
        List<Attachment> attachments=[select id, name from Attachment where parent.id=:tktprof.id];
        System.assertEquals(1, attachments.size());
   

cookie  counter = new Cookie('counter',eventInfo.id,null,-1,false);
         ApexPages.currentPage().setCookies(new Cookie[]{counter});
BLN_BoothsCon blbooth=new BLN_BoothsCon();
blbooth.sponsorticlist=listsp;
ApexPages.currentPage().getParameters().put('nw_bsizetxtval','6');
ApexPages.currentPage().getParameters().put('row_tid4',BoothMap.id);
system.debug('@@tickename'+ApexPages.currentPage().getParameters().put('row_tid4',BoothMap.id));
blbooth.update_newboothsize();

ApexPages.currentPage().getParameters().put('newbooth','20');
ApexPages.currentPage().getParameters().put('ticketlist1',tctn.Name+','+tctn.Name);

blbooth.update_boothareas();

ApexPages.currentPage().getParameters().put('newroom',nroom.Name);
ApexPages.currentPage().getParameters().put('ticketlist',tctn.Name+','+tctn.Name);

blbooth.update_boothRooms();

ApexPages.currentPage().getParameters().put('new_bRoom',nroom.Name);
ApexPages.currentPage().getParameters().put('row_tid3',BoothMap.id);

blbooth.update_boothRoom() ;

ApexPages.currentPage().getParameters().put('new_bArea','25');
ApexPages.currentPage().getParameters().put('row_tid2',BoothMap.id);

blbooth.update_boothArea();

ApexPages.currentPage().getParameters().put('new_bNo','8');
ApexPages.currentPage().getParameters().put('row_tid1',BoothMap.id);

blbooth.update_boothNo();

ApexPages.currentPage().getParameters().put('new_bsize','9');
ApexPages.currentPage().getParameters().put('row_tid',BoothMap.id);

blbooth.update_boothsize();

blbooth.displayPermissions();
//blbooth.BoothMapListprint;
blbooth.printBooths();
apexpages.currentpage().getparameters().put('searchKey','testna');
apexpages.currentpage().getparameters().put('start','2');
apexpages.currentpage().getparameters().put('length','2');
blbooth.ExhibitorsprocessData();

apexpages.currentpage().getparameters().put('deletedIdsp','attach.id');
try{
blbooth.delattachment();
}catch(Exception e){}

apexpages.currentpage().getparameters().put('deletedId','sponsorEdit.Ticket_id__r.tkt_profile__r.id');
try{
blbooth.delattachmentsp();
}catch(Exception e){}

BLN_BoothsCon.dynamicboothsize(eventinfo.id);
BLN_BoothsCon.dynamicboothnumbers(eventinfo.id);
blbooth.closePopup();
//blbooth.AttName;
//blbooth.AttNamespon;
//blbooth.AttData;
//blbooth.iframelink;
//blbooth.iframelinkspon;
//blbooth.imageData;
BLN_BoothsCon.SubWrapper dtp= new BLN_BoothsCon.SubWrapper(BoothMap,BoothMap.id);
        blbooth.boothedit=NULL;
        blbooth.exbPic=NULL;
        blbooth.exbImageName='test';

        apexpages.currentpage().getparameters().put('editID','test');
        
        BLN_BoothsCon  blnbothcon = new BLN_BoothsCon();            
        blnbothcon.sponsorEdit= new  BLN_Sponsorships__c (); 
        string bodys = '{"poolid" : "","trowid":"1", "tprice" : 150,"tags" : [],"tqty" : 30,"tname" : "iPad air ticket","subpackagegroup" : [],"ispackage" : false,"tdesc" : "","tvisib" : true,"tpaytype" : "Paid","itemtype" : "a1Ac0000000cNTAEA2","grouptickets" : [{"edate" : "12/09/2014 07:30 pm","sdate" : "12/06/2014 07:30 pm","tprice" : 150,"minqty" : "1","maxqty" : 20,"tname" : "iPad air ticket","itemid" : "","poolid" : "a18c0000000WS0zAAG","qty" : 30}],"ticketcount" : "1"}';
        blnbothcon.spPic= bodys;
        blnbothcon.spImageName='test';
        blnbothcon.exbPic=bodys;
        blnbothcon.selectedBoothSize='test';
        blnbothcon.BoothInformation=new LIST<SelectOption>();
        blnbothcon.exbImageName='test';
        blnbothcon.exbPic=bodys;
         blnbothcon.boothedit=new booth_map__c();          
        try{
            blnbothcon.editMethod();
            
            }
            catch(Exception e){
                
                                          
            }
                try{
                    blnbothcon.editspMethod();
                    }
                    catch(Exception e){}
                  try{
                    blnbothcon.SavespPopup();
                    }
                    catch(Exception e){}  
                    
                blnbothcon.printSponsors();
                 
            try{
                    
                    blnbothcon.SavePopup();
                    blnbothcon.closePopup();
                    blnbothcon.closePopup();
                }
                catch(Exception e){}
                
        apexpages.currentpage().getparameters().put('new_sc','test');        
        apexpages.currentpage().getparameters().put('spid','test'); 
                  
        BLN_Sponsorships__c  bsc = new  BLN_Sponsorships__c (); 
        bsc.Sponsorship_Category__c  = 'RAJ Sponsor';
        bsc.Display_Order__c = 1;
        bsc.Logo_Size__c = 'snall';
        bsc.Ticket_ID__c = ticket.id;
        insert bsc;
        
      
        
        try{
        blnbothcon.save_sponscat();
        }catch(exception e){}
      apexpages.currentpage().getparameters().put('displayOrder','test');
      try{
        blnbothcon.updateDisplayOrder();
          }catch(exception e){}
          
          BLN_Sponsorships__c  bsc1 = new  BLN_Sponsorships__c (); 
        bsc1.Sponsorship_Category__c  = 'RAJ Sponsorvvv';
        bsc1.Display_Order__c = 1;
        bsc1.Logo_Size__c = 'Medium';
        bsc1.Ticket_ID__c = ticket.id;
        insert bsc1;
        BLN_BoothsCon dcon= new BLN_BoothsCon();
         Apexpages.currentPage().getParameters().put('new_sc','trggg');
       Apexpages.currentPage().getParameters().put('spid',bsc1.id);
        dcon.save_sponscat();


}
}
}