objects/BLN_Event__c.object
<CustomObject>
    <fields>
        <fullName>Event_Ticket_Options__c</fullName>
        <label>Event Ticket Options</label>
        <picklist>
            <picklistValues>
                <fullName>Collect info from All Attendees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collect info from Buyers only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Do not collect Attendee info</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket_Settings__c</fullName>
        <label>Ticket_Settings</label>
        <picklist>
            <picklistValues>
                <fullName>Collect info from Buyers only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Collect info from All Attendees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not collect Attendee info</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>addon_parent_id__c</fullName>
        <label>Addon parent id</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>item_name__c</fullName>
        <label>Item name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>item_type__c</fullName>
        <label>Item type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_name__c</fullName>
        <label>Item name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>old Item</label>
    <nameField>
        <displayFormat>item-{0000}</displayFormat>
        <label>iteam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Addon_Parent__c</fullName>
        <label>Addon Parent</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Package_Flag__c</fullName>
        <label>Package Flag</label>
        <picklist>
            <picklistValues>
                <fullName>I - Individual Item pool</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>P - Package item pool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A - Addon Item pool</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ticket_Settings__c</fullName>
        <label>Ticket_Settings</label>
        <picklist>
            <picklistValues>
                <fullName>Collect info from Buyers only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Collect info from All Attendees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not collect Attendee info</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>BLN Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reg_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Column_Name__c</fullName>
        <label>Column Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Order__c</fullName>
        <label>Group Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Included__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Label_Name__c</fullName>
        <label>Label Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Display Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Organizer__c</fullName>
        <label>Organizer</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Setting_Type__c</fullName>
        <label>Setting Type</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Quick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Tab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eventdexapp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RegistrationLink</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Table_Name__c</fullName>
        <label>Table Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>BLN Reg Setting</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Reg Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Reg Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_Attendee_SettingsCon.cls
/***********************************************************************************************
*   Controller Name : BLN_Registration_Settings
*   Date            : 08/11/2014
*   Author          : Phani Kumar Ch
*   Purpose         : This class is for add and edit ticket settings
*   Change History  : 08/11/2014(mm/dd/yyyy)
*       Date                 Programmer                     Reason
*   --------------      -------------------           -------------------------
*  08/11/2014          Phani Kumar ch                     To Create Page
**************************************************************************************************/

public with sharing class BLN_Attendee_SettingsCon {

    public String selectedOPtion { get; set; }
public String selectedTicket { get; set; } // This is input hidden value for holding selected ticket id
public BLN_UtillDisplayLinks myticket {get;set;} // This is the variable for Component
public BLN_Event__c event{get;set;} // Event Instance for event details
public MAP<string,List<Reg_Setting__c>> MapTicWithSettings{get;set;} // variable to hold item and its settings
public List<BLN_Item__c> itemList {get;set;} // Items Belongs to this event
public MAP<id,List<Reg_Setting__c>> recSetMap{get;set;}
public List<inncls> inn{get;set;}
public MAP<string,List<Reg_Setting__c>> grupWithReg{get;set;} // To holding groupNAme and its settings of default Event 
public List<innForGroups> inngp{get;set;}
public List<BLN_Item__c> defaultTickets{get;set;} // for displaying default settings of event
public string defTciketId{get;set;}
public List<inncls> innclsListPool{get;set;} // It holds all the settings of itempool
public MAP<id,List<Reg_Setting__c>> mapPoolWithRegset{get;set;} // To hold itempool and its settings
public MAP<id,item_pool__c> mapItempoolWithId {get;set;} // to hold item pool id with itempool
public MAP<id,BLN_Item__c> mapPoolParentIdwithItem{get;set;} // MApping parent Itempool id with item for update with new value in savepool method  
public MAP<string,Reg_Setting__c>  mapLabelWithRs{get;set;}
public string eveType {get;set;}
   
   
 // Contructor
 public BLN_Attendee_SettingsCon(){
  try{
    // apply values to componet to heighlight perticular tab
     string k ='' ;
     Cookie counterval = ApexPages.currentPage().getCookies().get('counter');
    if(counterval !=null){
        k= counterval.getValue();
     }
     
     myticket = new BLN_UtillDisplayLinks();
     myticket.isAttendeeSettingsPage='active'; // To height light Link
     //myticket.isAttendeesPageExpand ='expand'; // To expand parent link
     myticket.isEventsettingsExpand ='expand';
     
     myticket.tablabel='Attendee Settings';  // Tab label
     myticket.eventId = k;
     myticket.userPermissions(userInfo.getUserId(),k);  // Getting Permissions as per login user role
       
     event = new BLN_Event__c  ();
     BLN_PromoCode_BAL blneventdetailbal = New BLN_PromoCode_BAL();
     event= blneventdetailbal.eventdetails(k); // getting event details
     myticket.EventName=event.Name; // to display event Name in component
      // ------------------- End component values ------------------------------------------
      getItems(); //gettting all settinga and tickets at a time
      getItemPools();
      
      BLN_RegistrationSettings_BAL regsetBal1 = new BLN_RegistrationSettings_BAL();
      grupWithReg = new MAP<string,List<Reg_Setting__c>>();
      grupWithReg =regsetBal1.getDefaultglobalEventSett(); // Getting default event and its settings
    
      displayGroups();
   }catch(exception ty){}   
      
    }
  public MAP<id,List<Item_pool__c>> mapIdwithPools{get;set;}
  public List<inncls> innFordefaultTc{get;set;}
  
  
    public List<inncls> getItems(){
      BLN_RegistrationSettings_BAL regsetBal =new BLN_RegistrationSettings_BAL();
      BLN_Quick_Registration_BAL quickBal= new BLN_Quick_Registration_BAL();  
      itemList = new List<BLN_Item__c>(); 
      recSetMap =new MAP<id,List<Reg_Setting__c>>();
      mapPoolParentIdwithItem = new  MAP<id,BLN_Item__c>();
      innFordefaultTc = new List<inncls>();
      
      mapIdwithPools= new MAP<id,List<Item_pool__c>>();
      inn = new List<inncls>();
      try{ 
      defaultTickets = [select id,Ticket_Settings__c,item_name__c,(select id,Name from Items__r) from BLN_Item__c where Event__r.Name='Default Event(Boothleads)'   limit 1];
    List<Reg_Setting__c> regSetList12 = new List<Reg_Setting__c>();
     
       if(defaultTickets.size()>0){
           List<Reg_Setting__c> regSetList13 =new List<Reg_Setting__c>();
           regSetList13 = regsetBal.CurrentEventSettings(event.id);
           selectedOPtion = event.Event_Ticket_Options__c ;
           innFordefaultTc.add(new inncls(defaultTickets[0],regSetList13,new List<item_pool__c>() ));  
           
        }
     
   
       itemList  =  quickBal.getEventItems(event.Id); // Getting tickets of selected Event
        SET<id> ticketIds = new SEt<id>();
        SET<id> ticketIdsForpool = new SEt<id>();
       
          for(BLN_Item__c fortcId : itemList){
            ticketIds.add(fortcId.id); 
              if(fortcId.Item_type__r.Name=='Package'){
                ticketIdsForpool.add(fortcId.id); 
                mapPoolParentIdwithItem.put(fortcId.Item_Pool__c ,fortcId);
            }
          }
        recSetMap = tcSettings(ticketIds,event.id); // Getting tickets ,its settings and assign to map 
        recSetMap.put(defaultTickets[0].id,regSetList12 );
         mapIdwithPools =  regsetBal.ItemsPoolsAndSettings(ticketIdsForpool,event.id); 
      
      
       for(BLN_Item__c blnItem : itemList){
          List<Reg_Setting__c> regSetList = new List<Reg_Setting__c>();
          regSetList= recSetMap.get(blnItem.id);
          inn.add(new inncls(blnItem,regSetList,mapIdwithPools.get(blnItem.id))); // Passing vales to inner class
       }  
     system.debug('OOOOOOOOOOOOOOOOOo '+inn[0].strNAme);
    return inn;  
    }catch(exception er){return null;}  
  }
  
  //Method to get all item pools related to package
   public List<inncls> getItemPools(){
      List<id> listOfpools = new List<id>();
      List<Item_Pool__c> aggPools = new List<Item_Pool__c >();
      mapPoolWithRegset = new MAP<id,List<Reg_Setting__c>>();
      mapItempoolWithId = new MAP<id,item_pool__c>();
      innclsListPool = new List<inncls>();
      List<Reg_Setting__c> agg = new List<Reg_Setting__c>();
        
     try{
      for(Id idsOfitem :mapIdwithPools.keySet() ){
        if(mapIdwithPools.get(idsOfitem)!=null){
           aggPools.addAll(mapIdwithPools.get(idsOfitem));
        }
      }
    
      for(Item_Pool__c itp :aggPools){
        listOfpools.add(itp.id);
     }
   
       agg = [select id,Column_Name__c,Event__c,Included__c,Item__c,Organizer__c,Required__c,Setting_Type__c,Table_Name__c,Label_Name__c,Item_Pool__c,Group_Name__c,order__c,item_pool__r.Ticket_Settings__c  from Reg_Setting__c where (item_pool__c In :listOfpools) and event__c=:event.id and Setting_Type__c='Regular' order by Group_Order__c,order__c ASC];
          for(item_pool__c itp :aggPools){
           List<Reg_Setting__c> aggTemp = new List<Reg_Setting__c>();
           for(Reg_Setting__c se :agg ){
             if(se.item_pool__c  == itp.id){
               aggTemp.add(se); 
             }
           }
           innclsListPool.add(new inncls(itp,aggTemp)); 
           mapPoolWithRegset.put(itp.id,aggTemp); 
           mapItempoolWithId.put(itp.id,itp);
         }
         
         return innclsListPool;
       } catch(exception rt){
         return null;
       }
    }
  
   
  
  
    
 // this will return ticket and its settings 
 public MAP<Id,LIST<Reg_Setting__c>> tcSettings(SET<id> ticIds,string eventId){
   List<Reg_Setting__c> regs = new List<Reg_Setting__c>();
   regs = [select id,Column_Name__c,Event__c,Included__c,Item__c,Organizer__c,Required__c,Setting_Type__c,Table_Name__c,Label_Name__c,Item_Pool__c,Group_Name__c,order__c,item_pool__r.Ticket_Settings__c  from Reg_Setting__c where (item__c In :ticIds ) and event__c=:eventId and Setting_Type__c='Regular' order by Group_Order__c,order__c ASC];
   MAP<id,List<Reg_Setting__c>> mapFinalListSettings = new  MAP<id,List<Reg_Setting__c>>();
     for(id tick :ticIds){
       List<Reg_Setting__c> reginterNal = new List<Reg_Setting__c>();
        for(Reg_Setting__c reg :regs ){
          if(reg.Item__c == tick){
           reginterNal.add(reg); 
         }
        }
        mapFinalListSettings.put(tick,reginterNal);
      }
   return mapFinalListSettings;
 }
 
 
 // For inserting regs 
    public void AddAccordian(){
    string gpnameVal = Apexpages.currentPAge().getParameters().get('gn');
    List<Reg_Setting__c> regse = new List<Reg_Setting__c>();
    List<Reg_Setting__c> regse1 = new List<Reg_Setting__c>();
    regse1 = grupWithReg.get(gpnameVal);
    
     system.debug('AAAAAAAAAAAAA '+regse1.size() );
    inn[0].strName.add(gpnameVal );
    
    List<Reg_Setting__c> regs3 = new List<Reg_Setting__c>();
        for(Reg_Setting__c tdc :regse1 ){
          Reg_Setting__c tempreg = new Reg_Setting__c();
          tempreg = tdc.clone(false,false,false,false);
          tdc.Event__c  = event.id;
          tdc.id=null;
          tdc.Item__c =null;
          tdc.Item_pool__c =null;
          regs3.add(tdc);  
        }
      dataBAse.saveResult[] ref1 = dataBase.insert(regs3,false);   
      system.debug('WWWWWWWWWWWWWWWWWW '+ref1 );
      
     for(inncls inc : inn){
        for(Reg_Setting__c tdc :regse1 ){
              Reg_Setting__c tempreg = new Reg_Setting__c();
              tempreg = tdc.clone(false,false,false,false);   
              tempreg.id=null;
              system.debug('AAAAAAAAAAAAA '+tempreg );
              if(defTciketId!=inc.iteminn.id){
                tempreg.Item__c = inc.iteminn.id;
              }else{
                 tempreg.Item__c =null;
              }
              tempreg.event__c = event.id;
              regse.add(tempreg);
         }     
      }
      
      for(inncls incpool : innclsListPool  ){
         for(Reg_Setting__c tdc :regse1 ){
              Reg_Setting__c tempreg1 = new Reg_Setting__c();
              tempreg1 = tdc.clone(false,false,false,false);   
              tempreg1.id=null;
              tempreg1.Item_pool__c = incpool.itpool.id;
              tempreg1.event__c = event.id;
              regse.add(tempreg1);
         } 
      }
      
            
     dataBAse.saveResult[] ref = dataBase.insert(regse,false);
     displayGroups();
   // system.debug('Accordian insert Result     '+ref );
  }
   
   
 // For deleting regs  
   public void deleteAccordian(){
      string gpnameVal = Apexpages.currentPAge().getParameters().get('gn');
     
       List<Reg_Setting__c> regse = new List<Reg_Setting__c>();
          for(inncls inc : inn){
            for( InnclsForGroup inng : inc.gpinnList ){
             if(gpnameVal==inng.groupName){
                regse.addAll(inng.regList);
               }
             }
           } 
           
            for(inncls incpool : innclsListPool){
            for( InnclsForGroup inng : incpool.gpinnList ){
             if(gpnameVal==inng.groupName){
                regse.addAll(inng.regList);
               }
             }
           } 
           
           inn[0].strName.remove(gpnameVal); 
        // deleting default ticket settings
        for(inncls ing:innFordefaultTc ){
          for(InnclsForGroup tg :ing.gpinnList){
            if(gpnameVal==tg.groupName){
                regse.addAll(tg.regList);
               }
             }
         }
        
               
       dataBase.delete(regse,false);   
      displayGroups();
      }
 
   

  
  public void saveDefultTicketSet(){
    eveType =selectedOPtion;  
     
       List<Reg_Setting__c> regToUpdate = new List<Reg_Setting__c>();
        for(inncls ing:innFordefaultTc ){
          for(InnclsForGroup tg :ing.gpinnList){
            regToUpdate.addALL(tg.regList); 
          }
        }
        database.update(regToUpdate ,false);
         event.Event_Ticket_Options__c = eveType;
         database.update(event,false); 
      // inn.addAll(innFordefaultTc);
    
  }
  
  // string has error message while we are saving item or item pool settings
  public string errorwhilesaving{get;set;} 
  
  // Save values after editing
    public PageReference Save() {
    try{ 
     //eveType = ApexPages.CurrentPage().getParameters().get('eveType');
     mapLabelWithRs = new MAp<string,Reg_Setting__c>(); // Mapping label with object to avoid for in for
     // Adding values  to map
      for(Reg_Setting__c rs : recSetMap.get(selectedTicket)){
          mapLabelWithRs.put(rs.Label_Name__c,rs);
      }  
 
   
     List<BLN_Item__c> itemsToUpdate = new List<BLN_Item__c>();
    SET<id> setOfids = new SET<id>(); 
     system.debug('PPPPPPPPPPPPPPPPP '+inn);
    
    // Getting selected tickets  
     for(inncls innSingle : inn){
        if(innSingle.selecetdValueInn){
           setOfids.add(innSingle.iteminn.id);
           innSingle.iteminn.Ticket_Settings__c = eveType;
               if(innSingle.iteminn.item_type__r.Name=='Package'){
                   for(Item_pool__c itp : innSingle.itemPoolsInn){
                      if(itp.Package_Flag__c!='P - Package item pool'){
                       itp.Ticket_Settings__c = eveType;
                     }
                   }
                 dataBase.update(innSingle.itemPoolsInn);
               }
           itemsToUpdate.add(innSingle.iteminn);
          }
     } 
     
      updateTicketsreg(setOfids);
      // List Of tickets to Update
        dataBase.saveResult[] sd =  dataBase.update(itemsToUpdate,false);
        system.debug('XXXXXXXXXXXXXXXXXXXXXXXXX '+sd );
      // dataBAse.update(event,false);
      }catch(exception er){ 
         errorwhilesaving = er.getMessage();
        } 
     return null;
    }
    
        public void savePool(){
      try{
       string idval= ApexPages.CurrentPage().getParameters().get('gnp');
       string eveType = ApexPages.CurrentPage().getParameters().get('eveTypePool');
       LIST<Reg_Setting__c> rsettUp = new List<Reg_Setting__c>();
    
       //Update item pool with new setting type   
       Item_pool__c itp = new Item_pool__c ();
       itp = mapItempoolWithId.get(idval);
       itp.Ticket_Settings__c = eveType;
       dataBase.update(itp);
       
       // updating regsettings with new values
       rsettUp.addAll(mapPoolWithRegset.get(idval));       
       dataBase.Update(rsettUp,false); 
       
         BLN_item__c  ite = new BLN_item__c();
         ite = mapPoolParentIdwithItem.get(itp.Addon_Parent__c); 
         ite.Ticket_Settings__c ='Collect info from All Attendees';
        dataBase.update(ite);
       }catch(exception er) {
          errorwhilesaving = er.getMessage();
        } 
   }
    
    
    
    
    
  
  
  // Update tickets and registration Settings 
     public void updateTicketsreg(SET<id> setOfids){
      LIST<Reg_Setting__c> toUpdate = new List<Reg_Setting__c>();  
      for(id tcId : setOfids){ // Iterating selected Ticket
       for(Reg_Setting__c rsForUp : recSetMap.get(tcId) ){ // Getting selected ticket id settings for update
          Reg_Setting__c rsforAdd = new Reg_Setting__c();
          rsforAdd =  mapLabelWithRs.get(rsForUp.Label_Name__c); // getting object for settings
          if(defTciketId ==tcId ){
             rsForUp.item__c =null;
          }
          rsForUp.Included__c = rsforAdd.Included__c  ;
          rsForUp.Required__c= rsforAdd.Required__c ;
          toUpdate.add(rsForUp);
       }    
     }  
    
    dataBase.update(toUpdate,false);  
       
 }
  
  
  
  
  
  
  
  public class innForGroups{
    public boolean selectChe{get;set;}
    public string groupNa{get;set;}
    public innForGroups(boolean b,string Name ){
     this.selectChe = b;
     this.groupna = Name;
    }
   }
  
  
  
   
 // Inner class for checkbox and ticket  
  public class inncls{
    public boolean selecetdValueInn {get;set;}
    public BLN_Item__c iteminn{get;set;}
    public List<InnclsForGroup> gpinnList{get;set;}
    public SEt<string> strName {get;set;}
    public List<Item_pool__c> itemPoolsInn{get;set;}
    public item_pool__c itpool{get;set;}
    
    public inncls(BLN_Item__c it,List<Reg_Setting__c> rsList,List<Item_pool__c> pool){
       iteminn = new BLN_Item__c();
       gpinnList= new List<InnclsForGroup>();
        itemPoolsInn = new  List<Item_pool__c>();
        this.itemPoolsInn  = pool;
        iteminn = it;
         gpinnList = utillForpoolAndItem(rsList); 
       
     }   
     
     public inncls(Item_pool__c it,List<Reg_Setting__c> rsList1){
      gpinnList= new List<InnclsForGroup>();
       gpinnList=utillForpoolAndItem(rsList1);
       itpool = new item_pool__c();
       itpool =it;
     }
     
     
   //Constructing Groups   
     public  List<InnclsForGroup> utillForpoolAndItem(List<Reg_Setting__c> rsList ){
        strName = new SET<string>(); // For uniqGroupNAmes
         List<string> strListName = new List<string>(); // For uniqGroupNAmes and order
       
         for(Reg_Setting__c rd:rsList){
          if(!strName.contains(rd.Group_Name__c)){
             strName.add(rd.Group_Name__c);
             strListName.add(rd.Group_Name__c);
          }
      }  
        List<InnclsForGroup> gpinnList1 = new List<InnclsForGroup>();
    // Passing Values  to Inner class  
       for(string gName:strListName){
         List<Reg_Setting__c> ListForInn = new List<Reg_Setting__c>();
          for(Reg_Setting__c rd1:rsList){
           if(rd1.Group_Name__c == gName){
              ListForInn.add(rd1);
           } 
          }
         gpinnList1.add(new InnclsForGroup(gName,ListForInn));
       }
     
     return gpinnList1;
     }
   }
   
   
   
  // Add group Names
  public void displayGroups(){
  SET<string> strgpName = new Set<string>();
  List<string> defgp = new List<string>();
  inngp = new List<innForGroups>();
      
  // getting default event settings
    for(Reg_Setting__c resDef : [select id,Group_Name__c,order__c,event__r.Name from Reg_Setting__c  where event__r.Name='Default Event(Boothleads)' and Setting_Type__c='Regular' order by order__c]){
         if(!strgpName.contains(resDef.Group_Name__c)){
         // system.debug('JJJJJJJJJJJJJJJJJJJJJJJ '+resDef.Group_Name__c);
             defgp.add(resDef.Group_Name__c);
             strgpName.add(resDef.Group_Name__c);
         }
    }
    system.debug('JJJJJJJJJJJJJJJJJJJJJJJ '+inn);
    
     if(inn.size()>0){
      for(string gpn :defgp){
       if(inn[0].strName.contains(gpn)){
          if(gpn!= 'Diversity Type Information'){
           inngp.add(new innForGroups(true,gpn));
          }
        }else{
          if(gpn!='Diversity Type Information'){
            inngp.add(new innForGroups(false,gpn));
          }
        }
      } 
    }
   
 }
  
  
 public class InnclsForGroup{
   public string groupName{get;set;}
   public List<Reg_Setting__c> regList{get;set;}
   public InnclsForGroup(string gpName,List<Reg_Setting__c> regs){
     regList = New List<Reg_Setting__c>();
     this.regList = regs;
     this.groupName = gpName;
   }
   
 } 
 
}