objects/BLN_Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <picklist>
            <picklistValues>
                <fullName>Paid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>item_count__c</fullName>
        <label>Item count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>item_name__c</fullName>
        <label>Item name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>item_type__c</fullName>
        <label>Item type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>BLN Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_name__c</fullName>
        <label>Item name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>old Item</label>
    <nameField>
        <displayFormat>item-{0000}</displayFormat>
        <label>iteam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Events__c</fullName>
        <label>Events</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Paid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Not Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Total__c</fullName>
        <label>Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>BLN Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Order Item</label>
    <nameField>
        <displayFormat>OI-{00000000}</displayFormat>
        <label>Order_Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Mode__c</fullName>
        <label>Payment Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Pay Gateway</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Payment</label>
    <nameField>
        <displayFormat>PAY-{00000000}</displayFormat>
        <label>Payment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tstatus_Id__c</fullName>
        <label>Tstatus_Id</label>
        <referenceTo>Tstatus__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tkt_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Tickets</relationshipLabel>
        <relationshipName>BLN_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tkt_profile__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN TKT profile</label>
    <nameField>
        <displayFormat>TP-{0000000}</displayFormat>
        <label>tkt profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN TKT profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tstatus__c.object
<CustomObject>
    <description>This will hold the history of ticket status
This maintains the state of the ticket such as checked in, checked out and the times
we can have multiple checkins and checkouts -</description>
    <fields>
        <fullName>Ticket__c</fullName>
        <label>Ticket</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipName>Tstatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tstatus_name__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tstatus_name</label>
        <type>Checkbox</type>
    </fields>
    <label>BLN Tstatus</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Tstatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tstatus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_DashboardConBAL.cls
public with sharing class BLN_DashboardConBAL {
/***************************************************************
    *   Controller Name         : BLN_Dashboards
    *   Date                    : 30/10/2014 
    *   Author                  : Mythily Nagandla(mythilyn@globalnest.com)
    *   Purpose                 : This class is for Creating Dashboards.
******************************************************************/
public BLN_DashboardConBAL(){}
public AggregateResult[] paywithtics {get ; set ;}
public AggregateResult[] paymentwithticket(string selectedevent ){
  paywithtics = [SELECT count(id) c,SUM(Order__r.Order_Total__c) s,Item__r.item_name__c t FROM Order_Item__c WHERE  Item__r.Event__c =: selectedevent  AND (Order__r.Order_Status__c != 'Cancelled' AND Order__r.Order_Status__c != 'Abandoned' AND Order__r.Order_Status__c != 'Not Paid' ) GROUP BY Item__r.item_name__c,Item__c ];//WHERE  Item__r.Event__c =: selectedevent
 return paywithtics ; 
}


public LIST<soldticketsinn> soldinn {get ; set ;}  
    public decimal booked {get ; set ;}
    public decimal Available {get ; set ;}
    public decimal totalticsNo {get ; set ;}
    public decimal soldtics {get ; set ;}
    public decimal attendeesreig {get ; set ;}
    
    public LIST<soldticketsinn> TotalTics(string selectedevent){
        soldtics =0;
        attendeesreig =0;
        soldinn  = new LIST<soldticketsinn> ();
          
           LIST<Ticket__c> tics = [SELECT (select id,Ticket__c,Tstatus_name__c from Tstatus__r ORDER BY CreatedDate),id,Item__r.id,Ticket_Status__c,Item_Type__r.Name FROM Ticket__c WHERE  Item__r.Event__c =: selectedEvent  AND (Order__r.Order_Status__c != 'Cancelled' AND Order__r.Order_Status__c != 'Abandoned' AND Order__r.Order_Status__c != 'Not Paid' ) ];
         MAP<id,integer> countChkWithTic = new MAP<id,integer>();
           for(Ticket__c tcs : tics ){
           integer tChIncount = 0; integer  tChoutcount = 0;
               for(Tstatus__c ts :tcs.Tstatus__r){
                  if(ts.Tstatus_name__c){
                    tChIncount++; 
                  }else{
                    tChoutcount++;
                  }
              }
              countChkWithTic.put(tcs.id,(tChIncount-tChoutcount));     
           }
          
          
          LIST<BLN_Item__c> items = [SELECT (SELECT id,tkt_profile__r.First_Name__c from Item__r),id,Name,item_type__r.Name,item_name__c,price__c,item_count__c FROM BLN_Item__c WHERE Event__c =: selectedEvent ];
            MAP<string,decimal> itemsmapcount = new MAP<string,decimal> ();
           MAP<id,integer> itemWithQuan = new MAP<id,integer>(); 
            
            for(BLN_Item__c its : items){        
                itemsmapcount.put (its.id,its.item_count__c);
                integer chkCount = 0;
                for(Ticket__c tcp : its.Item__r){
                 if(null != countChkWithTic.get(tcp.id)){
                   chkCount+=countChkWithTic.get(tcp.id); 
            }
                }
                itemWithQuan.put(its.id,chkCount);
            }
            //system.debug('::::::::::::;;;ex:::::::::;'+expected);      
         
         
         booked =0;
         available = 0;
         for(BLN_Item__c item : items){
         booked =0;
         available = 0;
             for(Ticket__c tt : tics){
                 if(tt.Item__r.id == item.id && tt.Ticket_Status__c == 'Booked' ){
                    booked ++; 
         
                 }else if(tt.Item__r.id == item.id && tt.Ticket_Status__c != 'Booked' ){
                     //available ++;
                 }        
             }
                 
             available = available + (item.item_count__c - booked);
             string typename = item.item_name__c;
             soldinn.add(new soldticketsinn(booked,available,typename,itemWithQuan.get(item.id),item.price__c));
              soldtics= soldtics+booked;   
             }
             return soldinn;
     }
     //---------------------------------------------------------
     public  AggregateResult[] paymentsresult {get ; set ;}
     public  AggregateResult[]  paymenttype( string selectedEvent){
        paymentsresult = [SELECT Payment_Mode__c p,SUM(Order__r.Order_Total__c) s FROM Payment__c WHERE Order__r.Events__c =:selectedEvent  AND (Order__r.Order_Status__c != 'Cancelled' AND Order__r.Order_Status__c != 'Abandoned' AND Order__r.Order_Status__c != 'Not Paid' ) GROUP BY Payment_Mode__c];
     return paymentsresult;
     }
 
    
//INNER CLASS FOR TOTAL NO OF TICKETS Vs SOLD TICKETS REPORT 
    public class soldticketsinn {
        public String TIC {get;set;} 
        public decimal SOLD{get;set;} 
        public decimal Available{get;set;} 
        public Integer CheckinQuan {get;set;}
        public Decimal tcPrice{get;set;}
        public soldticketsinn(decimal SOLD ,decimal Available,String TIC,integer chQ,Decimal tcp)  { 
            this.SOLD =SOLD ;
            this.Available=Available;
            this.TIC  =TIC  ;
            this.CheckinQuan =chQ;
            this.tcPrice = tcp;
        }
    }
    
    
  public LIST<Checkin> TotalCheckIn(string selectedevent){
       
       List<Checkin> chklist=new List<Checkin>();
       LIST<BLN_Item__c> items = [SELECT id,Name,item_type__r.Name,item_name__c,price__c,item_count__c FROM BLN_Item__c WHERE Event__c =: selectedEvent ];
            
       LIST<Ticket__c> tics = [SELECT id,Tstatus_Id__r.Tstatus_name__c,Item__r.id,Ticket_Status__c,Item_Type__r.Name FROM Ticket__c WHERE  Item__r.Event__c =: selectedEvent  AND (Order__r.Order_Status__c != 'Cancelled' AND Order__r.Order_Status__c != 'Abandoned' AND Order__r.Order_Status__c != 'Not Paid' )];
         decimal checkincount=0;
         decimal TicketSold=0;
       for(BLN_Item__c item : items){
        checkincount=0;
        set<id> tid = new set<id>();
            for(Ticket__c tt : tics){
                 if(tt.Item__r.id == item.id && tt.Ticket_Status__c == 'Booked'&& tt.Tstatus_Id__r.Tstatus_name__c==true ){
                   checkincount++; 
                 }  
                  if(tt.Item__r.id == item.id && tt.Ticket_Status__c == 'Booked'&& tt.Ticket_Status__c!='Cancelled'){
                   //TicketSold++; 
                   tid.add(tt.id);
                 }
                 
             }
                 
             Checkin chk=new Checkin();
                chk.TotalTicketSold= tid.size();
                chk.TotalTicketCount=item.item_count__c ;
                chk.TotalCheckInCount=checkincount++;
                chk.ItemName=item.item_name__c;
                chk.ItemId=item.Id;
                 chklist.add(chk);   
             }
             return chklist;
     }  
    
public class Checkin
    {  public Decimal TotalTicketSold{get;set;}
       public Decimal TotalTicketCount{get;set;}
       public String ItemName{get;set;}
       public String ItemId{get;set;}
       public Decimal TotalCheckInCount{get;set;}
    }


}