objects/BLN_Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>BLN Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <label>Payment</label>
        <picklist>
            <picklistValues>
                <fullName>Paid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>item_count__c</fullName>
        <label>Item count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>item_name__c</fullName>
        <label>Item name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>item_type__c</fullName>
        <label>Item type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>sale_end__c</fullName>
        <label>Sale end</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sale_start__c</fullName>
        <label>Sale start</label>
        <type>DateTime</type>
    </fields>
    <label>BLN Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event_Price__c.object
<CustomObject>
    <description>Resource Types for the event	- Default event zero has all the default values
Admissions Ticket 	$0.75		- as soon as ticket is bought
Seats Ticket 		$1.00
Seminars 		$1.00
MatchLeads Buyers 	$50.00
MatchLeads Sellers 	$15.00
Booth 		$0.50
Items 		$0.25
Package		$0.00
LeadScan 	$50.00 / booth	 - as soon as ticket is bought
Scan Attendee $299.00 /badge	 - as soon as service is added
Kiosk 	  $499.00  /event	 - as soon as service is added
BoothMap       $499.00  /event	 - as soon as service is added</description>
    <fields>
        <fullName>BL_Fee_Amount__c</fullName>
        <label>BL Fee Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Event_Price</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Count__c</fullName>
        <label>Item Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_type__c</fullName>
        <label>Item type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Event_Price</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Event Price</label>
    <nameField>
        <displayFormat>EP-{000000}</displayFormat>
        <label>Event Price</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Event Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Hash_Tag__c.object
<CustomObject>
    <description>Any tagging on an event or order or ticket or item can go here.</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Event_Tags</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Event Tag</label>
    <nameField>
        <displayFormat>TAG-{0000}</displayFormat>
        <label>Tag ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Event Tags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_name__c</fullName>
        <label>Item name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>old Item</label>
    <nameField>
        <displayFormat>item-{0000}</displayFormat>
        <label>iteam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Badgable__c</fullName>
        <label>Badgable</label>
        <picklist>
            <picklistValues>
                <fullName>B - Badge</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N - No Badge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M - Mark on the badge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Count__c</fullName>
        <label>Item Count</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_Pool_Name__c</fullName>
        <label>Item Pool Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Package_Flag__c</fullName>
        <label>Package Flag</label>
        <picklist>
            <picklistValues>
                <fullName>I - Individual Item pool</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>P - Package item pool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A - Addon Item pool</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <fields>
        <fullName>Badgable__c</fullName>
        <description>Badge is available for this resource type?
N - No Badge   --
B - Badge      --
M - Mark on the badge    --</description>
        <label>Badgable</label>
        <picklist>
            <picklistValues>
                <fullName>B - Badge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N - No Badge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M - Mark on the badge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Option_Desc__c</fullName>
        <label>Event Option Desc</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Order Item</label>
    <nameField>
        <displayFormat>OI-{00000000}</displayFormat>
        <label>Order_Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BLN_ItemType_BAL.cls
public with sharing class BLN_ItemType_BAL {

/***********************************************************************************************
*   Controller Name : BLN_ItemType_BAL
*   Date            : 19/05/2014
*   Author          : Naga Mallikarjuna Rao B
*   Purpose         : This class is for Item Types Business Application Layer
*   Change History  : 19/05/2014 
*       Date                 Programmer                     Reason
*   --------------      -------------------           -------------------------
*   19/05/2014          Naga Mallikarjuna Rao B           To Create Page
**************************************************************************************************/
    
    
    public static LIST<SelectOption> itemTypeSelectOptions(LIST<Event_Price__c> itemTypes){
        
        LIST<SelectOption> ItemTypesOptions = new LIST<SelectOption>();
        
        for(Event_Price__c itt : itemTypes ){

            ItemTypesOptions.add(new SelectOption(itt.item_type__r.id, itt.item_type__r.Name));
        }
        
        return ItemTypesOptions;
        
    }
     
     //Used in Events page
     public static LIST<SelectOption> boothleadsFeesStructure(){
        
        LIST<SelectOption> ticketServiceFee  = new LIST<SelectOption>();
        
        ticketServiceFee.add(new SelectOption('AddFee' , 'Add Eventdex fee on top of the total ticket price' )); 
        ticketServiceFee.add(new SelectOption('IncludeFee' , 'Include the Eventdex fee in to the total ticket price' )); 
        
        return ticketServiceFee;
        
     }
     
     
     //Used in Events page
     public static LIST<SelectOption> ticketOptions(){
        
        LIST<SelectOption> ticketServiceFee  = new LIST<SelectOption>();
        
        ticketServiceFee.add(new SelectOption('AddFee' , 'Add Eventdex fee on top of the total ticket price' )); 
        ticketServiceFee.add(new SelectOption('IncludeFee' , 'Include the Eventdex fee in to the total ticket price' )); 
        
        return ticketServiceFee;
        
     }
     
     
     
     // Create New Ticket In Events Page..........................................
    
     public static ticketsinnerClass addOnemoreTicket(Item_Pool__c  itemPoolForInnerClass,  BLN_Item__c blnItems, integer counteruniqueNo, Item_Type__c admissionItemType, LIST<Item_Pool__c> itemPools, LIST<BLN_Item__c> itemsList, LIST<Hash_Tag__c> itemHashTags /*, LIST<ItemPoolTags> itpTags*/){
          
      //  insertTickets.add(new ticketsinnerClass( itemPoolForInnerClass , blnItems, counteruniqueNo, admissionItemType, itemPools) );
        
         return (new ticketsinnerClass( itemPoolForInnerClass , blnItems, counteruniqueNo, admissionItemType, itemPools, itemsList, itemHashTags /*, itpTags*/));
        
    }
      
    
    
     public Decimal eventPriceToCharge{get;set;}
     public void eventOptiuonsTosave(LIST<Item_Type__c> itemTypes, BLN_Event__c event, GN_User__c gnUser, Company__c comp, Boolean saveOrder, Currency__c cur ){
        
        LIST<Item_Pool__c> eventadminItemPools = new LIST<Item_Pool__c>();
        LIST<BLN_Item__c> eventAdminItems = new LIST<BLN_Item__c>();
         
        eventPriceToCharge=0.0;
        system.debug('LLLLLLLLLLLLLLLLLL KKKKKKKKKKKKKKKKKKKKKKKKK '+event);
        BLN_EventOptions_DAO togetEventOptions = new BLN_EventOptions_DAO();
        MAP<id, Event_Price__c> eventOptionsPrice = new MAP<id, Event_Price__c>();
        //commented
         eventOptionsPrice = togetEventOptions.queryEventOptions(event.id);
         
         
        for(Item_Type__c itp: itemTypes){
            
            Item_Pool__c itemPools = new Item_Pool__c();
            
            if(eventOptionsPrice.containsKey(itp.id)){
                Event_Price__c eventPrice = new Event_Price__c();
                eventPrice = eventOptionsPrice.get(itp.id);
                
                if(eventPrice.Item_Count__c  != NULL)
                    itemPools.Item_Count__c  = eventPrice.Item_Count__c;
                else
                    itemPools.Item_Count__c =1;
            }else{
                itemPools.Item_Count__c = 1;
            }
            
            
            itemPools.Item_Pool_Name__c = itp.Event_Option_Desc__c;
            itemPools.Event__c = event.Id;
            itemPools.Item_Type__c = itp.id;
            itemPools.Package_Flag__c = 'I - Individual Item pool';
            itemPools.Badgable__c = 'N - No Badge';
             
              eventadminItemPools.add(itemPools);
        }
        //Here insert all ItemTypes Byselecting the values
        BLN_ItemPool_DAO itemPoolDAO = new BLN_ItemPool_DAO();
        itemPoolDAO.createItemPools(eventadminItemPools);
        
        
        system.debug('Item_Pool_Name__c Item_Pool_Name__c Item_Pool_Name__c Item_Pool_Name__c Item_Pool_Name__c '+eventadminItemPools );
        
        // get Event options price from Event_Price Object 
         
        
        for(Item_Pool__c ipool: eventadminItemPools){
            
            BLN_Item__c blnItem = new BLN_Item__c();
            
            Event_Price__c eventPrice = new Event_Price__c();
            if(eventOptionsPrice.containsKey(ipool.Item_Type__c)){
                
                eventPrice = eventOptionsPrice.get(ipool.Item_Type__c);
                if(eventPrice.BL_Fee_Amount__c != NULL)
                    eventPriceToCharge += eventPrice.BL_Fee_Amount__c;
            }
            

            blnItem.item_type__c = eventPrice.Item_type__c; 
            blnItem.Event__c = ipool.Event__c;
            blnItem.item_name__c = eventPrice.Item_type__r.Event_Option_Desc__c; 
            blnItem.item_count__c = ipool.Item_Count__c;
            blnItem.Payment__c = 'Paid';
            blnItem.price__c = eventPrice.BL_Fee_Amount__c;
            
            integer sthrs=0;
            integer stmin=0;
            //To find Sale Start DateTime................................................
           /* if(event.Start_Time__c != null){
                if(event.Start_Time__c.contains(':')){
                     LIST<String> splitTimes = new LIST<String>();
                     
                     splitTimes = event.Start_Time__c.split(':');
                     
                     if(splitTimes.size() == 2){
                        
                        //Assign Hrs....................
                        if(splitTimes[1].containsIgnoreCase('PM')){
                            sthrs = integer.valueOf(splitTimes[0]+12);
                        }else{
                            sthrs = integer.valueOf(splitTimes[0]);
                        }
                        //Assign Minuts....................
                        if(splitTimes[1].containsIgnoreCase(' ')){
                            if(splitTimes[1].split(' ')[0].isNumeric()     ){
                                stmin = integer.valueOf(splitTimes[1].split(' ')[0]);  
                            }
                        }
                     }
                     
                }
            }
            if(stmin != 0 && sthrs != 0){
                blnItem.sale_start__c =  DateTime.newInstance(event.Start_Date__c.year() , event.Start_Date__c.month(), event.Start_Date__c.day(), sthrs, stmin, 0);
            }
            
            sthrs=0;
            stmin=0;
            
            // To find Sale End dateTime.................................................................
            if(event.End_Time__c != null){
                if(event.End_Time__c.contains(':')){
                     LIST<String> splitTimes = new LIST<String>();
                     
                     splitTimes = event.End_Time__c.split(':');
                     
                     if(splitTimes.size() == 2){
                        
                        //Assign Hrs....................
                        if(splitTimes[1].containsIgnoreCase('PM')){
                            sthrs = integer.valueOf(splitTimes[0]+12);
                        }else{
                            sthrs = integer.valueOf(splitTimes[0]);
                        }
                        //Assign Minuts....................
                        if(splitTimes[1].containsIgnoreCase(' ')){
                            if(splitTimes[1].split(' ')[0].isNumeric()){
                                stmin = integer.valueOf(splitTimes[1].split(' ')[0]);  
                            }
                        }
                     }
                     
                }
            }
            
            if(stmin != 0 && sthrs != 0){
                blnItem.sale_end__c = DateTime.newInstance(event.Start_Date__c.year() , event.Start_Date__c.month(), event.Start_Date__c.day(), sthrs, stmin, 0);
            }*/
            
            //added instead of above commented code
            blnItem.sale_start__c = event.Start_Date__c;
            blnItem.sale_end__c = event.End_Date__c;
            //end of added instead of above commented code
            
            
            blnItem.Item_Pool__c = ipool.id;
            blnItem.Visibility__c = 'public';
            
            
            eventAdminItems.add(blnItem);
        }
        
        BLN_Item_DAO itemDAO = new BLN_Item_DAO();
        LIST<Database.Upsertresult> itemSuccessBool = itemDAO.upsertItems(eventAdminItems);
        
        system.debug('UUUUUUUUUUUUUUUUUUUUUUUU @@@@@@@@@@@@@@@@ '+itemSuccessBool);
        
        LIST<ID> successIds = new LIST<ID>();
        
        for(Database.Upsertresult item: itemSuccessBool){
            if(item.isSuccess())
                successIds.add(item.getId());
        }
        
        LIST<Ticket__c> itemtickets = new LIST<Ticket__c>();
        BLN_Ticket_DAO blnTicket = new BLN_Ticket_DAO();
        itemtickets = blnTicket.getSelectedTickets(successIds);
        
        
        
        system.debug('Item_Pool_Name__c Item_Pool_Name__c Item_Pool_Name__c Item_Pool_Name__c Item_Pool_Name__c 22222222222222      '+itemtickets.size() );
        
        
        LIST<Ticket__c> eventOptionTickets = new LIST<Ticket__c>();
        
        for(BLN_Item__c ite: eventAdminItems){
            Ticket__c t = new Ticket__c();
            
            t.Event__c = event.id;
            t.tkt_profile__r.bln_company__c=  comp.id;
            t.Item__c = ite.id;
            t.tkt_profile__r.bln_gn_user__c = gnUser.id;
            t.Ticket_Status__c = 'Available';
            t.Item_Pool__c = ite.Item_Pool__c;
            t.Item_Type__c = ite.item_type__c;
            
            
             eventOptionTickets.add(t);
        }
        
        BLN_Ticket_DAO toUpsertTickets = new BLN_Ticket_DAO();
     // toUpsertTickets.updteTickets(eventOptionTickets);
        
        //system.debug('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFinal Tickets   111111111111111111   '+ ite);
        
        
        if(saveOrder){
            Order__c o = new Order__c();
            
             o.Events__c = event.id;
             o.bln_tkt_profile__r.bln_company__c= comp.Id;
             o.bln_tkt_profile__r.bln_gn_user__c=  gnUser.id;
             o.Currency_Code__c = cur.id;
             o.Order_Status__c = 'Not Paid';
             o.Order_Total__c = eventPriceToCharge;
              
            DataBase.Saveresult orderSaveRes = DataBase.insert(o);
            
            LIST<Order_Item__c> orderLineItems = new LIST<Order_Item__c>();
            if(orderSaveRes.isSuccess()){
                for(BLN_Item__c ite: eventAdminItems){
                        system.debug('DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD   22222222222222222222222   '+ ite);
                    Order_Item__c l = new Order_Item__c();
                    l.Item__c = ite.id;
                    l.Order__c = orderSaveRes.getId();
                    l.Currency__c = cur.id;
                    l.Item_Quantity__c = ite.item_count__c;
                    l.Item_Price__c = ite.price__c;
                    l.Item_Total__c =  (ite.item_count__c * ite.price__c);
                    l.Status__c = 'Active';
                    
                    //orderLineItems.
                }
                
            }
            
            
            
        }
        
        
        
        
     }
     
     
     
     
      
    // wrapper Class for All Tickets and packages  
    public class ticketsinnerClass{
        
        public Item_Pool__c itemPool{get; set;}
        public BLN_Item__c items{get; set;}
        public integer count{get; set;}
        public LIST<BLN_Item__c> itemsList{get; set;}
        public LIST<Item_Pool__c> packageItemPools{get; set;}
        public Item_Type__c itemTypes{get; set;}
        public LIST<Hash_Tag__c> hashTagsForPool{get; set;}
        public LIST<String> hashTagsToshow{get; set;}
        public LIST<ItemPoolTags> itemPoolTags{get; set;}
        public Boolean displayInPage{get; set;}
        public Boolean displayWaterMark{get; set;}
        public decimal waterMarkAmount{get; set;}
        
        public ticketsinnerClass(){
            
             itemsList = new LIST<BLN_Item__c>();
             packageItemPools = new LIST<Item_Pool__c>();
             hashTagsForPool = new LIST<Hash_Tag__c>();
               hashTagsToshow = new LIST<String>();
               itemPoolTags = new LIST<ItemPoolTags>();
        }
        
        
        public ticketsinnerClass(Item_Pool__c itemPoolFromMain, BLN_Item__c BLNItems , integer counter, Item_Type__c itType, LIST<Item_Pool__c> pakItemPool, LIST<BLN_Item__c> ItemsForBird, LIST<Hash_Tag__c> itemHashTags /* , LIST<ItemPoolTags> itpTags*/){
               itemPool = new Item_Pool__c();
               items = new BLN_Item__c ();
               itemsList = new LIST<BLN_Item__c>();
               packageItemPools = new LIST<Item_Pool__c>();
               itemTypes = new Item_Type__c(); 
               hashTagsForPool = new LIST<Hash_Tag__c>();
               hashTagsToshow = new LIST<String>();
               itemPoolTags = new LIST<ItemPoolTags>();
               displayInPage = TRUE;
               displayWaterMark = FALSE;
               waterMarkAmount =0.00;
               
             system.debug('%%%%%%%%%%%%%%%%%%%%%%%      '+itemPool);  
               //admissionItemType
              if(ItemsForBird.size() > 0){
                itemsList.addAll(ItemsForBird);
              } else{
                 itemsList.add(BLNItems );
              } 
              
               itemPool = itemPoolFromMain;
               
               system.debug(' ITEM_Type_BAL    itemPool.Item_Type__c    itType.id  '+itType.id+'     '+ itemPool.Item_Type__c);  
               
               if(itemPool.Item_Type__c == null || itemPool.Item_Type__c != itType.id){
                 itemPool.Item_Type__c = itType.id;
               }  
               
               if(BLNItems.Payment__c == null){
                    BLNItems.Payment__c = 'Paid';
               }
                        
               items  = BLNItems ;
               count = counter;
               itemTypes = itType;
               packageItemPools = pakItemPool;
               hashTagsForPool = itemHashTags;
              // itemPoolTags = itpTags;
               
               for(Hash_Tag__c ht: itemHashTags){
                hashTagsToshow.add(ht.Tag_Text__c);
               }
                    
                 
              
               
         }    
    
    
    }
    
    
    
    
    public class ItemPoolTags{
        
        public LIST<String> itemPoolTags{get; set;}
        public Item_Pool__c itemPool{get; set;}
        
        public ItemPoolTags(Item_Pool__c ipool, LIST<String> ipht){
            itemPoolTags = new LIST<String>();
            itemPool = new Item_Pool__c();
            
            itemPoolTags.addAll(ipht);
            itemPool = ipool;
                        
        }
        
    }
    
    
    
    
}