objects/BLN_Event__c.object
<CustomObject>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <picklist>
            <picklistValues>
                <fullName>America/New_York</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Kolkata</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>image_url__c</fullName>
        <label>Image url</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>sale_end__c</fullName>
        <label>Sale end</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>sale_start__c</fullName>
        <label>Sale start</label>
        <type>DateTime</type>
    </fields>
    <label>BLN Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BLN_ASC_ItemsList.cls
@RestResource(urlMapping='/BLN_ASC_ItemsList/*')

global class BLN_ASC_ItemsList{
global static List<Itemscls_info> ct1 {get ; set ;}
global static BLN_Item_DAO itemsDao {get; set ;}
global static DateTime moddate{get; set ;}
    @HttpPost  
    global static List<Itemscls_info> doPost(){ 
      String siteurl=Label.SiteURL;
      string orgid = UserInfo.getOrganizationId();
        RestRequest req = RestContext.request;
        //system.debug('PPPPPP '+req.params.get('Event_id'));
        
        string eventid = req.params.get('Event_id');
        
        
        system.debug('@@eventid'+eventid );
        ct1 = new List<Itemscls_info>();
        itemsDao = new BLN_Item_DAO ();
        LIST<BLN_Item__c> itemsofEvent = itemsDao.getEventItemsForMobile(eventid);
        BLN_Event__c  ble=[select id,name,Time_Zone__c from BLN_Event__c where id=:eventid limit 1];
       system.debug('@@ble'+ble);
        BLN_ASC_GlobalItemLineit globalcls = new BLN_ASC_GlobalItemLineit();
        Map<Id,List<Item_Pool__c>> mapitemWithpools = new Map<Id,List<Item_Pool__c>>();
        mapitemWithpools = globalcls.sendItemsWithpools(itemsofEvent);
            for(BLN_Item__c BLT : itemsofEvent  ){
            string Sdate ='';
            string Edate ='';
               if(ble.Time_Zone__c != null){
               Sdate = BLT.sale_start__c.format('yyyy-MM-dd hh:mm a',ble.Time_Zone__c);
               Edate = BLT.sale_end__c.format('yyyy-MM-dd hh:mm a',ble.Time_Zone__c);
               
               }
               System.debug('BLT.lastmodifieddate '+BLT.lastmodifieddate);
                System.debug('BLT####'+BLT );
               System.debug('moddate '+moddate);
               system.debug('image_url'+BLT.image_url__c);
               if(moddate!=null){
               if(BLT.lastmodifieddate>=moddate)
               ct1.add(new Itemscls_info(BLT,Sdate,Edate,mapitemWithpools.get(BLT.Id),siteurl+'/servlet/servlet.ImageServer?oid='+orgid+'&id=')); }
               else
                ct1.add(new Itemscls_info(BLT,Sdate,Edate,mapitemWithpools.get(BLT.Id),siteurl+'/servlet/servlet.ImageServer?oid='+orgid+'&id='));       
        }
        


        return ct1;

    }
    
   global class Itemscls_info{
     public String siteurl{get;set;}
   public BLN_Item__c Items {get ; set ;}
   public List<Item_Pool__c> Itempool {get ; set ;}
   public string Startdate {get ; set ;}
   public string Enddate {get ; set ;}
   public Itemscls_info(BLN_Item__c Item1 ,string sdate,string edate, List<Item_Pool__c> Itempool1,String siteurls){
   Items =Item1;
   Startdate= sdate;
   Enddate = edate;
   Itempool = ItemPool1;
   siteurl=siteurls;
   
   }
     public Itemscls_info(){}
   }
    

}