objects/BLN_Address__c.object
<CustomObject>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>BLN Address</relationshipLabel>
        <relationshipName>BLN_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PoBox__c</fullName>
        <label>PoBox</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>BLN Address (State)</relationshipLabel>
        <relationshipName>BLN_Address1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>BLN Address</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>BLN Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Long_Name__c</fullName>
        <label>Long Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BLN Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>State</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Long_Name__c</fullName>
        <label>Long Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BLN State</label>
    <nameField>
        <label>State Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BLN_Address_DAO.cls
public with sharing class BLN_Address_DAO {
    public BLN_Address__c getAddress(String addId) {
      return [SELECT id,Address1__c,Address2__c,City__c,Country__c,Country__r.Long_Name__c,PoBox__c,State__c,ZipCode__c from BLN_Address__c where id=:addId];    
    }
    public string insertadd(string add1,string add2,string city,string country,string state,string pobox,string Zip){
    BLN_Address__c GNADD = new BLN_Address__c();
    GNADD.Address1__c = add1;
    GNADD.Address2__c = add1;
    GNADD.City__c = city;
    GNADD.Country__c = country;
    GNADD.State__c = state;
    GNADD.PoBox__c = pobox;
    GNADD.ZipCode__c = Zip;
    insert GNADD;
    system.debug('::::::::::::::::::::HID:::::::::::::;;'+GNADD.id);
    return GNADD.id;
    
    }
}