objects/BLN_Event__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>item_type__c</fullName>
        <label>Item type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Room__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Room</label>
    <nameField>
        <label>BLN_Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Track__c.object
<CustomObject>
    <description>Various Tracks within event
This can be a morning session or evening session for an event
This can be Java Track or .Net track for seminars</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Tracks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Company_Ext__c.object
<CustomObject>
    <description>This table stores all additional company attributes</description>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Company_Ext</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Company Ext</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Company Ext Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Company Ext</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipName>Countries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>BLN Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Device_Usage__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Device_Usage</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Device Usage</label>
    <nameField>
        <label>Device Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Device Usage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GN_User__c.object
<CustomObject>
    <description>The address fields belong to user home address
This should be the only link between gnuser and salesforce user. salesforce user table should not be accessible any where else in db except this table.</description>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN GN User</label>
    <nameField>
        <displayFormat>GNU-{000000}</displayFormat>
        <label>GN User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN GN Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Question__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item Question</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>Item_Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item_Question</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead_Scan__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Lead_Scans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>country__c</fullName>
        <label>country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>state</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>BLN Lead Scan</label>
    <nameField>
        <displayFormat>LS-{00000000}</displayFormat>
        <label>Lead Scan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Lead Scans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>BLN Question</label>
    <nameField>
        <displayFormat>QUE-{000000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reg_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Reg Setting</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Reg Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Reg Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>State</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN State</label>
    <nameField>
        <label>State Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_BLN_LeadRetrievalCon.cls
@istest
public class Test_BLN_LeadRetrievalCon{
    public static testmethod void Testmethod_BLN_LeadRetrievalCon(){
    
    globalForTestClass globalTest= new globalForTestClass();
    
     Profile p = [select id from profile where name='System Administrator'];
     userRole r=[SELECT ID FROM userRole WHERE name =: 'CEO'];   
     

     User u = new User(alias = 'Test', email='testcode123vb@noemail.com',
                       emailencodingkey='UTF-8',profileid = p.Id,lastname='codeTesting', Firstname='codeTesting', languagelocalekey='en_US',
                       localesidkey='en_US',country='United States Of America', userRoleId= r.id, CompanyName= 'GlobalNest',
                       timezonesidkey='America/Los_Angeles', username='testcode123vbc@noemail.com');
    insert u;
    
    
    
    
    system.runas(U){
            NAICS_Code__c naicsCodeInfo1= new NAICS_Code__c();
            naicsCodeInfo1= globalTest.createNaicsCode();
            
            NAICS_Code__c naicsCodeInfo2= new NAICS_Code__c();
            naicsCodeInfo2= globalTest.createNaicsCode();
            
            Currency__c currenyInfo= new Currency__c();
            currenyInfo= globalTest.createCurrency();
            
            Country__c countryInfo= new Country__c();
            countryInfo= globalTest.createCountry(currenyInfo.Id);  
            
            State__c stateInfo= new State__c ();
            stateInfo= globalTest.createState(countryInfo.Id);     
            
            Company__c companyInfo= new Company__c();
            companyInfo= globalTest.createCompany(u.Companyname);
            
            Company_Ext__c companyExtInfo= new Company_Ext__c();
            companyExtInfo= globalTest.createCompanyExt(companyInfo.Id, naicsCodeInfo1.Id, naicsCodeInfo2.Id, countryInfo.Id, stateInfo.Id); 
                    
            BLN_Event__c eventInfo= new  BLN_Event__c();
            eventInfo= globalTest.createEvent(countryInfo.Id, Stateinfo.Id ,CompanyInfo.id);  
            
            User userInfo= new User();
            userInfo= globalTest.createUserForGNUser();
                        
            GN_User__c  gnUserInfo= new GN_User__c();
            gnUserInfo= globalTest.createGNUser(userInfo, countryInfo.Id, stateInfo.Id);
            
            GN_User__c  gnUser= new GN_User__c();
            gnUser= globalTest.createGNUser(u,countryInfo.Id, stateInfo.Id);
            
            BLN_Room__c roomInfo= new BLN_Room__c();
            roomInfo= globalTest.createRoom(eventInfo.Id);
            
            BLN_Track__c trackInfo= new BLN_Track__c();
            trackInfo= globalTest.createTrack(eventInfo.Id);
            
            Item_Type__c itemType= new Item_Type__c();
            itemType= globalTest.createItemType();
            
            Item_Pool__c ItemPool= new Item_Pool__c();
            ItemPool= globalTest.createItemPool(eventInfo.id, itemType.Id, NULL, trackInfo.Id);
            
            Item_Pool__c ItemPool2= new Item_Pool__c();
            ItemPool2= globalTest.createItemPool(eventInfo.id, itemType.Id, ItemPool.Id, trackInfo.Id);
            
            BLN_Item__c item= new BLN_Item__c();
            item= globalTest.createItem(ItemPool.Id, itemType.Id, eventInfo.id);
            
            Tkt_profile__c  tktprof = new Tkt_profile__c();
        tktprof=globalTest.createTktprofile(userInfo);
            
            Order__c insertOrder1= new Order__c();
            //insertOrder1= globalTest.createOrder(gnUserInfo.Id, userInfo.id, companyInfo.Id, eventInfo.Id, currenyInfo.Id);
            insertOrder1= globalTest.createOrder(tktprof.Id, userInfo.id, companyInfo.Id, eventInfo.Id, currenyInfo.Id);
            //insertOrder1.BLN_tkt_profile__c= tktprof.id;
            //update insertOrder1;
            
        Question__c que = new Question__c();
        que=globalTest.createQuestion(eventInfo.id);
        
        Item_Question__c itemQue = new Item_Question__c();
        itemQue =globalTest.createItemQuestion(eventInfo.id,item.Id,que.Id);
        
       BLN_Answer__c ans = new BLN_Answer__c();
            ans=globalTest.createAnswer(que.Id);
             
        User_Answer__c  usrAns = new User_Answer__c();
        usrAns=globalTest.createUserAnswer(gnUser.id,itemQue.Id, ans.Id);
        
        
            Ticket__c ticket= new Ticket__c();
            ticket= globalTest.createTicket(eventInfo.id, item.Id, itemPool.Id, itemType.Id, insertOrder1.Id, tktprof.Id);
            //ticket.tkt_profile__c= tktprof.id;
           // update ticket;
        
            Lead_Scan__c ls=new Lead_Scan__c();
        ls.First_Name__c='testa';
        ls.Last_Name__c='testb';
            ls.Event__c=eventInfo.id;
            //ls.Scanee_User__c=gnUserInfo.id;
            ls.Scanner_Company__c=companyInfo.id;
            ls.Scanner_User__c=gnUser.id;
            ls.Lead_Status__c='Active';
            insert ls;
            
            Device_Usage__c du=new Device_Usage__c();
            du.Event__c=eventInfo.id;
            //du.User__c=gnUserInfo.id;
            insert du;
        
            que.OwnerId=gnUserInfo.User__c;
            update que;
            
            itemQue.Question_Level__c='Lead Retrieval';
            update itemQue;

            //usrAns.User__c=ls.Scanee_User__c;
            //update usrAns;
        
        Company_Ext__c CompanyExt= new Company_Ext__c();
        CompanyExt= globalTest.createCompanyExt(companyInfo.id, naicsCodeInfo1.id,naicsCodeInfo2.Id,countryInfo.Id,stateInfo.Id);
        
            Reg_Setting__c rsett = new Reg_Setting__c();
            rsett.Event__c = eventInfo.id;
            rsett.Included__c =true;
            insert rsett;
            
            PageReference pageRef1 = Page.BLN_LeadRetrieval;
            Test.setCurrentPage(pageRef1);
            
            cookie  counter = new Cookie('counter',eventInfo.id,null,-1,false);
            ApexPages.currentPage().setCookies(new Cookie[]{counter});
            
            BLN_LeadRetrievalCon lrcon = new BLN_LeadRetrievalCon();
            lrcon.displayPermissions();
            ApexPages.currentPage().getParameters().put('search','');
            lrcon.expLeadAction();
            ApexPages.currentPage().getParameters().put('search[value]','');
            ApexPages.currentPage().getParameters().put('start','0');
            ApexPages.currentPage().getParameters().put('length','10');
            lrcon.processData();
            //lrcon.selectedeventid=eventInfo.id;
            BLN_LeadScan_DAO lsDAO=new BLN_LeadScan_DAO ();
            string condition=' AND id=\'' + ls.id + '\'';
            lsDAO.getLeadScan(eventInfo.id,condition);
            apexpages.currentpage().getparameters().put('showId',ls.id);
            lrcon.showpopup();
            apexpages.currentpage().getparameters().put('editLead',ls.id);
            lrcon.editLead();
           // lrcon.countryStates();
           // lrcon.statesBasedOnCountry();
            
            
            lrcon.SavePopup();
            lrcon.closePopup();
            
            lrcon.printLeads();
            lrcon.exportLeads();
            lrcon.salesorgExport();

        lsDAO.getLeads(u.Id, eventInfo.id, companyInfo.id);
        lsDAO.Leadexistchk(eventInfo.id, gnuser.id, u.Id);
        lsDAO.getLeadScan_dashboard(eventInfo.id,'');
        lsDAO.getLeads(u.Id,eventInfo.id, companyInfo.id,'',null);
        set<id> lids = new set<id>();
        lids.add(ls.id);
        lsDAO.leadRecords(lids);
        
        BLN_LeadRetrieval_BAL lrBAL=new BLN_LeadRetrieval_BAL();
        lrBAL.insertLead(ticket, u.Id, eventInfo.id, companyInfo.id,null);
        //lrBAL.showleaddetails(ls.id,eventInfo.id);
        list<Lead_Scan__c> lslist=new list<Lead_Scan__c>();
        lslist.add(ls);
        lrBAL.maintableVals(eventInfo.id,lslist);
        list<Ticket__c> tct = new list<Ticket__c>();
        tct.add(ticket);
        LIST<datetime> st=new LIST<datetime>();
        st.add(system.now());
        lrBAL.insertLead(tct,u.id,eventInfo.id, companyInfo.id,st);
        BLN_LeadRetrieval_BAL.qaclass qa=new BLN_LeadRetrieval_BAL.qaclass('testque','testans');
        BLN_LeadRetrieval_BAL.editqaclass edtqa=new BLN_LeadRetrieval_BAL.editqaclass(que,usrAns);
        
        apexpages.currentpage().getparameters().put('deleteLead',ls.id);
        lrcon.deleteLead();
    
    }
    
    }   
}