objects/BLN_Event__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>item_type__c</fullName>
        <label>Item type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Track__c.object
<CustomObject>
    <description>Various Tracks within event
This can be a morning session or evening session for an event
This can be Java Track or .Net track for seminars</description>
    <label>BLN Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Company__c.object
<CustomObject>
    <description>user companyWhen company information is null in input form. create a company with just user name and assign user role of company admin.</description>
    <label>BLN Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipName>Countries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>BLN Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Currency__c.object
<CustomObject>
    <label>BLN Currency</label>
    <nameField>
        <label>Currency Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Currency</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GN_User__c.object
<CustomObject>
    <description>The address fields belong to user home address
This should be the only link between gnuser and salesforce user. salesforce user table should not be accessible any where else in db except this table.</description>
    <label>BLN GN User</label>
    <nameField>
        <displayFormat>GNU-{000000}</displayFormat>
        <label>GN User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN GN Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pay_Gateway__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Pay_Gateway</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PGateway_Type__c</fullName>
        <label>PGateway Type</label>
        <referenceTo>PGateway_Type__c</referenceTo>
        <relationshipName>Pay_Gateway</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Pay Gateway</label>
    <nameField>
        <displayFormat>PG-{00000000}</displayFormat>
        <label>Pay Gateway Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Pay Gateway</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PGateway_Type__c.object
<CustomObject>
    <label>BLN PGateway Type</label>
    <nameField>
        <label>PGateway_Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN PGateway Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>State</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN State</label>
    <nameField>
        <label>State Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_BLN_ReUse_EventsEditConExtended.cls
@isTest(SeeAllData=true)
public class Test_BLN_ReUse_EventsEditConExtended{
    public static testmethod void Testmethod_BLN_ReUse_EventsEditConExtended(){
    Account acc= new Account(Name='Globalnest');
         insert acc;
    
        contact con = new contact(firstname='gn',lastname='user',AccountId=acc.id);
        insert con;
        Profile p = [select id from profile where name='Event Admin1'];
        //userRole r=[SELECT ID FROM userRole WHERE name =: 'Custom Role'];   userRoleId= r.id,
        User U= new User(alias = 'gn', email='manasatest@gmail.com', firstname= 'fngn', Phone= '9878654345',ContactId= con.Id,
                                  emailencodingkey='UTF-8',profileid = p.Id,lastname='gnuser', languagelocalekey='en_US',
                                  localesidkey='en_US',country='United States Of America', CompanyName= 'GlobalNest',
                                  timezonesidkey='America/Los_Angeles', username='manasatest@gmail.com', Title= 'SFDC Developer');
        database.insert(U,false);
     
     globalForTestClass globalTest= new globalForTestClass();
     
     test.starttest();
       System.runas(u){
        
   Currency__c currenyInfo= new Currency__c();
        currenyInfo= globalTest.createCurrency();             
    Country__c countryInfo= new Country__c();
        countryInfo= globalTest.createCountry(currenyInfo.Id);  
            
        State__c stateInfo= new State__c ();
        stateInfo= globalTest.createState(countryInfo.Id);
    Company__c companyInfo= new Company__c();
    Item_Type__c itemType1= new Item_Type__c();
            itemType1= globalTest.createItemType();
            companyInfo= globalTest.createCompany('GlobalNest');
   
    BLN_Event__c eventInfo= new  BLN_Event__c();
    eventInfo= globalTest.createEvent(countryInfo.Id, Stateinfo.Id ,CompanyInfo.id);
    GN_User__c  gnUserInfo= new GN_User__c();
   gnUserInfo= globalTest.createGNUser(u,countryInfo.Id, Stateinfo.Id);
        BLN_Track__c trackInfo= new BLN_Track__c();
            trackInfo= globalTest.createTrack(eventInfo.id);
         
             Item_Pool__c ItemPool2= new Item_Pool__c();
            ItemPool2= globalTest.createItemPool(eventInfo.id, itemType1.Id, NULL, trackInfo.id);
            
            BLN_Item__c item= new BLN_Item__c();
            item= globalTest.createItem(ItemPool2.Id, itemType1.Id, eventInfo.id);
            Currency__c currencyInfo= new Currency__c();
            
            currencyInfo= globalTest.createCurrency();
            PGateway_Type__c pt=[select id,name from PGateway_Type__c limit 1];
            Pay_Gateway__c p1=new Pay_Gateway__c(Company__c=CompanyInfo.id,PGateway_Type__c=pt.id);
            
     BLN_ReUse_EventsEditCon.savesFinalEvent('Live',string.valueof(eventInfo.id),'2.00','4111111111111111','09','2017','123', '[{"ticketName":"ABC","ticketPrice":"2","ticketQty":"1","ticketId":"'+itemType1.id+'","itemId":"'+item.id+'"}]',string.valueof(currencyInfo.Id),'Pay Using Existing Credit Card','Credit Card','visa');
     BLN_ReUse_EventsEditCon.savesFinalEvent('Live',string.valueof(eventInfo.id),'2.00','4111111111111111','09','2017','123', '[{"ticketName":"ABC","ticketPrice":"2","ticketQty":"1","ticketId":"'+itemType1.id+'","itemId":"'+item.id+'"}]',string.valueof(currencyInfo.Id),'Pay Using New Credit Card','Credit Card','visa');
     BLN_ReUse_EventsEditCon.savesFinalEvent('Live',string.valueof(eventInfo.id),'2.00','4111111111111111','09','2017','123', '[{"ticketName":"ABC","ticketPrice":"2","ticketQty":"1","ticketId":"'+itemType1.id+'","itemId":"'+item.id+'"}]',string.valueof(currencyInfo.Id),'Check ','Check','visa');
     try{
      BLN_ReUse_EventsEditCon.new_savesPaymentOption('{"pgopt":"PayPal","firstparam":"'+p1.id+'","secondparam":"Check","thirdparam":"Direct","fourthparam":"test4p"}',eventInfo.id,'true','cash','external','cashcheckexternalcardcustomerid', 'cashcheckexternalcarddetails','tckopt','feeopt', '','F','acceptrangeforgt','mingt','check','micheck');
       }catch(Exception e){}      
        
         
            }       
    test.stoptest();
    
    }
    
    
    
    }