objects/BLN_Event__c.object
<CustomObject>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <picklist>
            <picklistValues>
                <fullName>America/New_York</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Kolkata</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>item_type__c</fullName>
        <label>Item type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Pool_Name__c</fullName>
        <label>Item Pool Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>BLN Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>tkt_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Tickets</relationshipLabel>
        <relationshipName>BLN_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tkt_profile__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TKT_Company__c</fullName>
        <label>TKT Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TKT_Job_Title__c</fullName>
        <label>TKT Job Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN TKT profile</label>
    <nameField>
        <displayFormat>TP-{0000000}</displayFormat>
        <label>tkt profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN TKT profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_ExportTickets.cls
global without sharing class BLN_ExportTickets implements Database.batchable < sObject > , Database.Stateful {
    global final String Query;


    private static final Integer SCOPE_SIZE = 100;
    public BLN_ExportTickets(String q) {
        Query = q;
    }
    global Iterable < sObject > start(Database.batchableContext batchableContext) {
        system.debug('query' + query);
        return Database.getQueryLocator(query);

    }
    global void execute(Database.BatchableContext batchableContext, List < sObject > scope) {
        String temp = 'Ticket No.,Ticket Name,Order Id,Ticket Type,First Name,Last Name,Email,Title,Company,Status,Sale Date\n';

        for (sObject tickets: scope) {
            Ticket__c ticket = (Ticket__c) tickets;

            temp += '"' + ticket.Name + '",';
            if (ticket.Item_Type__r.Name != 'Package') {
                temp += '"' + ticket.Item_Pool__r.Item_Pool_Name__c + '",';
            } else {
                string poolname = ticket.Item_Pool__r.Item_Pool_Name__c + ' (' + ticket.Item__r.Item_Pool__r.Item_Pool_Name__c + ')';
                temp += '"' + poolname + '",';
            }
            temp += '"' + ticket.Order__r.Name + '",';

            if (ticket.Item_Type__r.Name != 'Package') {
                temp += '"' + ticket.Item_Type__r.Name + '",';
            } else {
                temp += '"' + ticket.Item_Pool__r.Item_Type__r.Name + '",';
            }

            if (ticket.tkt_profile__r.First_Name__c != null && ticket.tkt_profile__r.First_Name__c != '') {
                temp += '"' + ticket.tkt_profile__r.First_Name__c + '",';
            } else {
                temp += '"",';

            }

            if (ticket.tkt_profile__r.Last_Name__c != null && ticket.tkt_profile__r.Last_Name__c != '') {
                temp += '"' + ticket.tkt_profile__r.Last_Name__c + '",';
            } else {
                temp += '"",';

            }

            if (ticket.tkt_profile__r.Email__c != null && ticket.tkt_profile__r.Email__c != '') {
                temp += '"' + ticket.tkt_profile__r.Email__c + '",';
            } else {
                temp += '"",';

            }



            if (ticket.tkt_profile__r.TKT_Job_Title__c != null && ticket.tkt_profile__r.TKT_Job_Title__c != '') {
                temp += '"' + ticket.tkt_profile__r.TKT_Job_Title__c + '",';
            } else {
                temp += '"",';

            }

            if (ticket.tkt_profile__r.TKT_Company__c != null && ticket.tkt_profile__r.TKT_Company__c != '') {
                temp += '"' + ticket.tkt_profile__r.TKT_Company__c + '",';
            } else {
                temp += '"",';

            }




            temp += '"' + ticket.Ticket_Status__c + '",';
            BLN_timeConToEvzoneCon tz = new BLN_timeConToEvzoneCon();
            tz.tZone = ticket.Event__r.Time_Zone__c;
            tz.format = 'MM/dd/yyyy hh:mm a';
            tz.dateTimeValue = ticket.Order__r.createddate;
            temp += '"' + tz.getTimeZoneValue();

            temp += '"';


            temp += '\n';

        }


        try {
            Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
            attachment.setFileName('ExportTickets.csv');
            attachment.setBody(Blob.valueOf(temp));
            attachment.setContentType('text/csv');


            String emailMessage = 'Please find attached your exported data as an attachment';
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setFileAttachments(new Messaging.EmailFileAttachment[] {
                attachment
            });

            OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where DisplayName = 'supporteventdex'];

            if (owea.size() > 0) {
                mail.setOrgWideEmailAddressId(owea.get(0).Id);
                //emailTOea.setOrgWideEmailAddressId(owea.get(0).Id);
            }

            String[] toAddresses = new String[] {
                UserInfo.getUserName()
            };
            mail.setToAddresses(toAddresses);
            mail.setReplyTo('support@eventdex.com');
            mail.setSubject('Ticket Detail Report');
            //mail.setPlainTextBody(emailMessage);
            mail.setHtmlBody(emailMessage);


            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {
                mail
            });
        } catch (Exception e) {}
    }


    global void finish(Database.BatchableContext batchableContext) {}

}