objects/BLN_Address__c.object
<CustomObject>
    <fields>
        <fullName>Address1__c</fullName>
        <label>Address1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address2__c</fullName>
        <label>Address2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>BLN Address</relationshipLabel>
        <relationshipName>BLN_Address</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PoBox__c</fullName>
        <label>PoBox</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>BLN Address (State)</relationshipLabel>
        <relationshipName>BLN_Address1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZipCode__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>BLN Address</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>BLN Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipName>Countries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Long_Name__c</fullName>
        <label>Long Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Display of the countries in list</description>
        <label>Display Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BLN Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Currency__c.object
<CustomObject>
    <fields>
        <fullName>Currency_Name__c</fullName>
        <label>Currency Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency_Symbol__c</fullName>
        <label>Currency Symbol</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BLN Currency</label>
    <nameField>
        <label>Currency Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Currency</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>BLN Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>State</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Long_Name__c</fullName>
        <label>Long Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>BLN State</label>
    <nameField>
        <label>State Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_BLN_Address_DAO.cls
@isTest
public class Test_BLN_Address_DAO {

    public static testMethod void testMethod_BLN_Address_DAO() {
        
        
        User U= new User();
        globalForTestClass globalTest= new globalForTestClass();
        U= globalTest.createUser();
        
        System.runAs(U){
        
         Currency__c insertCurrency= new Currency__c();
        insertCurrency.Name= 'USD';
        insertCurrency.Currency_Name__c= 'US Dollar';
        insertCurrency.Currency_Symbol__c= '$';
        
        insert insertCurrency;
        
         Country__c insertCountry= new Country__c();
        insertCountry.Long_Name__c = 'United States Of America';
        insertCountry.Short_Name__c= 'US';
        insertCountry.Currency__c= insertCurrency.id;
        insertCountry.Order__c= 123;
        insert insertCountry;
        
        State__c insertState= new State__c();
        insertState.Country__c= insertCountry.id;
        insertState.Long_Name__c= 'Andhra Pradesh';
        insertState.Order__c= 123;
        insertState.Short_Name__c= 'AP';
        
        insert insertState;
        
        
         BLN_Address__c bc = new BLN_Address__c();
         bc.Address1__c = 'sssss';
         bc.Address2__c = 'ddde';
         bc.City__c = 'ddddd';
         bc.Country__c = insertCountry.id;   
         bc.State__c = insertState.id;
         bc.PoBox__c = 'ddedd';
        
         bc.ZipCode__c = '33333';
         insert bc;
           
           BLN_Address_DAO  bd = new BLN_Address_DAO();
           bd.getAddress(bc.id); 
           bd.insertadd('hydff','viz','vij',insertCountry.id,insertState.id,'gpppp','1588');
        }
    }
    
}