objects/BLN_BadgeTemplate_Styles__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>BadgeTemplate_Styles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN BadgeTemplate_Styles</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN BadgeTemplate_Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Event__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>item_type__c</fullName>
        <label>Item type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BLN_Track__c.object
<CustomObject>
    <description>Various Tracks within event
This can be a morning session or evening session for an event
This can be Java Track or .Net track for seminars</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Tracks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Company_Ext__c.object
<CustomObject>
    <description>This table stores all additional company attributes</description>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Company_Ext</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Company Ext</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Company Ext Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Company Ext</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipName>Countries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Display of the countries in list</description>
        <label>Display Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>old Item</label>
    <nameField>
        <displayFormat>item-{0000}</displayFormat>
        <label>iteam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Order Item</label>
    <nameField>
        <displayFormat>OI-{00000000}</displayFormat>
        <label>Order_Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Reg_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Display Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Reg Setting</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Reg Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Reg Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>State</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN State</label>
    <nameField>
        <label>State Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_BLN_Reg_Settings_DAO.cls
@isTest
public class Test_BLN_Reg_Settings_DAO{

 static testmethod void Testmethod_BLN_Reg_Settings_DAO(){
 
  
    //User U= new User();
        globalForTestClass globalTest= new globalForTestClass();
     //   U= globalTest.createUser();        
        
            Profile p = [select id from profile where name='System Administrator'];
            userRole r=[SELECT ID FROM userRole WHERE name =: 'CEO'];   
         

            User u = new User(alias = 'Test', email='testcode1235689@noemail.com',
                           emailencodingkey='UTF-8',profileid = p.Id,lastname='codeTesting', Firstname='codeTesting', languagelocalekey='en_US',
                           localesidkey='en_US',country='United States Of America', userRoleId= r.id, CompanyName= 'GlobalNest',
                           timezonesidkey='America/Los_Angeles', username='testcode1235689@noemail.com');
            Database.insert(u);
        
        
        
            system.runas(U){
            
                    
            
            NAICS_Code__c naicsCodeInfo1= new NAICS_Code__c();
            naicsCodeInfo1= globalTest.createNaicsCode();
            
            NAICS_Code__c naicsCodeInfo2= new NAICS_Code__c();
            naicsCodeInfo2= globalTest.createNaicsCode();
            
            Currency__c currenyInfo= new Currency__c();
            currenyInfo= globalTest.createCurrency();      
            
            Country__c countryInfo= new Country__c();
            countryInfo= globalTest.createCountry(currenyInfo.Id);  
            
            State__c stateInfo= new State__c ();
            stateInfo= globalTest.createState(countryInfo.Id);     
            
            Company__c companyInfo= new Company__c();
            companyInfo= globalTest.createCompany(u.Companyname);
            
            Company_Ext__c companyExtInfo= new Company_Ext__c();
            companyExtInfo= globalTest.createCompanyExt(companyInfo.Id, naicsCodeInfo1.Id, naicsCodeInfo2.Id, countryInfo.Id, stateInfo.Id); 
                     
            BLN_Event__c eventInfo= new  BLN_Event__c();
            eventInfo= globalTest.createEvent(countryInfo.Id, Stateinfo.Id ,CompanyInfo.id);   
            
            BLN_BadgeTemplate_Styles__c badTStyleInfo=new BLN_BadgeTemplate_Styles__c();
            badTStyleInfo=globalTest.createBadgeTemplateStyle(eventInfo.id);
            
            
            
            
            
            User userForGN= new User();
            userForGN= globalTest.createUserForGNUser();
            
            GN_User__c  gnUser= new GN_User__c();
            gnUser= globalTest.createGNUser(userForGN, countryInfo.Id, stateInfo.Id);
            
            Order__c insertOrder1= new Order__c();
            insertOrder1= globalTest.createOrder(null, userForGN.id, companyInfo.Id, eventInfo.Id, currenyInfo.Id);
            
            Item_Type__c itemType= new Item_Type__c();
            itemType= globalTest.createItemType();
            
            BLN_Track__c trackInfo= new BLN_Track__c();
            trackInfo= globalTest.createTrack(eventInfo.id);
            
            Item_Pool__c ItemPool= new Item_Pool__c();
            ItemPool= globalTest.createItemPool(eventInfo.id, itemType.Id, NULL, trackInfo.Id);
            
            Item_Pool__c ItemPool2= new Item_Pool__c();
            ItemPool2= globalTest.createItemPool(eventInfo.id, itemType.Id, ItemPool.Id, trackInfo.Id);
           
            BLN_Item__c item= new BLN_Item__c();
            item= globalTest.createItem(ItemPool.Id, itemType.Id, eventInfo.id);
            
            Ticket__c ticket= new Ticket__c();
                
            ticket= globalTest.createTicket(eventInfo.id, item.Id, itemPool.Id, itemType.Id, insertOrder1.Id,null);
            Ticket__c insertTicket  = [select id,Name,Badge_Label__c,Tag_No__c,tkt_profile__r.BLN_GN_User__c,Item__c,Event__c
                                       from Ticket__c where id =:ticket.id];
                
            Ticket__c ticket1= new Ticket__c();
            ticket1= globalTest.createTicket(eventInfo.id, item.Id, itemPool.Id, itemType.Id, insertOrder1.Id,null);
                
            Order_Item__c orderItem= new Order_Item__c();
            orderItem= globalTest.createOrderItem(item.Id, insertOrder1.Id, null, currenyInfo.Id);
                       
            
            
            
            BLN_BadgeTemplate_Styles__c badTempStyl=new BLN_BadgeTemplate_Styles__c ();
            badTempStyl=globalTest.createBadgeTemplateStyle(eventInfo.id);
            
            Badge__c bdg= new Badge__c();
            bdg=globalTest.createBadge(insertTicket.id);
            
            Reg_Setting__c regSettingsInfo1= new Reg_Setting__c();
            regSettingsInfo1= globalTest.createRegSettings(eventInfo.Id, NULL, NULL, NULL, NULL,'Regular', 'AS_Last_Name__c');
            
            Reg_Setting__c regSettingsInfo4= new Reg_Setting__c();
            regSettingsInfo4= globalTest.createRegSettings(eventInfo.Id, NULL, NULL, NULL, NULL,'Regular', 'AS_Last_Name__c');
            
            
                
            Reg_Setting__c regSettingsInfo2= new Reg_Setting__c();
            regSettingsInfo2= globalTest.createRegSettings(eventInfo.Id, ItemPool2.Id, item.Id, companyInfo.Id, NULL, 'Regular', 'AS_Last_Name__c');
            
            list<Reg_Setting__c> regsettinginfo3 = new list<Reg_Setting__c>();
            regsettinginfo3.add(regSettingsInfo1);
            regsettinginfo3.add(regSettingsInfo2);
            
            
            set<id> setid = new set<id>();
             setid.add(item.id);   
                      
            list<id> listid = new list<id>();
            listid.add(item.id);
             
            list<id> lstid = new list<id>();
            
            lstid.add(ItemPool.id);          
           lstid.add(ItemPool2.id); 
            
            BLN_Reg_Settings_DAO regsettings = new BLN_Reg_Settings_DAO();
            
            regsettings.deleteRegset(regsettinginfo3);
            regsettings.insRegset(regsettinginfo3);
            regsettings.updateSet(regsettinginfo3);
            regsettings.getregsetlist(eventInfo.Id);
            
            //try{
            regsettings.itemSettings(lstid);
           // }
           // catch (exception eee) 
           // {}
            
            regsettings.getregsettingslist(eventInfo.Id);
            regsettings.attendeeSettingsSetUp(eventInfo.Id);
            regsettings.setsResitem('all',item.id);
            regsettings.setsResevent('all',item.id);
            regsettings.bookedRegSettingList(setid,eventInfo.Id); 
             regsettings.getMobileSettings(eventInfo.Id);
              regsettings.getMobileSettings(eventInfo.Id,null);
 
             regsettings.getMobileSettings(eventInfo.Id, system.now());
             regsettings.getItemtypeRegSetList(eventInfo.Id);
             regsettings.getrestrationlinksettings(eventInfo.Id);
             regsettings.getEventdexAppDefaultSettings();
 
  }
 }
}