objects/BLN_Session__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <picklist>
            <picklistValues>
                <fullName>Scan Attendee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eentdex</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BLN_Events__c</fullName>
        <label>BLN Events</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipLabel>BLN Sessions</relationshipLabel>
        <relationshipName>BLN_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Device_Id__c</fullName>
        <label>Device Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PusunotificationId__c</fullName>
        <label>PusunotificationId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BLN_Sessions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Session</label>
    <nameField>
        <displayFormat>SE-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_Session_DAO.cls
public with sharing class BLN_Session_DAO {
    public List<BLN_Session__c> getUsrActSessions(String uId,String appName,String dId){
       return [SELECT DeviceType__c,PusunotificationId__c,id,Application__c,Device_Id__c,Status__c,Token__c,User__c,LastmodifiedDate FROM BLN_Session__c WHERE Status__c='Active' AND User__c=:uId AND Application__c=:appName AND Device_Id__c=:dId ORDER BY lastmodifiedDate DESC ];
    }
    public List<BLN_Session__c> getUsrActSessions(String uId,String appName,String dId,String eId){
       return [SELECT DeviceType__c,PusunotificationId__c,id,Application__c,Device_Id__c,Status__c,Token__c,User__c,LastmodifiedDate FROM BLN_Session__c WHERE Status__c='Active' AND User__c=:uId AND Application__c=:appName AND Device_Id__c=:dId AND BLN_Events__c=:eId ORDER BY lastmodifiedDate DESC];
    }
   public List<BLN_Session__c> getUsrAct(String uId,String appName,String eId){
       return [SELECT DeviceType__c,PusunotificationId__c,id,Application__c,Device_Id__c,Status__c,Token__c,User__c,LastmodifiedDate FROM BLN_Session__c WHERE Status__c='Active' AND User__c=:uId AND Application__c=:appName AND BLN_Events__c=:eId ORDER BY lastmodifiedDate DESC];
    }

    public BLN_Session__c getSession(String sid){
    	try{
         return [SELECT DeviceType__c,PusunotificationId__c,id,Application__c,Device_Id__c,Status__c,Token__c,User__c,LastmodifiedDate FROM BLN_Session__c WHERE id=:sid];
    	}catch(exception ty){
    		return null;
    	}
    }
}