objects/BLN_Event__c.object
<CustomObject>
    <label>BLN Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Pool_Name__c</fullName>
        <label>Item Pool Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>BLN Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Registration_Type__c</fullName>
        <label>Registration Type</label>
        <picklist>
            <picklistValues>
                <fullName>Online</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Import</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Payment</label>
    <nameField>
        <displayFormat>PAY-{00000000}</displayFormat>
        <label>Payment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tstatus_Id__c</fullName>
        <label>Tstatus_Id</label>
        <referenceTo>Tstatus__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tkt_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Tickets</relationshipLabel>
        <relationshipName>BLN_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tkt_profile__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TKT_Company__c</fullName>
        <label>TKT Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN TKT profile</label>
    <nameField>
        <displayFormat>TP-{0000000}</displayFormat>
        <label>tkt profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN TKT profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tstatus__c.object
<CustomObject>
    <description>This will hold the history of ticket status
This maintains the state of the ticket such as checked in, checked out and the times
we can have multiple checkins and checkouts -</description>
    <fields>
        <fullName>Ticket__c</fullName>
        <label>Ticket</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipName>Tstatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>scan_time__c</fullName>
        <label>scan time</label>
        <type>DateTime</type>
    </fields>
    <label>BLN Tstatus</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>Tstatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tstatus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_ParticipantFirstVisitReportCon.cls
public class BLN_ParticipantFirstVisitReportCon {

/****************************************************************
Author    : Deepthi K
Date      : 10 Mar 2016
Purpose   : Report to display when pre-registered participants 
            visited for the first time
****************************************************************/

    public BLN_Event__c  se{get;set;}
    public String SelectedEvent{get; set;}
    public BLN_UtillDisplayLinks myticket { get; set; }
    public transient LIST<ticket__c> ticketsList{get;set;}
    
    public BLN_ParticipantFirstVisitReportCon(){
        Cookie k = ApexPages.currentPage().getCookies().get('counter');
        if(k!=null){ 
         selectedEvent = k.getValue();
        }
        
        LIST<ticket__c> ticList = new LIST<ticket__c>();
        ticList = [SELECT name,Order__c,item_pool__r.item_pool_name__c,tkt_profile__r.First_Name__c,tkt_Profile__r.Last_Name__c,tkt_profile__r.Email__c,tkt_profile__r.TKT_Company__c,(select scan_time__c from tstatus__r order by scan_time__c ASC limit 1) from ticket__c 
                        WHERE event__c = :selectedEvent 
                         AND tstatus_id__c != ''];
                         
        LIST<Payment__c> payments = new LIST<Payment__c>();
        BLN_Payment_DAO payDAO = new BLN_Payment_DAO();
        payments = payDAO.allpaymentsForEvent(selectedEvent);
        
        MAP<id,string> orderPayMap = new MAP<id,string>();
        for(Payment__c p:payments){
            orderPayMap.put(p.order__c,p.Registration_Type__c);
        }
        
        ticketsList = new LIST<ticket__c>();
        for(ticket__c t:ticList){
            if(orderPayMap.get(t.order__c)!= 'Onsite'){
                ticketsList.add(t);
            }
        }
        
    }
    
    
    public PageReference displayPermissions() {
        Cookie k = ApexPages.currentPage().getCookies().get('counter');
        if(k!=null){ 
         selectedEvent = k.getValue();
        }
        
        BLN_PromoCode_BAL blneventdetailbal = New BLN_PromoCode_BAL();
        se = new BLN_Event__c  ();
        try{
         se = blneventdetailbal.eventdetails(selectedEvent );
        }catch(exception e){}
        
        myticket = new BLN_UtillDisplayLinks();
        myticket.isSAExpand='expand';
        myticket.isSAreportExpand='expand';
        myticket.isFirstVisitReportPage='active';
        myticket.tablabel='First Visit Report';
        myticket.EventId = selectedEvent ;
        try{
          myticket.eventName=se.NAme;
        }catch(exception e){}
        myticket.userPermissions(userInfo.getUserId(),selectedEvent);
        return null;
    }
    
    public PageReference userSelectPerticularToExport() {
        pageReference pg = new PageReference ('/apex/BLN_ParticipantFirstVisitReportExport');
        pg.getParameters().put('seldates',apexpages.currentpage().getparameters().get('seldates'));
        pg.setRedirect(true);
        return pg;
    }

    public string seldates{get;set;}
    public PageReference expmethod() {
        seldates=apexpages.currentpage().getparameters().get('seldates');
        system.debug(apexpages.currentpage().getparameters().get('seldates')+'sssssssddddddd'+seldates);
    if(seldates!=null && seldates!=''){
        LIST<ticket__c> ticList = new LIST<ticket__c>();
        for(ticket__c t:ticketsList){
            if(seldates.contains(t.item_pool__r.item_pool_name__c)){
                ticList.add(t);
            }
        }
        ticketsList = new LIST<ticket__c>();
        ticketsList.addAll(ticList);
    }
    system.debug('1111111:');
        return null;
    }   
}