objects/BLN_Event__c.object
<CustomObject>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <picklist>
            <picklistValues>
                <fullName>America/New_York</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Kolkata</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Events</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Company_Diversity__c.object
<CustomObject>
    <description>Junction table between company and diversity tables. One company can have multiple diversity types such as MBE, SBE, 8a etc.</description>
    <fields>
        <fullName>BLN_TKT_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Company_Diversity</relationshipLabel>
        <relationshipName>BLN_Company_Diversity</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Company_Diversity</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>Company Diversity Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Company_Diversity</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Company_Naicscodes__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>BLN_TKT_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Company_Naicscodes</relationshipLabel>
        <relationshipName>BLN_Company_Naicscodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Company_Naicscodes</label>
    <nameField>
        <displayFormat>CN-{0000000}</displayFormat>
        <label>Custom Object Label Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Company_Naicscodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>old Item</label>
    <nameField>
        <displayFormat>item-{0000}</displayFormat>
        <label>iteam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Question__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Item_Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>Item_Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item Question</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>Item_Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item_Question</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>BLN_TKT_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Orders</relationshipLabel>
        <relationshipName>BLN_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reg_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Display Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Reg Setting</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Reg Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Reg Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_ID__c</fullName>
        <label>Parent ID</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tkt_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Tickets</relationshipLabel>
        <relationshipName>BLN_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tkt_profile__c.object
<CustomObject>
    <label>BLN TKT profile</label>
    <nameField>
        <displayFormat>TP-{0000000}</displayFormat>
        <label>tkt profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN TKT profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Item_Question__c</fullName>
        <label>Item Question</label>
        <referenceTo>Item_Question__c</referenceTo>
        <relationshipName>User_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket__c</fullName>
        <label>Ticket</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipName>User_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UAnswer_Text__c</fullName>
        <label>UAnswer Text</label>
        <length>34000</length>
        <type>LongTextArea</type>
    </fields>
    <label>BLN User Answer</label>
    <nameField>
        <displayFormat>UANS-{000000}</displayFormat>
        <label>User Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN User Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_AttendeeDetailReport_BAL.cls
/***********************************************************************************************
*   Controller Name : BLN_AttendeeDetailReport_BAL
*   Date            : 10/31/2014
*   Author          : Manasa Gandham
*   Purpose         : This class is to display the Attendee Details Report
*   Change History  : 10/31/2014
*       Date                 Programmer                     Reason
*   --------------      -------------------           -------------------------
*    10/31/2014              Manasa Gandham                 To Create Page
*  
**************************************************************************************************/

public class  BLN_AttendeeDetailReport_BAL{

    public BLN_AttendeeDetailReport_BAL(){ } 
    public BLN_Item_Question_DAO itemQuestionDAOClass{get;set;}
    public BLN_Ticket_DAO ticketsDAOClass{get; set;}
    public BLN_Company_DAO companyDiversityDAOClass{get; set;}
    public BLN_UserAnswers_DAO userAnswersDAOClass{get; set;}
    public BLN_Company_Naicscodes_DAO companyNaicCodeClass{get; set;}
    public BLN_Reg_Settings_DAO regSetDao{get;set;}
    public integer maxQuestion{get;set;}
    public integer maxQuestionItem{get;set;}
    public integer maxQuestionItemPool{get;set;}
    
    public SET<Id> tid{get;set;}
    public SET<Id> itemIds{get;set;}
    public SET<Id> itemPoolIds{get;set;}
    public SET<Id> tktprofileId{get;set;}
    public SET<Id> tktpId{get;set;}
        
    public LIST<AttendeeDetailInner> ticketsListForEvent(LIST<Ticket__c> ticksList1,String EventId, Date FromDate, Date ToDate, String SearchString){
        
        ticketsDAOClass= new BLN_Ticket_DAO();
        companyDiversityDAOClass= new BLN_Company_DAO();
        userAnswersDAOClass= new BLN_UserAnswers_DAO();
        companyNaicCodeClass=new BLN_Company_Naicscodes_DAO();
        itemQuestionDAOClass =new BLN_Item_Question_DAO ();
        
        LIST<Ticket__c> ticksList= new LIST<Ticket__c>();
        ticksList= ticksList1;//ticketsDAOClass.ticketsListForEvent(EventId, FromDate, ToDate);
        
        tid= new SET<Id>();
        itemIds= new SET<Id>();
        itemPoolIds= new SET<Id>();
        tktprofileId= new SET<Id>();
        tktpId=new SET<ID>();
           
        MAP<id, LIST<Company_Diversity__c>> diversityListMAP= new MAP<id, LIST<Company_Diversity__c>>();
        
        for(Ticket__c tic: ticksList){
            tid.add(tic.id); 
            itemIds.add(tic.item__c);
            //if(tic.parent_id__c!=null && tic.item_type__r.name=='Package'){            
                itemPoolIds.add(tic.item_pool__c);
            //}
            tktprofileId.add(tic.tkt_profile__c);
            tktpId.add(tic.tkt_profile__c);
        }
        SET<id> bothIds=new set<id>();
        bothIds.addAll(itemIds);
        bothIds.addAll(itemPoolIds);
        
        //process to get saved naics codes
        MAP<id, List<Company_Naicscodes__c>> CompanyNaicCodeMAP= new MAP<id, List<Company_Naicscodes__c>>();
        LIST<Company_Naicscodes__c> CompanyNaicCodeList= new LIST<Company_Naicscodes__c>();
        CompanyNaicCodeList= companyNaicCodeClass.companyNAICSWithTKTPro(tktprofileId);
        System.debug('NNNCNCNC:'+CompanyNaicCodeList);       
        for(Company_Naicscodes__c  compNC : CompanyNaicCodeList){
            LIST<Company_Naicscodes__c> naicsList= new LIST<Company_Naicscodes__c>();
            if(CompanyNaicCodeMAP.containsKey(compNC.BLN_TKT_profile__c)){
                naicsList= CompanyNaicCodeMAP.get(compNC.BLN_TKT_profile__c);
                naicsList.add(compNC);
                CompanyNaicCodeMAP.put(compNC.BLN_TKT_profile__c, naicsList);
            }else{
                naicsList.add(compNC);
                CompanyNaicCodeMAP.put(compNC.BLN_TKT_profile__c, naicsList);
            }
        } 
        
        //reg setting foreach indivdual ticket
        regSetDao=new BLN_Reg_Settings_DAO();
        MAP<String, List<Reg_Setting__c>> rgsetMap= new MAP<String, List<Reg_Setting__c>> ();  
        LIST<Reg_Setting__c> rgsetlist= new LIST<Reg_Setting__c>();
        try{
        rgsetlist= regSetDao.bookedRegSettingList(bothIds,EventId);
        }catch(exception e){}
        system.debug('ERGRGRR:'+rgsetlist);
        for(Reg_Setting__c rg : rgsetlist){
            LIST<Reg_Setting__c> rgtemplist1= new LIST<Reg_Setting__c>();
            if(rgsetMap.containsKey(rg.item__c)){
                rgtemplist1= rgsetMap.get(rg.item__c);
                rgtemplist1.add(rg);
                rgsetMap.put(rg.item__c, rgtemplist1);
            }else{
                rgtemplist1.add(rg);
                rgsetMap.put(rg.item__c, rgtemplist1);
            }
            
            LIST<Reg_Setting__c> rgtemplist2= new LIST<Reg_Setting__c>();
            if(rgsetMap.containsKey(rg.item_pool__c)){
                rgtemplist2= rgsetMap.get(rg.item_pool__c);
                rgtemplist2.add(rg);
                rgsetMap.put(rg.item_pool__c, rgtemplist2);
            }else{
                rgtemplist2.add(rg);
                rgsetMap.put(rg.item_pool__c, rgtemplist2);
            }
        } 
        
        //Getting Diversity
        LIST<Company_Diversity__c> companyDiversityList= new LIST<Company_Diversity__c>();        
        companyDiversityList= companyDiversityDAOClass.diversityOntktprofile(tktpId);
        
        for(Company_Diversity__c div  : companyDiversityList){
            LIST<Company_Diversity__c> DivList= new LIST<Company_Diversity__c>();
            if(diversityListMAP.containsKey(div.BLN_TKT_profile__c)){
                DivList= diversityListMAP.get(div.BLN_TKT_profile__c);
                DivList.add(div);
                diversityListMAP.put(div.BLN_TKT_profile__c, DivList);
            }else{
                DivList.add(div);
                diversityListMAP.put(div.BLN_TKT_profile__c, DivList);
            }
        }
        
        //Getting only survey questions for respective ticket with/without user answers
        //item level questions
        /*MAP<Id, LIST<item_question__c>> itemQuestionsMAP= new MAP<Id, LIST<item_question__c>>();
        LIST<item_question__c> itemQuestionsList= new LIST<item_question__c>();
        itemQuestionsList= itemQuestionDAOClass.itemQuestionsForTickets(itemIds, EventId);
        
        for(item_question__c iq : itemQuestionsList){
            LIST<item_question__c> itmQueList= new LIST<item_question__c>();
            if(itemQuestionsMAP.containsKey(iq.Item__c)){
                itmQueList= itemQuestionsMAP.get(iq.Item__c);
                itmQueList.add(iq);
                itemQuestionsMAP.put(iq.Item__c, itmQueList);
            }else{
                itmQueList.add(iq);
                itemQuestionsMAP.put(iq.Item__c, itmQueList);
            }
        }
        
        //itempool survey questions
        MAP<Id, LIST<item_question__c>> itemQuestionsMAPPool= new MAP<Id, LIST<item_question__c>>();
        LIST<item_question__c> itemQuestionsListPool= new LIST<item_question__c>();
        itemQuestionsListPool= itemQuestionDAOClass.itemQuestionsForTickets(itemPoolIds, EventId);
        
        for(item_question__c q : itemQuestionsListPool){
             LIST<item_question__c> itmQueListpool= new LIST<item_question__c>();
            if(itemQuestionsMAPPool.containsKey(q.Item_pool__c)){
                itmQueListpool= itemQuestionsMAPPool.get(q.Item_pool__c);
                itmQueListpool.add(q);
                itemQuestionsMAPPool.put(q.Item_pool__c, itmQueListpool);
            }else{
                itmQueListpool.add(q);
                itemQuestionsMAPPool.put(q.Item_pool__c, itmQueListpool);
            }       
        } 
        
        //item level user answers
        MAP<Id, LIST<User_Answer__c>> userAnswersMAP= new MAP<Id, LIST<User_Answer__c>>();
        LIST<User_Answer__c> userAnswersList= new LIST<User_Answer__c>();
        userAnswersList= userAnswersDAOClass.userAnswersForTickets(tid, itemIds, EventId);
        
        for(User_Answer__c ans : userAnswersList){
            LIST<User_Answer__c> userAnsList= new LIST<User_Answer__c>();
            if(userAnswersMAP.containsKey(ans.Item_Question__r.Item__c)){
                userAnsList= userAnswersMAP.get(ans.Item_Question__r.Item__c);
                userAnsList.add(ans);
                userAnswersMAP.put(ans.Item_Question__r.Item__c, userAnsList);
            }else{
                userAnsList.add(ans);
                userAnswersMAP.put(ans.Item_Question__r.Item__c, userAnsList);
            }
        }        
        
        //considering itempool user answers also
        MAP<Id, LIST<User_Answer__c>> userAnswersMAPPool= new MAP<Id, LIST<User_Answer__c>>();
        LIST<User_Answer__c> userAnswersListPool= new LIST<User_Answer__c>();
        userAnswersListPool= userAnswersDAOClass.userAnswersForTickets(tid, itemPoolIds, EventId);
        
        for(User_Answer__c ans: userAnswersListPool){
            //if(ans.UAnswer_Text__c!=Null){
                 LIST<User_Answer__c> userAnsListpool= new LIST<User_Answer__c>();
                if(userAnswersMAPPool.containsKey(ans.Item_Question__r.Item_pool__c)){
                    userAnsListpool= userAnswersMAPPool.get(ans.Item_Question__r.Item_pool__c);
                    userAnsListpool.add(ans);
                    userAnswersMAPPool.put(ans.Item_Question__r.Item_pool__c, userAnsListpool);
                }else{
                    userAnsListpool.add(ans);
                    userAnswersMAPPool.put(ans.Item_Question__r.Item_pool__c, userAnsListpool);
                }
            //}           
            } 
        
        maxQuestionItem=0;
        maxQuestionItemPool=0;*/
        LIST<LIST<AttendeeDetailInner>> AttendeeDetailInnerListOfList= new LIST<LIST<AttendeeDetailInner>>();        
        LIST<AttendeeDetailInner> AttendeeDetailInnerList999= new LIST<AttendeeDetailInner>();
        for(Ticket__c tic: ticksList){
            
           /* LIST<item_question__c> itmQueParentList= new LIST<item_question__c>(); 
            LIST<User_Answer__c> userAnsParentList= new LIST<User_Answer__c>();
            
            //item level survey questins
            LIST<item_question__c> itemQueList= new LIST<item_question__c>();
            LIST<item_question__c> iqList= new LIST<item_question__c>();  
            if(itemQuestionsMAP.get(tic.item__c) != NULL){ 
                itemQueList= itemQuestionsMAP.get(tic.item__c);         
                for(item_question__c q : itemQueList){
                    if(tic.item__c== q.item__c){
                        iqList.add(q);
                    }
                }
            }
            
            //item pool level survey questions
            LIST<item_question__c> itemPoolQueList= new LIST<item_question__c>();
            LIST<item_question__c> qListPool= new LIST<item_question__c>();  
            if(itemQuestionsMAPPool.get(tic.item_pool__c) != NULL && tic.parent_id__c!=null){ 
                itemPoolQueList= itemQuestionsMAPPool.get(tic.item_pool__c);         
                for(item_question__c q: itemPoolQueList){
                    if(tic.item_pool__c== q.item_pool__c){
                        qListPool.add(q);
                    }
                }
            }
            
             
            //item level user answers
            LIST<User_Answer__c> itemAnsList= new LIST<User_Answer__c>();
            LIST<User_Answer__c> userAnsList= new LIST<User_Answer__c>();  
            if(userAnswersMAP.get(tic.item__c) != NULL){ 
                itemAnsList= userAnswersMAP.get(tic.item__c);         
                for(User_Answer__c ans: itemAnsList){
                    if(tic.id== ans.ticket__r.id){
                        userAnsList.add(ans);
                    }
                }
            }
            
            //item pool level user answers
            LIST<User_Answer__c> itemPoolAnsList= new LIST<User_Answer__c>();
            LIST<User_Answer__c> userAnsListPool= new LIST<User_Answer__c>();  
            if(userAnswersMAPPool.get(tic.item_pool__c) != NULL && tic.parent_id__c!=null){ 
                itemPoolAnsList= userAnswersMAPPool.get(tic.item_pool__c);         
                for(User_Answer__c ans: itemPoolAnsList){
                    if(tic.id== ans.ticket__r.id){
                        userAnsListPool.add(ans);
                    }
                }
            }
            
            //item questions             
            if(iqList.size()>0)
                itmQueParentList.addAll(iqList);  
            
            if(qListPool.size()>0 )
                itmQueParentList.addAll(qListPool); 
            
            
            //user answers              
            if(userAnsList.size()>0)
                userAnsParentList.addAll(userAnsList);  
            
            if(userAnsListPool.size()>0 )
                userAnsParentList.addAll(userAnsListPool);
                
            //getting max no. of survey questions for each ticket
            if(maxQuestionItem < iqList.size()){
                maxQuestionItem =iqList.size();
            }else{
                maxQuestionItem=maxQuestionItem;
            }
            
            System.debug('xxxxxx'+maxQuestionItem);
            
            if(maxQuestionItemPool < qListPool.size()){
                maxQuestionItemPool=qListPool.size();
            }else{
                maxQuestionItemPool=maxQuestionItemPool;
            }
            System.debug('yyyyyy'+maxQuestionItemPool);*/
           
            AttendeeDetailInnerList999.add(new AttendeeDetailInner(tic, diversityListMAP.get(tic.TKT_Profile__c),new LIST<item_question__c>(),new LIST<User_Answer__c>(),CompanyNaicCodeMAP.get(tic.TKT_Profile__c), rgsetMap.get(tic.item__c),rgsetMap.get(tic.item_pool__c)));
            
        }
        
          /*  if(AttendeeDetailInnerList999.size() == 999){
                AttendeeDetailInnerListOfList.add(AttendeeDetailInnerList999);
                AttendeeDetailInnerList999= new LIST<AttendeeDetailInner>();
            }
        
        if(AttendeeDetailInnerList999.size() != NULL){
                AttendeeDetailInnerListOfList.add(AttendeeDetailInnerList999);
                AttendeeDetailInnerList999= new LIST<AttendeeDetailInner>();
            }
        
        return AttendeeDetailInnerListOfList;*/
        return AttendeeDetailInnerList999;
        }
        
        public Class AttendeeDetailInner{
            public LIST<item_question__c> itmQue{get;set;}
            public LIST<User_Answer__c> uans{get;set;}
            public Ticket__c ticketData{get; set;}
            public LIST<Company_Diversity__c> companyDiversityData{get; set;}
            public List<Company_Naicscodes__c> companyNaicsCode {get; set;}
            public LIST<Reg_Setting__c> regSetData{get; set;}
            public LIST<Reg_Setting__c> regSetDataPool{get; set;}
            public String createdon{get;set;}
            
            public AttendeeDetailInner(Ticket__c ticketData, LIST<Company_Diversity__c> companyDiversityData,LIST<item_question__c> itmQue, LIST<User_Answer__c> uans, List<Company_Naicscodes__c>  companyNaicsCode, LIST<Reg_Setting__c> regSetData,LIST<Reg_Setting__c> regSetDataPool){
                
                this.ticketData= ticketData;
                this.companyDiversityData= companyDiversityData;
                this.itmQue= itmQue;
                this.uans= uans;
                this.companyNaicsCode= companyNaicsCode;
                this.regSetData= regSetData;
                this.regSetDataPool= regSetDataPool;
                BLN_timeConToEvzoneCon tz=new BLN_timeConToEvzoneCon();
                tz.tZone=ticketData.Event__r.Time_Zone__c;
                tz.format='MM/dd/yyyy hh:mm a';
                tz.dateTimeValue=ticketData.Order__r.CreatedDate;
                this.createdon=tz.getTimeZoneValue();
            }
        }
}