objects/BLN_Item__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket_Settings__c</fullName>
        <label>Ticket_Settings</label>
        <picklist>
            <picklistValues>
                <fullName>Collect info from Buyers only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Collect info from All Attendees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not collect Attendee info</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>item_name__c</fullName>
        <label>Item name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>item_type__c</fullName>
        <label>Item type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item</label>
    <nameField>
        <displayFormat>Item-{000000}</displayFormat>
        <label>Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Badgable__c</fullName>
        <label>Badgable</label>
        <picklist>
            <picklistValues>
                <fullName>B - Badge</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>N - No Badge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M - Mark on the badge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Pool_Name__c</fullName>
        <label>Item Pool Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Package_Flag__c</fullName>
        <label>Package Flag</label>
        <picklist>
            <picklistValues>
                <fullName>I - Individual Item pool</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>P - Package item pool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A - Addon Item pool</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ticket_Settings__c</fullName>
        <label>Ticket_Settings</label>
        <picklist>
            <picklistValues>
                <fullName>Collect info from Buyers only</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Collect info from All Attendees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do not collect Attendee info</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <fields>
        <fullName>Badgable__c</fullName>
        <description>Badge is available for this resource type?
N - No Badge   --
B - Badge      --
M - Mark on the badge    --</description>
        <label>Badgable</label>
        <picklist>
            <picklistValues>
                <fullName>B - Badge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N - No Badge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M - Mark on the badge</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>BLN Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Order Item</label>
    <nameField>
        <displayFormat>OI-{00000000}</displayFormat>
        <label>Order_Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>BLN_Item__c</referenceTo>
        <relationshipName>Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_Item__c</fullName>
        <label>Order Item</label>
        <referenceTo>Order_Item__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_ID__c</fullName>
        <label>Parent ID</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BLN_ASC_Blocktickets.cls
/***********************************************************************************************
*   Controller Name : BLN_ASC_Blocktickets
*   Date            : 10/02/2015
*   Author          : Phani Kumar Ch
*   Purpose         : This class is Web service Class to hold tickets using tickets status changed.
                       (Means blocking tickets for some time)
**************************************************************************************************/

@RestResource(urlMapping='/BLN_ASC_Blocktickets')
global class BLN_ASC_Blocktickets {
   
 @HttpPost
 global static List<ItemWithTickets> doPost(){  
    RestRequest req = RestContext.Request;
    // Fetching json body form request 
    integer sessiontime = Integer.valueof(req.params.get('sessiontime'));
    String JsonString = req.requestBody.toString(); 
    System.debug('parser string www:'+JsonString);
    ItemsWithQuan itq = new ItemsWithQuan();
    List<ItemsWithQuan> itqList = new List<ItemsWithQuan>();
    MAP<string,integer> mapIdwithint = new MAP<string,integer>();
    BLN_Item_DAO itemDao = new BLN_Item_DAO();
    List<ItemWithTickets> itemTickets = new  List<ItemWithTickets>();
    List<id> TciketsIdsFrScduler;
    
    JSONParser parser = JSON.createParser(JsonString);
    System.debug('parser string:'+parser);
      while (parser.nextToken() != null){     
        if (parser.getCurrentToken() == JSONToken.START_OBJECT) {
           itq = (ItemsWithQuan)parser.readValueAs(ItemsWithQuan.class);// typecasting to object type
           mapIdwithint.put(itq.ItemId,integer.valueOf(itq.Qty));
           system.debug('itq ==='+ itq);
          }
       }
    BLN_Quick_Registration_BAL QuickRegBAL = new BLN_Quick_Registration_BAL();
     List<Ticket__c> listOfabandonedTics  = new List<Ticket__c>();
     boolean isAllticketsAvailble = true;
     //Fetching items for getting tickets
      
        BLN_Ticket_DAO TicketDAO = new BLN_Ticket_DAO();
       
         
     for(BLN_Item__c item :itemDao.ItemDetails(mapIdwithint.keySet())){
        /* Integer RecordCount = mapIdwithint.get(item.id);
         LIST<Ticket__c> TicketList = new LIST<Ticket__c>();
         LIST<Ticket__c> PackageTickets = new LIST<Ticket__c>();
        
         if(item.Item_Type__r.Name!='Package'){
            TicketList = TicketDAO.getTickets('id,Item__r.item_type__r.Name,name,Event__c,Item__r.item_name__c,Item_Pool__r.Item_Pool_Name__c,item__r.Ticket_Settings__c,Item_Pool__r.Ticket_Settings__c,Item_Type__r.name,Ticket_Status__c,Item_Pool__r.Package_Flag__c,Parent_ID__c,Item_Pool__r.Badgable__c','Event__c=\''+item.Event__c +'\' AND Item__r.item_name__c=\''+item.item_name__c+'\' AND Ticket_Status__c=\'Available\' AND Parent_ID__c=null ORDER BY Name LIMIT '+ RecordCount);     
         }else{
              TicketList = TicketDAO.getTickets('id,Item__r.item_type__r.Name,name,Event__c,Item__r.item_name__c,Item_Pool__r.Item_Pool_Name__c,item__r.Ticket_Settings__c,Item_Pool__r.Ticket_Settings__c,Item_Type__r.name,Ticket_Status__c,Item_Pool__r.Package_Flag__c,Parent_ID__c,Item_Pool__r.Badgable__c','Event__c=\''+item.Event__c +'\' AND Item__r.item_name__c=\''+item.item_name__c+'\' AND Ticket_Status__c=\'Available\' AND Parent_ID__c=null ORDER BY Name LIMIT '+ RecordCount);     
              for(Ticket__c tc : TicketList ){
                   PackageTickets.addAll(TicketDAO.getTickets('id,name,Event__c,Item__r.item_type__r.Name,Item_Pool__r.Item_Pool_Name__c,Item__r.item_name__c,Item_Pool__r.Ticket_Settings__c,Client_GN_User__c,Client_Company__c,Order__c,Order_Item__c,item__r.Ticket_Settings__c,Item_Type__r.name,Parent_ID__c,Item_Pool__r.Package_Flag__c,Item_Pool__r.Badgable__c,Ticket_Status__c','Ticket_Status__c=\'Available\' and  Parent_ID__c=\''+tc.id+'\'')); 
                }
             }
          listOfabandonedTics.addAll(TicketList);  
          listOfabandonedTics.addAll(PackageTickets);  
         }    */
         List<Ticket__c> tcList = new List<Ticket__c>();
          if(item.Item_Type__r.Name!='Package'){
            tcList = QuickRegBAL.getTicketDetail(item, mapIdwithint.get(item.id)); 
           }else{
              Item.Ticket_Settings__c = 'Collect info from All Attendees' ;
               tcList = QuickRegBAL.getTicketDetail(item, mapIdwithint.get(item.id));  
           } 
            
                
             if(tcList.size() >= mapIdwithint.get(item.id)){
                 itemTickets.add(new ItemWithTickets(item.id,tcList,tcList.size()));
                 listOfabandonedTics.addAll(tcList);
             }else{
                  itemTickets.add(new ItemWithTickets(item.id,new List<Ticket__c>(),tcList.size()));
                  isAllticketsAvailble = false;
              }
           }
         
           breakBlockticketsLoop.bvalue =false; // This is for not fire triggers on Item Object
         
           List<Ticket__c> listOfabandonedupd  = new List<Ticket__c>();
            TciketsIdsFrScduler = new List<id>();
             if(isAllticketsAvailble){
               for(Ticket__c tc :listOfabandonedTics){
                tc.Ticket_Status__c  ='Reserved';
                listOfabandonedupd.add(tc);
                 TciketsIdsFrScduler.add(tc.id);
               }
               BLN_generateScanId createScanId = new BLN_generateScanId();
               createScanId.insertScanId(listOfabandonedupd);
            }
   
    //Bln_Scheduler_ticketStatus scCls =new Bln_Scheduler_ticketStatus(sessiontime,TciketsIdsFrScduler);
     Bln_Scheduler_ticketStatus scCls = new Bln_Scheduler_ticketStatus();
    String SchedulerIdToAbart = scCls.Bln_Scheduler(SessionTime, TciketsIdsFrScduler);
   
     return itemTickets;
   }// Do post Method end 
    
   // Inner class to hold items and its quantities
     global class ItemsWithQuan{
        public string ItemId{get;set;}
        public string Qty{get;set;}     
          
     }
   
   // inner calss for responce 
   global class ItemWithTickets{
     public id  ItemId{get;set;}    
     public List<Ticket__c> ticketsList{get;set;}
     public integer tickesAvilable{get;set;}
     public  ItemWithTickets(string itid,List<Ticket__c> ticketsList1,integer tickesAvilable1){
        ticketsList = new List<Ticket__c>();
        tickesAvilable = 0;
        this.ItemId = itid;
        this.ticketsList = ticketsList1;
        this.tickesAvilable =tickesAvilable1;
        
     }    
  }
   
   
}