objects/BoothVisitSummary__c.object
<CustomObject>
    <fields>
        <fullName>BVS_Budget__c</fullName>
        <label>Budget</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BVS_City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BVS_Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BVS_Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>BVS_FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BVS_FollowUps__c</fullName>
        <label>FollowUps</label>
        <picklist>
            <picklistValues>
                <fullName>Send Sample</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active MailingList</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Have SalesPerson Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immediate Contact Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Demo Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send Literature</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>BVS_LastName__c</fullName>
        <label>LastName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BVS_LeadCategory__c</fullName>
        <label>LeadCategory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BVS_LeadRating__c</fullName>
        <defaultValue>0</defaultValue>
        <label>LeadRating</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BVS_LeadType__c</fullName>
        <label>LeadType</label>
        <picklist>
            <picklistValues>
                <fullName>ProductLead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ServiceLead</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BVS_Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BVS_PhoneNumber__c</fullName>
        <label>PhoneNumber</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>BVS_State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BVS_SurveyAnswer1__c</fullName>
        <label>SurveyAnswer1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BVS_SurveyAnswer2__c</fullName>
        <label>SurveyAnswer2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BVS_SurveyAnswer3__c</fullName>
        <label>SurveyAnswer3</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BVS_SurveyAnswer4__c</fullName>
        <label>SurveyAnswer4</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BVS_SurveyQuestion1__c</fullName>
        <defaultValue>&apos;Purchasing Authority ?&apos;</defaultValue>
        <label>SurveyQuestion1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BVS_SurveyQuestion2__c</fullName>
        <defaultValue>&apos;Best way of Contact ?&apos;</defaultValue>
        <label>SurveyQuestion2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BVS_SurveyQuestion3__c</fullName>
        <defaultValue>&apos;Product Interest ?&apos;</defaultValue>
        <label>SurveyQuestion3</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BVS_SurveyQuestion4__c</fullName>
        <label>SurveyQuestion4</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BVS_Tags__c</fullName>
        <label>Tags</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BVS_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EA_AttendeeBarcode__c</fullName>
        <label>AttendeeBarcode</label>
        <referenceTo>Event_Attendee_Mapping__c</referenceTo>
        <relationshipLabel>BoothVisitSummary</relationshipLabel>
        <relationshipName>BoothVisitSummary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mrecordid__c</fullName>
        <description>This is used for the mobile  application record</description>
        <externalId>true</externalId>
        <label>Mrecordid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScanTime__c</fullName>
        <label>ScanTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User_id__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BoothVisitSummary</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BoothVisitSummary</label>
    <nameField>
        <displayFormat>BVS_{0000000000}</displayFormat>
        <label>BVS_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BoothVisitSummary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Event_BVS__c.object
<CustomObject>
    <fields>
        <fullName>BVS_id__c</fullName>
        <label>BoothVisitSummary</label>
        <referenceTo>BoothVisitSummary__c</referenceTo>
        <relationshipLabel>User_Event_BVS</relationshipLabel>
        <relationshipName>User_Event_BVS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>User_Event_BVS</relationshipLabel>
        <relationshipName>User_Event_BVS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mrecordid__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Mrecordid</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>User_Event_BVS_Mapping</label>
    <nameField>
        <displayFormat>UEB_{00000000}</displayFormat>
        <label>UEB_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Event_BVS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Profile_Event__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_id__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User_Profile_Event</label>
    <nameField>
        <displayFormat>UPE_{00000000}</displayFormat>
        <label>UPE_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Profile_Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BoothLeads.cls
@Restresource(urlMapping='/BoothLeads/*')

global with sharing class BoothLeads{


global static list<BoothVisitSummary__c> BoothSummaryNew = new List<BoothVisitSummary__c>();
 
global static List<Boothlead> bleads = new List<Boothlead>();

global static User_Profile_Event__c UPE;

global static List<User_Event_BVS__c> UserBVS = new List<User_Event_BVS__c>(); 

@HttpPost


global static List<Boothlead> doPost(){
    
    
    RestRequest req = RestContext.request;
    RestResponse res = RestContext.response;
    
    System.debug('@@@@@req'+req);
    
    String userId = req.params.get('UserId');
   
    System.debug('@@@@@userId'+userId );
   
    String eventId = req.params.get('EventId');
    
    System.debug('@@@@@eventId '+eventId);
   
  
    
    UserBVS  = [Select BVS_id__r.BVS_FollowUps__c ,BVS_id__r.EA_AttendeeBarcode__c,BVS_id__r.BVS_Budget__c,BVS_id__r.BVS_City__c,BVS_id__r.BVS_Company__c,BVS_id__r.BVS_Email__c,BVS_id__r.BVS_FirstName__c,BVS_id__r.BVS_LastName__c,BVS_id__r.BVS_LeadCategory__c,BVS_id__r.BVS_LeadRating__c,BVS_id__r.BVS_LeadType__c,BVS_id__r.Mrecordid__c,
    
                BVS_id__r.BVS_Notes__c,BVS_id__r.BVS_PhoneNumber__c,BVS_id__r.ScanTime__c,BVS_id__r.BVS_State__c,BVS_id__r.BVS_SurveyAnswer1__c,BVS_id__r.BVS_SurveyAnswer2__c,BVS_id__r.BVS_SurveyAnswer3__c,BVS_id__r.BVS_SurveyAnswer4__c,BVS_id__r.BVS_SurveyQuestion1__c,BVS_id__r.BVS_SurveyQuestion2__c,BVS_id__r.BVS_SurveyQuestion3__c,
                
                BVS_id__r.BVS_SurveyQuestion4__c,BVS_id__r.BVS_Tags__c,BVS_id__r.BVS_Title__c  from User_Event_BVS__c where EV_id__c=:eventId  and BVS_id__r.User_id__r.id=:userId]; 
    
   
     System.debug('@@@@@@@UserBVS'+UserBVS);
   
   
   for(User_Event_BVS__c UEBC:UserBVS){
   
   
   Boothlead Blead = new Boothlead();
  
   //Blead.Barcode = UEBC.BVS_id__r.EA_AttendeeBarcode__c;
   
   Blead.Designation = UEBC.BVS_id__r.BVS_Title__c;
   
   Blead.state= UEBC.BVS_id__r.BVS_State__c;
   
   Blead.Phone = UEBC.BVS_id__r.BVS_PhoneNumber__c;
   
   Blead.Notes = UEBC.BVS_id__r.BVS_Notes__c ;
   
   Blead.LeadCategory = UEBC.BVS_id__r.BVS_LeadCategory__c;
   
   Blead.Lastname = UEBC.BVS_id__r.BVS_LastName__c;
   
   Blead.Firstname= UEBC.BVS_id__r.BVS_FirstName__c;
   
   Blead.Email = UEBC.BVS_id__r.BVS_Email__c;
   
   Blead.City = UEBC.BVS_id__r.BVS_City__c;
   
   Blead.RecordId = UEBC.BVS_id__r.Mrecordid__c;
   
   Blead.SurveyAnswer1 = UEBC.BVS_id__r.BVS_SurveyAnswer1__c;
    
   Blead.SurveyAnswer2 = UEBC.BVS_id__r.BVS_SurveyAnswer2__c;
    
   Blead.SurveyAnswer3 = UEBC.BVS_id__r.BVS_SurveyAnswer3__c;
     
      Blead.SurveyAnswer4 = UEBC.BVS_id__r.BVS_SurveyAnswer4__c;
      
      
      Blead.SurveyQuestion1= UEBC.BVS_id__r.BVS_SurveyQuestion1__c ;   
       
      Blead.SurveyQuestion2= UEBC.BVS_id__r.BVS_SurveyQuestion2__c ;
        
      Blead.SurveyQuestion3 = UEBC.BVS_id__r.BVS_SurveyQuestion3__c;
        
        Blead.SurveyQuestion4= UEBC.BVS_id__r.BVS_SurveyQuestion4__c;
          
           Blead.FollowupTypes = UEBC.BVS_id__r.BVS_FollowUps__c;
           
            System.debug('@@@@@bleads'+Blead);
        
        bleads.add(Blead);
        
          
  
   }
   
   
   System.debug('@@@@@bleads'+bleads);
  
    // ResponseMessage resMessage = new ResponseMessage('Success');
     
    // return resMessage; 
    
   return bleads;
    
}













global class Boothlead{
    
    
   // String EventId;
    
    String Barcode;
    

    
    String BoothPersonnelId;
    
    //String Userid;

    String imageUrl;
   
    String AttendeeId;
    
    String Firstname;
    
    String Lastname;
    
    String Email;
    
    String Company;
    
    String Designation;
    
    String Phone;
    
    String Notes;
    
    String City;
    
    String state;
    
    String leadRating;
    
    String leadId;
    
    String NumberOfVisits;
    
    String FollowupTypes;
    
    String NextFollowUpdate;
    
    String rating;
    
   // String notes;
    
    String LeadCategory;
    
    String SurveyQuestion1;
    
    String SurveyQuestion2;
    
    String SurveyQuestion3;
    
    String SurveyQuestion4;
    
    String SurveyAnswer1;
    
    String SurveyAnswer2;
    
    String SurveyAnswer3;
    
    String SurveyAnswer4;
    
    
    String RecordId;
    
    
   global BoothLead(){
        
    }
    
    
}
}