objects/Company__c.object
<CustomObject>
    <description>user companyWhen company information is null in input form. create a company with just user name and assign user role of company admin.</description>
    <label>BLN Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead_Scan__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Email__c</fullName>
        <label>Lead Email</label>
        <type>Email</type>
    </fields>
    <label>BLN Lead Scan</label>
    <nameField>
        <displayFormat>LS-{00000000}</displayFormat>
        <label>Lead Scan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Lead Scans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_ASC_ED_searchlead.cls
@RestResource(urlMapping='/BLN_ASC_ED_searchlead')
global class BLN_ASC_ED_searchlead {
  @HttpGet
   global Static BLN_ls_Fetchleads.Leadslist  doPost(){ 
    RestRequest req = RestContext.Request;
    String loginUserId = req.params.get('loginUserId');
    String eventId = req.params.get('eventId');
     String searchStr = req.params.get('searchStr');
     BLN_LeadScan_DAO lsDao = new BLN_LeadScan_DAO();
     List<Lead_Scan__c> leadlisttemp=new List<Lead_Scan__c>();
     String condition = ' AND (First_Name__c like \''+searchStr+'%\' OR Last_Name__c like \''+searchStr+'%\' OR Lead_Email__c like \''+searchStr+'%\' OR Company__c like \''+searchStr+'%\')';
     leadlisttemp = lsDao.getLeadScan(eventId,condition);
     BLN_LS_Fetchleads_BAL fetchBal = new BLN_LS_Fetchleads_BAL();
     BLN_ls_Fetchleads.Leadslist myleads = new BLN_ls_Fetchleads.Leadslist();
     myleads.user_Q_nd_A = fetchBal.getSurveyAns(leadlisttemp,loginUserId,eventId);//Get survey questions related to lead
    myleads.leadsList = leadlisttemp;
     myleads.LastModifiedDate =system.now().format('YYYY-MM-dd HH:mm:ss','GMT');
    if(leadlisttemp.size()>0)
        myleads.msg.ldvalueAssign('','',true);
      else
        myleads.msg.ldvalueAssign('Error','No leads found',false);
        system.debug('myleads======'+myleads);
      return myleads;
   }    
}