objects/Company__c.object
<CustomObject>
    <description>user companyWhen company information is null in input form. create a company with just user name and assign user role of company admin.</description>
    <label>BLN Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Constomer__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Isinserted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Isinserted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>payKey__c</fullName>
        <label>payKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Transaction Info</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>customer key Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Dummay__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Dummays</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IndividualAmount__c</fullName>
        <formula>IF( TicketTypes__c != NULL, TicketAmount__c / Tickets_Quantty__c, TicketAmount__c / Item_Quantity__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IndividualAmount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guest</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Registered_Date__c</fullName>
        <formula>CreatedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Registered Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>customer_key__c</fullName>
        <label>customer key</label>
        <referenceTo>Constomer__c</referenceTo>
        <relationshipName>Dummays</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>payKey__c</fullName>
        <label>payKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Registration Info</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Dummay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>EV_Title__c</fullName>
        <description>Changed By Phani on 09/07/2012</description>
        <label>Title</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizerId__c</fullName>
        <label>OrganizerId</label>
        <type>Email</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/transactionsreportcon.cls
public class transactionsreportcon {

public LIST<Dummay__c> dum{get;set;}
public Dummay__c dm{get;set;}
public Dummay__c temp{get;set;}
 public string eventid{get;set;}
 public string email{get;set;}
 public string paykey{get;set;}
    public transactionsreportcon()
    {
   
      
      eventid= Apexpages.CurrentPage().getParameters().get('id');
      dum= [Select ID,First_Name__c,Last_Name__c,Email__c,Company__c,payKey__c,Payment_Type__c,Registered_Date__c,customer_key__r.IsInserted__c,IndividualAmount__c,Event__r.OrganizerId__c
            FROM Dummay__c 
            WHERE Event__c=: eventid 
          // Event__r.id='a00Z000000IKyiv'
            ORDER BY Registered_Date__c DESC ];
    }
    
public void sendemail()
{
    system.debug('EMAILID:' + email + 'eventid:' + eventid);
     temp= [Select ID,First_Name__c,Last_Name__c,Email__c,Company__c,payKey__c,Payment_Type__c,Registered_Date__c,Event__r.EV_Title__c,customer_key__r.IsInserted__c,IndividualAmount__c,Event__r.OrganizerId__c
            FROM Dummay__c where id=:email AND Event__c=: eventid
           ];

    system.debug('mmmmmmmmmmmmmc'+temp);
    //email = Apexpages.CurrentPage().getParameters().get('emailid');
   // system.debug('Email Id:'+email);
    LIST<String> ccAddresses = new LIST<String>();
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    EmailTemplate template = [select Id,Body,Subject,Markup from EmailTemplate Where Name = 'Failed Transaction'];
   // mail.setTemplateId(template.Id);
   mail.setSubject('Your Registration for '+temp.Event__r.EV_Title__c  + ' did not go through');
    mail.setReplyTo('unnikrishna.tula@globalnest.com');
    mail.setToAddresses(new String[]{temp.Email__c});
    mail.setccAddresses(new String[]{temp.Event__r.OrganizerId__c});
    system.debug('ccccccccccccc'+mail);
    //ccAddresses.add('durga@globalnest.com');
    mail.setSenderDisplayName('Unni');
    User us=[select id,name,Username from User where Username=:temp.email__c];
    //mail.setTargetObjectId(us.id);
   // mail.setWhatId(dum[0].id);
    //mail.setSaveAsActivity(false);
  
   



     // EmailTemplate E = new EmailTemplate();
      
      //= [select Id,Body,Subject,HtmlValue,Markup from EmailTemplate Where Name = 'Failed Transaction'];
      
       
      String ReplaceContactName = template.body; 
        system.debug('gggggggggggg'+ReplaceContactName);
      string replacedname;
      
            
              replacedname =ReplaceContactName.Replace('{!username}',temp.First_Name__c );
              system.debug('AAAAAAAAAAAAA'+replacedname);
             
                 // replacedname = ReplaceContactName.Replace('{!Dummay__c.First_Name__c}','');
              
              
             
              replacedname = replacedname.Replace('{!event}',temp.Event__r.EV_Title__c);
              system.debug('bbbbbbbbbbbbb'+replacedname);
               mail.setPlainTextBody(replacedname);   
               
             Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });    
               
}



  public pagereference chkpay()
  {
   paykey=ApexPages.CurrentPage().getParameters().get('paykey');
   Pagereference pg= page.PayDetailTest;
   //ControllerPayDetailApi.Paykey= dum.payKey__c;
  
   return pg;
  
  }
}