objects/Company_Naicscodes__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>BLN_Company__c</fullName>
        <label>BLN Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>BLN Company_Naicscodes</relationshipLabel>
        <relationshipName>BLN_Company_Naicscodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BLN_GN_User__c</fullName>
        <label>BLN GN User</label>
        <referenceTo>GN_User__c</referenceTo>
        <relationshipLabel>BLN Company_Naicscodes</relationshipLabel>
        <relationshipName>BLN_Company_Naicscodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BLN_NAICS_Code__c</fullName>
        <label>BLN NAICS Code</label>
        <referenceTo>NAICS_Code__c</referenceTo>
        <relationshipLabel>BLN Company_Naicscodes</relationshipLabel>
        <relationshipName>BLN_Company_Naicscodes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BLN_TKT_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Company_Naicscodes</relationshipLabel>
        <relationshipName>BLN_Company_Naicscodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Company_Naicscodes</label>
    <nameField>
        <displayFormat>CN-{0000000}</displayFormat>
        <label>Custom Object Label Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Company_Naicscodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NAICS_Code__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>NAICS Code</label>
    <nameField>
        <label>NAICS Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NAICS Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_CompNaics_DAO.cls
public with sharing class BLN_CompNaics_DAO {
    public void NaicsHandle(Id compId,Id uId,String naicsCodesString){
          Savepoint sp = Database.setSavepoint();
            List<Company_Naicscodes__c> comList = new List<Company_Naicscodes__c>();
            List<Company_Naicscodes__c>  naicsListToinsert = new List<Company_Naicscodes__c>();

            for(String ncs : naicsCodesString.split('-')){
             if(ncs=='' ){

            }else{
                 comList = [SELECT id from Company_Naicscodes__c Where BLN_Company__c=:compId AND BLN_GN_User__c=:uId];
                 Database.Delete(comList,false);
           

                Company_Naicscodes__c nind = new Company_Naicscodes__c();
                   nind.BLN_GN_User__c = uId;
                   nind.BLN_Company__c = compId;
                   system.debug('dddddddddddddddddddddddddd'+ncs);
                   nind.BLN_NAICS_Code__c = ncs;
                   naicsListToinsert.add(nind);
            }
               
            }
            
            Database.SaveResult[] sRes = Database.insert(naicsListToinsert,false);
               for(Database.SaveResult sR :sRes){
                  if(sR.isSuccess()){
                     
                  }else{
                    Database.RollBack(sp);
                  }
               }
       }
 public void NaicsHandle(Id tktId,String naicsCodesString){
          Savepoint sp = Database.setSavepoint();
            List<Company_Naicscodes__c> comList = new List<Company_Naicscodes__c>();
            List<Company_Naicscodes__c>  naicsListToinsert = new List<Company_Naicscodes__c>();

            for(String ncs : naicsCodesString.split('-')){
             if(ncs=='' ){

            }else{
                 comList = [SELECT id from Company_Naicscodes__c Where BLN_tkt_profile__c=:tktId];
                 Database.Delete(comList,false);
                Company_Naicscodes__c nind = new Company_Naicscodes__c();
                   nind.BLN_tkt_profile__c = tktId;
                   system.debug('dddddddddddddddddddddddddd'+ncs);
                   nind.BLN_NAICS_Code__c = ncs;
                   naicsListToinsert.add(nind);
            }
               
            }
            
            Database.SaveResult[] sRes = Database.insert(naicsListToinsert,false);
               for(Database.SaveResult sR :sRes){
                  if(sR.isSuccess()){
                     
                  }else{
                    Database.RollBack(sp);
                  }
               }
       }


        /********This method is to get gnuser company NAICS codes,written by Purna *******************************/
        
         public List<Company_Naicscodes__c> getCompGNUserNaics(String compid ,Id gnuid){
        return  [SELECT id,BLN_Company__c,BLN_GN_User__c,BLN_NAICS_Code__r.Description__c from Company_Naicscodes__c where BLN_Company__c=:compid and BLN_GN_User__c = : gnuid]; 
}

}