objects/Company__c.object
<CustomObject>
    <description>user companyWhen company information is null in input form. create a company with just user name and assign user role of company admin.</description>
    <label>BLN Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event_Pay_Gateway__c.object
<CustomObject>
    <description>This table defines the payment gateway for event for different payment types.  (online booking, at gate booking)</description>
    <fields>
        <fullName>Accept_Min_Max_Range__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accept Min Max Range</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Events__c</fullName>
        <label>Events</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Event_Pay_Gateway</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Min_amount_to_accept__c</fullName>
        <label>Min amount to accept</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pay_Gateway__c</fullName>
        <label>Pay Gateway</label>
        <referenceTo>Pay_Gateway__c</referenceTo>
        <relationshipName>Event_Pay_Gateway</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registration_Type__c</fullName>
        <label>Registration Type</label>
        <picklist>
            <picklistValues>
                <fullName>Online</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Onsite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ScanAttendee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Event Pay Gateway</label>
    <nameField>
        <displayFormat>EPG-{000000}</displayFormat>
        <label>Event Pay Gateway ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Event Pay Gateway</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Pay_Gateway__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Pay_Gateway</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Min_amount_to_accept__c</fullName>
        <label>Min amount to accept</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PG_Email_Id__c</fullName>
        <label>PG Email Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PG_Pass_Secret__c</fullName>
        <label>PG Pass Secret</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>PG_Signature__c</fullName>
        <label>PG Signature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PG_User_Key__c</fullName>
        <label>PG User Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PGateway_Type__c</fullName>
        <label>PGateway Type</label>
        <referenceTo>PGateway_Type__c</referenceTo>
        <relationshipName>Pay_Gateway</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PP_Fee_Payer__c</fullName>
        <description>This field determines the paypal fee payer</description>
        <label>PP Fee Payer</label>
        <picklist>
            <controllingField>PP_Payment_Type__c</controllingField>
            <picklistValues>
                <fullName>EACHRECEIVER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRIMARYRECEIVER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SENDER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SECONDARYONLY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PP_Payment_Type__c</fullName>
        <description>This field determines the Paypal payment type</description>
        <label>PP Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Parallel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simple</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Fee__c</fullName>
        <label>Pay Gateway Service Fee</label>
        <picklist>
            <picklistValues>
                <fullName>Include</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclude</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Use_Host_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Host Page</label>
        <type>Checkbox</type>
    </fields>
    <label>BLN Pay Gateway</label>
    <nameField>
        <displayFormat>PG-{00000000}</displayFormat>
        <label>Pay Gateway Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Pay Gateway</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PGateway_Type__c.object
<CustomObject>
    <fields>
        <fullName>Adaptive_Type__c</fullName>
        <label>Adaptive_Type</label>
        <picklist>
            <picklistValues>
                <fullName>Direct</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Display_Type__c</fullName>
        <label>Display Type</label>
        <picklist>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <label>BLN PGateway Type</label>
    <nameField>
        <label>PGateway_Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN PGateway Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_EventPayGateway_DAO.cls
public with sharing class BLN_EventPayGateway_DAO{

/***********************************************************************************************
*   Controller Name         : BLN_EventPayGateway_DAO
*   Date                    : 17/06/2014 
*   Author                  : Mahesh Sakunala
*   Purpose                 : This class is for Retrieving Pay Gateways of Events.
**************************************************************************************************/

    
    public LIST<Event_Pay_Gateway__c> getEventPayGateWays(String EventId){
        LIST<Event_Pay_Gateway__c> EventPayGateWays = new LIST<Event_Pay_Gateway__c>();
        return EventPayGateWays = [SELECT Accept_Min_Max_Range__c,Min_amount_to_accept__c,Registration_Type__c,Pay_Gateway__r.Use_Host_Page__c,Id,Events__c,Pay_Gateway__c,Pay_Gateway__r.Id,Pay_Gateway__r.Company__c,Pay_Gateway__r.PP_Fee_Payer__c,Pay_Gateway__r.PP_Payment_Type__c,Pay_Gateway__r.PGateway_Type__c,Pay_Gateway__r.PG_Email_Id__c,Pay_Gateway__r.PG_Pass_Secret__c,Pay_Gateway__r.PG_Signature__c,Pay_Gateway__r.PG_User_Key__c,Pay_Gateway__r.Service_Fee__c,Pay_Gateway__r.Min_amount_to_accept__c,Pay_Gateway__r.PGateway_Type__r.Name,Pay_Gateway__r.PGateway_Type__r.Adaptive_Type__c,Pay_Gateway__r.PGateway_Type__r.Display_Type__c, Pay_Gateway__r.PGateway_Type__r.Help_Text__c, Pay_Gateway__r.PGateway_Type__r.Image_URL__c FROM Event_Pay_Gateway__c WHERE Events__c=: EventId];
    }
    
    public LIST<Event_Pay_Gateway__c> getEventPayGateWaysbasedonmodule(String EventId,String Module){
        LIST<Event_Pay_Gateway__c> EventPayGateWays = new LIST<Event_Pay_Gateway__c>();
        return EventPayGateWays = [SELECT Accept_Min_Max_Range__c,Min_amount_to_accept__c,Registration_Type__c,Pay_Gateway__r.Use_Host_Page__c,Id,Events__c,Pay_Gateway__c,Pay_Gateway__r.Id,Pay_Gateway__r.Company__c,Pay_Gateway__r.PP_Fee_Payer__c,Pay_Gateway__r.PP_Payment_Type__c,Pay_Gateway__r.PGateway_Type__c,Pay_Gateway__r.PG_Email_Id__c,Pay_Gateway__r.PG_Pass_Secret__c,Pay_Gateway__r.PG_Signature__c,Pay_Gateway__r.PG_User_Key__c,Pay_Gateway__r.Service_Fee__c,Pay_Gateway__r.Min_amount_to_accept__c,Pay_Gateway__r.PGateway_Type__r.Name,Pay_Gateway__r.PGateway_Type__r.Adaptive_Type__c,Pay_Gateway__r.PGateway_Type__r.Display_Type__c, Pay_Gateway__r.PGateway_Type__r.Help_Text__c, Pay_Gateway__r.PGateway_Type__r.Image_URL__c FROM Event_Pay_Gateway__c WHERE Events__c=: EventId and Registration_Type__c=:Module];
    }
    
     public static Event_Pay_Gateway__c getEventPayGateWay(String EventId,String Name,String Module){
         Event_Pay_Gateway__c  EGateway = new Event_Pay_Gateway__c ();
        return EGateway =[SELECT Accept_Min_Max_Range__c,Min_amount_to_accept__c,Registration_Type__c,Pay_Gateway__r.Use_Host_Page__c,Id,Name,Pay_Gateway__r.PGateway_Type__r.name,Events__c,Pay_Gateway__c,Pay_Gateway__r.Id,Pay_Gateway__r.PGateway_Type__r.Adaptive_Type__c,Pay_Gateway__r.Name FROM Event_Pay_Gateway__c WHERE Events__c=:EventId and Registration_Type__c=:Module and Pay_Gateway__r.PGateway_Type__r.name=:Name limit 1];
    }

}