objects/Company__c.object
<CustomObject>
    <description>user companyWhen company information is null in input form. create a company with just user name and assign user role of company admin.</description>
    <label>BLN Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GN_User__c.object
<CustomObject>
    <description>The address fields belong to user home address
This should be the only link between gnuser and salesforce user. salesforce user table should not be accessible any where else in db except this table.</description>
    <label>BLN GN User</label>
    <nameField>
        <displayFormat>GNU-{000000}</displayFormat>
        <label>GN User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN GN Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pay_Address__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Pay_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Pay_Addresses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>GN_User__c</fullName>
        <label>GN User</label>
        <referenceTo>GN_User__c</referenceTo>
        <relationshipName>Pay_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Pay Address</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Pay Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Pay Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_BLN_Pay_Address_DAO.cls
@isTest
public class Test_BLN_Pay_Address_DAO {

    static testMethod void testmethod_BLN_Pay_Address_DAO(){
    
    BLN_Pay_Address_DAO bd = new BLN_Pay_Address_DAO();
    
    Pay_Address__c pc = new Pay_Address__c();
     
    bd.insertPayAddress(pc);
    
    List<Pay_Address__c> lc = new List<Pay_Address__c>();
    
    bd.getbillingAddress('test');
    
     string ed = pc.Event__c;
     string ab = pc.Company__c;
     string  cd = pc.GN_User__c;
    globalForTestClass globalTest= new globalForTestClass();
    company__c companyInfo= new Company__c();
    companyInfo= globalTest.createCompany('globalnest');
    set<id> cid= new set<id>();
    cid.add(companyInfo.id);
     bd.billingAddrssForReport(cid);
    bd.insertPayAddressprocess(ed,ab,cd);
    
    }
    
  }