objects/Company__c.object
<CustomObject>
    <description>user companyWhen company information is null in input form. create a company with just user name and assign user role of company admin.</description>
    <label>BLN Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Role__c.object
<CustomObject>
    <description>user roleEvent AdminEvent StaffCompany Admin</description>
    <label>BLN Role</label>
    <nameField>
        <label>Role  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UC_Role__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>User_Company</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Event Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company Admin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN UC_Role</label>
    <nameField>
        <displayFormat>UC-{00000000}</displayFormat>
        <label>UC_Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN UC_Role</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UtillForNewBL.cls
public without sharing class UtillForNewBL{
/***********************************************************************************************
*   Controller Name : UtillForNewBL 
*   Date            : 07/05/2014
*   Author          : Phani Kumar Ch
*   Purpose         : Utill class
*   Change History  : 07/05/2014 

*   Date                 Programmer                     Reason
*   --------------      -------------------           -------------------------
*   07/05/2014         Phani Kumar Ch                  To Create Page
**************************************************************************************************/
   
// This method is for inserting user
 public string InsertUser(user u,string pass){
 
 user uname=[SELECT Id,CreatedById,isActive FROM User WHERE profile.Name =: 'System Administrator' AND isActive=: true LIMIT 1];
 
            Account acc = new Account();
            acc.name='Booth Leads';    
            acc.ownerId=uname.id; 
            insert acc; 
            
            system.debug('!!!! '+u);
            contact Con = new Contact();
            Con.Lastname = u.firstname;
            Con.Firstname = u.lastname; 
            con.email = u.email;
            Con.AccountID = acc.id;
            insert Con;
            
           Profile P = [SELECT Id,Name FROM Profile WHERE Name = 'Event Admin'];
           U.ContactID = Con.id;    
           U.Username = u.email;  
           U.Alias = 'EAdmin';
           U.ProfileID = P.id;
           U.CommunityNickname = String.valueOf(math.random());
           
            if(pass!=null && pass!=''){
            u.password__c =pass;
            u.isSignup__c =true;
            }
            U.LocaleSidKey = 'en_US';
            U.LanguageLocaleKey = 'en_US';
            U.TimeZoneSidKey = 'America/Los_Angeles';
            U.EmailEncodingKey='UTF-8';
            Database.insert(U);
            return u.id;
 }
 
 // This  Method is for Inserting Comany 
  public string insertCompany(Company__c  com){
   insert  com;
   return com.id;
  }
 
 // This method is for inserting user Company role

  public void insertUC_role(string uId,string cId){
     UC_Role__c uRole = new UC_Role__c();
     uRole.Company__c = cId;
     //uRole.Role__c = 'Company Admin';
    //uRole.User__c =uId;
     insert uRole;
          
  }


/////ADDED BY ARINDAM///////
// This method is for updated user
 public string UpdateUser(user u){
 
 //update user
 user updateuser=[SELECT FirstName,LastName,Email FROM User WHERE Username =: u.Email LIMIT 1];
 updateuser.FirstName=u.FirstName;
 updateuser.LastName=u.LastName ;
 update updateuser;
 
 //update contact
 try
 {
 contact Con = [Select FirstName,LastName,email from contact where email=:u.email]; 
            Con.Lastname = u.firstname;
            Con.Firstname = u.lastname; 
            update con;          
    }catch( Exception e){}        
 
 return updateuser.id;
 }
 
 
 
 // This method is for updating user Company 

  public void updateUC_role(string email,string cId){
  User use=[select id,email from User where email=:email];
  //UC_Role__c updaterole=[select User__c,Company__c from UC_Role__c  where User__c=:use.id limit 1];
     //updaterole.Company__c = cId;
     //update updaterole;
   
          
  }

}