objects/Company__c.object
<CustomObject>
    <description>user companyWhen company information is null in input form. create a company with just user name and assign user role of company admin.</description>
    <label>BLN Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GN_User__c.object
<CustomObject>
    <description>The address fields belong to user home address
This should be the only link between gnuser and salesforce user. salesforce user table should not be accessible any where else in db except this table.</description>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GN_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN GN User</label>
    <nameField>
        <displayFormat>GNU-{000000}</displayFormat>
        <label>GN User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN GN Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pay_Gateway__c.object
<CustomObject>
    <fields>
        <fullName>BLN_GN_User__c</fullName>
        <label>BLN GN User</label>
        <referenceTo>GN_User__c</referenceTo>
        <relationshipLabel>BLN Pay Gateway</relationshipLabel>
        <relationshipName>BLN_Pay_Gateway</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipName>Pay_Gateway</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PG_Email_Id__c</fullName>
        <label>PG Email Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>PG_Pass_Secret__c</fullName>
        <label>PG Pass Secret</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>PG_Signature__c</fullName>
        <label>PG Signature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PG_User_Key__c</fullName>
        <label>PG User Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PGateway_Type__c</fullName>
        <label>PGateway Type</label>
        <referenceTo>PGateway_Type__c</referenceTo>
        <relationshipName>Pay_Gateway</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PP_Fee_Payer__c</fullName>
        <description>This field determines the paypal fee payer</description>
        <label>PP Fee Payer</label>
        <picklist>
            <controllingField>PP_Payment_Type__c</controllingField>
            <picklistValues>
                <fullName>EACHRECEIVER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRIMARYRECEIVER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SENDER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SECONDARYONLY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PP_Payment_Type__c</fullName>
        <description>This field determines the Paypal payment type</description>
        <label>PP Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Parallel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simple</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Paygateway_name__c</fullName>
        <label>Paygateway_name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN Pay Gateway</label>
    <nameField>
        <displayFormat>PG-{00000000}</displayFormat>
        <label>Pay Gateway Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Pay Gateway</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PGateway_Type__c.object
<CustomObject>
    <label>BLN PGateway Type</label>
    <nameField>
        <label>PGateway_Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN PGateway Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_ASC_AddPayGatewayKey.cls
@RestResource(urlMapping='/BLN_ASC_AddPayGatewayKey/*')
global class BLN_ASC_AddPayGatewayKey {

  @HttpPost  
  global static Response doPost(){  
        
        RestRequest req = RestContext.Request;
        String EventId =req.params.get('Event_Id'); 
        String Module=req.params.get('Module'); 
        String paygatewaykeyname=req.params.get('Paygatewaykeyname'); 
        String paygatewayid=req.params.get('Paygatewayid'); 
        string payjsonInput = req.requestBody.tostring();
        BLN_ReUse_EventsEditCon.PaymentOpt pinfo=BLN_ReUse_EventsEditCon.new_savesPaymentGateways(payjsonInput,EventId,paygatewaykeyname,paygatewayid,Module);
        Response response=new Response();
        if(pinfo.firstparam=='Success'){
            response.status=pinfo.firstparam;
            response.message=pinfo.secondparam;
            response.pg=new Pay_Gateway__c();
        response.pg=[SELECT Id,BLN_GN_User__r.User__c,Name,Company__c,Paygateway_name__c,PGateway_Type__c,PGateway_Type__r.Name,PG_Email_Id__c,PG_Pass_Secret__c,PG_Signature__c,PG_User_Key__c,PP_Fee_Payer__c,PP_Payment_Type__c FROM Pay_Gateway__c where id=:pinfo.secondparam order by Company__c];
        return response;
        }
        else
        {
         response.status=pinfo.firstparam;
            response.message=pinfo.secondparam;
        response.pg=new Pay_Gateway__c();
        return response;
        }
  }
  
  
  
  global class Response
  {
    public String status{get;set;}
    public String message{get;set;}
    public Pay_Gateway__c pg{get;set;}
  }
 

}