objects/Company__c.object
<CustomObject>
    <description>user companyWhen company information is null in input form. create a company with just user name and assign user role of company admin.</description>
    <label>BLN Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Company</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipName>Countries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>BLN Country</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Currency__c.object
<CustomObject>
    <label>BLN Currency</label>
    <nameField>
        <label>Currency Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Currency</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GN_User__c.object
<CustomObject>
    <description>The address fields belong to user home address
This should be the only link between gnuser and salesforce user. salesforce user table should not be accessible any where else in db except this table.</description>
    <label>BLN GN User</label>
    <nameField>
        <displayFormat>GNU-{000000}</displayFormat>
        <label>GN User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN GN Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>State</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN State</label>
    <nameField>
        <label>State Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_userinfoEventdex.cls
@istest
public class Test_userinfoEventdex{

 static testmethod void TestuserinfoEventdex(){
 User U= new User();
        globalForTestClass globalTest= new globalForTestClass();
        U= globalTest.createUser();
        system.runas(U){
            User userForGN= new User();
            userForGN= globalTest.createUserForGNUser();
            Company__c companyInfo= new Company__c();
            
            companyInfo= globalTest.createCompany(u.Companyname);
            
            Currency__c currenyInfo= new Currency__c();
            currenyInfo= globalTest.createCurrency();             
            
            Country__c countryInfo= new Country__c();
            countryInfo= globalTest.createCountry(currenyInfo.Id);  
            
            State__c stateInfo= new State__c ();
            stateInfo= globalTest.createState(countryInfo.Id);
            
            GN_User__c  gnUser= new GN_User__c();
            gnUser = globalTest.createGNUser(userForGN,countryInfo.Id, Stateinfo.Id);
            
                     System.RestContext.request = new RestRequest(); 
     RestContext.request.requestURI ='/GlobalnestEM/userinfoEventdex';
      RestContext.request.addParameter('userid',u.id);
      userinfoEventdex.doPost();

 
 }


}

}