objects/DeviceUsage__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>DeviceUsages</relationshipLabel>
        <relationshipName>DeviceUsages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IMEI__c</fullName>
        <label>IMEI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OsVersion__c</fullName>
        <label>OsVersion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DeviceUsages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DeviceUsage</label>
    <nameField>
        <displayFormat>Dev_{000000000}</displayFormat>
        <label>DeviceUsage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DeviceUsages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>EV_EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_EndTime__c</fullName>
        <label>EndTime</label>
        <picklist>
            <picklistValues>
                <fullName>12:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:05 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:10 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:20 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:25 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:35 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:40 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:50 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:55 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:05 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:10 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:20 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:25 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:35 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:40 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:50 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:55 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:05 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:10 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:20 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:25 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00 AM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EV_HostingTimeZone__c</fullName>
        <label>HostingTimeZone</label>
        <picklist>
            <picklistValues>
                <fullName>Eastern Time(USA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Time(USA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mountain Time(USA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific Time(USA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indian Standard Time(IST)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central European Time Zone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EV_StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Title__c</fullName>
        <description>Changed By Phani on 09/07/2012</description>
        <label>Title</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FacebookId__c</fullName>
        <label>FacebookId</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>StartTime</label>
        <picklist>
            <picklistValues>
                <fullName>12:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:05 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:10 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:20 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:25 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:35 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:40 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:50 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:55 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:05 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:10 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:20 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:25 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:35 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:40 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:50 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:55 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:05 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:10 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:20 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:25 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00 AM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_AttendedFbUsers.cls
@isTest
public class Test_AttendedFbUsers{

public static testMethod void testdoget(){

contact m = new contact(firstname='testcontactname',lastname='testcontactlastname');
           insert m;
       Profile w = [select id from profile where name='Standard User'];
  
   // ------------------ Eventadmin Insert ---------------------
        User u = new User(alias = 'test123', email='test100@noemail.com',
                 emailencodingkey='UTF-8',profileid = w.Id,lastname='Testing', languagelocalekey='en_US',
                  localesidkey='en_US',country='United States',
                  timezonesidkey='America/Los_Angeles', username='test100@noemail.com', FaceBookId__c='596207599');
                  insert u;
                  Id eventAdminId=u.id;    
 
 
   Event__c eve = new Event__c(EV_Title__c='Global Event',EV_HostingTimeZone__c='Eastern Time(USA)',
                             EV_EndDate__c =  Date.Parse('01/18/2014'),
                             EV_StartDate__c = Date.Parse('01/18/2014'),
                             EV_EndTime__c='09:00 AM',
                             StartTime__c='11:00 AM');
      insert eve;
      Id EventId=eve.Id;

 DeviceUsage__c device=new DeviceUsage__c(EV_id__c=eve.id,IMEI__c='12365',OsVersion__c='safari 6',User__c=u.id);
     insert device;
     
     system.runAs(u){
     
      System.RestContext.request = new RestRequest();
       RestContext.request.requestURI = '/GlobalnestEM/AttendedFbUsers';
       RestContext.request.addParameter('eventIDForFB',eve.id);
       RestContext.request.addParameter('userid', u.Id);
       string JSONMsg='[{"id":"596207598","Name":"Mk Chakravarthy"},{"id":"596207599","Name":"Chpk"}]';
       RestContext.request.requestBody = Blob.valueof(JSONMsg );
         AttendedFbUsers.doPost();
     }
     
     

}


}