objects/Dummay__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Dummays</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TicketTypes__c</fullName>
        <label>TicketTypes</label>
        <referenceTo>TicketTypes__c</referenceTo>
        <relationshipName>Dummays</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Registration Info</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Dummay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>AS_HostingCity__c</fullName>
        <label>HostingCity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_EventLogo__c</fullName>
        <label>EventLogo</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>EV_HistingAddr1__c</fullName>
        <label>HistingAddr1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_HostingLocation__c</fullName>
        <label>HostingLocation</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_HostingState__c</fullName>
        <label>HostingState</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_HostingZipcode__c</fullName>
        <label>HostingZipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Title__c</fullName>
        <description>Changed By Phani on 09/07/2012</description>
        <label>Title</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event_Attendee_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event_Attendee_Mapping</relationshipLabel>
        <relationshipName>Event_Attendee_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TicketTypes__c</fullName>
        <description>Ticket Types used  to store the selected tickets by  Event Admin, used in the  Attendee registration</description>
        <inlineHelpText>Ticket Types used  to store the selected tickets by  Event Admin, used in the  Attendee registration</inlineHelpText>
        <label>TicketTypes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Event_Attendee_Mapping</label>
    <nameField>
        <displayFormat>EA{0000000000}</displayFormat>
        <label>EA_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event_Attendee_Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MatchLeads_Days__c.object
<CustomObject>
    <description>It is save no of days Match Leads will be and the timings when the matching will be started.</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>MatchLeads_Days</relationshipLabel>
        <relationshipName>MatchLeads_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_time__c</fullName>
        <description>Start time when the match leads will be started</description>
        <label>Start time</label>
        <picklist>
            <picklistValues>
                <fullName>12:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>MatchLeads_Days</label>
    <nameField>
        <displayFormat>D-{000}</displayFormat>
        <label>MatchLeads_Days Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MatchLeads_Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Profile__c.object
<CustomObject>
    <fields>
        <fullName>PR_Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Profile name</label>
    <nameField>
        <displayFormat>PR_{000}</displayFormat>
        <label>profile_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profile cus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TicketTypes__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>TicketTypes</relationshipLabel>
        <relationshipName>TicketTypes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <picklist>
            <picklistValues>
                <fullName>12:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:15 AM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TicketTypes</label>
    <nameField>
        <displayFormat>TT_{0000000}</displayFormat>
        <label>TT_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TicketTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Profile_Event__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile_id__c</fullName>
        <label>Profile</label>
        <referenceTo>Profile__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UEP_isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_id__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User_Profile_Event</label>
    <nameField>
        <displayFormat>UPE_{00000000}</displayFormat>
        <label>UPE_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Profile_Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SA_TicketsController.cls
public with sharing class SA_TicketsController{

    // Ticket Variables
    public LIST<LIST<TicketTypes__c>> TicketTypes{get; set;}
    public TicketTypes__c TT{get; set;}
    public Boolean TicketPopUp{get;set;}
    public Boolean AddTicketPopUp{get;set;}
    public Boolean SelectedTicketMode{get;set;}
    public String TicketIdParam{get;set;}
    public String TableHeading{get;set;}
    public Id SelectedTicketId{get;set;}
    public Id SelectedEventId{get;set;}
    public Event__c SelectedEvent{get;set;}
    public transient Blob Logo{get;set;}
    public String LogoName{get;set;}
    public Boolean myDocBool{get; set;}
    public Document mydoc{get;set;}
    public boolean ShowTicketCost{get; set;}
    public MAP<ID, String> SessionNamesMAP{get; set;}
    public Boolean isPastEvent{get; set;}     
    public Boolean isEventAdminStaffUser{get; set;}   
    public LIST<MatchLeads_Days__c> SessionsList{get; set;}
        
    public SA_TicketsController(){
    
        TicketPopUp = TRUE;
        AddTicketPopUp = FALSE;
        myDocBool = FALSE;  
        SelectedTicketMode = FALSE;
        ShowTicketCost= FALSE;
 
        system.debug(TicketPopUp +' POPUPS '+AddTicketPopUp );
        Cookie counter = ApexPages.currentPage().getCookies().get('counter');
        if(counter !=null){

            SelectedEventId  = counter.getValue();
             SelectedEvent= [SELECT  ID, EV_Title__c, EV_HostingLocation__c, EV_HistingAddr1__c, AS_HostingCity__c, 
                            EV_HostingZipcode__c, EV_EventLogo__c, EV_StartDate__c, EV_EndDate__c, EV_HostingState__c,
                            (SELECT ID FROM MatchLeads_Days__r) 
                            FROM Event__c 
                            Where Id=:SelectedEventId];
            
            SessionsList= SelectedEvent.MatchLeads_Days__r;
            isPastEvent= FALSE;
            if(SelectedEvent.EV_EndDate__c < system.today()){
                isPastEvent= TRUE;                
            } 
            List<User_Profile_Event__c> loginUserProfile= new LIST<User_Profile_Event__c>();
            loginUserProfile= [SELECT ID, Profile_id__r.PR_Name__c 
                               FROM User_Profile_Event__c 
                               WHERE EV_id__c =: SelectedEventId AND 
                               UEP_isActive__c =: TRUE AND
                               User_id__c =: UserInfo.getUserId()];
            
            isEventAdminStaffUser= FALSE;                               
            if(loginUserProfile.size() >0){
                for(User_Profile_Event__c prof: loginUserProfile){
                    if(prof.Profile_id__r.PR_Name__c == 'EventAdmin Staff'){
                        isEventAdminStaffUser= TRUE;
                    }
                }
            }  
        }
        system.debug(' EVENT ID '+SelectedEventId);
        SelectedSessionIds= new LIST<String>();
        SessionsListPick= new LIST<SelectOption>();
        SessionNamesMAP= new MAP<ID, String>();

                
        SessionsList= new LIST<MatchLeads_Days__c>();
        SessionsList= [SELECT ID, Start_time__c, End_Time__c, MatchLeads_Date__c, Session_Name__c 
                       FROM MatchLeads_Days__c
                       WHERE Event__c =: SelectedEventId];

        for(MatchLeads_Days__c session: SessionsList){
            String SessionDate= String.valueof(session.MatchLeads_Date__c.format());
            SessionsListPick.add(new SelectOption(session.Id, session.Session_Name__c+'  '+SessionDate));
            SessionNamesMAP.put(session.Id, session.Session_Name__c+'/'+String.valueof(session.MatchLeads_Date__c));
        }
        
        ticketsList();
    }
    
    public PageReference ticketsList(){
        try{
        TicketPopUp = true;
        AddTicketPopUp = false;
        ShowTicketError= FALSE;
        system.debug('****** '+SelectedEventId);
        TicketTypes= new LIST<LIST<TicketTypes__c>>();
        LIST<TicketTypes__c> ticketsList= new LIST<TicketTypes__c>();
        
        ticketsList= [SELECT Id,TT_Name__c,EV_id__c,TT_Amount__c,TT_Sold__c,Ticket_Image_URL__c,Ticket_Category__c,
                      Ticket_Description__c,TT_TicketType__c,TT_Available__c, Available__c 
                      FROM TicketTypes__c 
                      WHERE EV_id__r.id =: SelectedEventId AND TT_Name__c != 'Guest' AND TT_Name__c != 'Attendee Staff'];
                       
                       
        LIST<TicketTypes__c> tickets999= new LIST<TicketTypes__c>();
         
         for(TicketTypes__c  tic: ticketsList){
             
                 tickets999.add(tic);
             
             if(tickets999.size() == 999){
                 TicketTypes.add(tickets999);
                 tickets999= new LIST<TicketTypes__c>();
             }
             system.debug('  MBES LIST  '+tickets999.size()+'  '+TicketTypes.size());
         }
         
         if(tickets999.size() != 0){
              TicketTypes.add(tickets999);
         }
         
                        
        }catch(exception ex){}
        return null;
    }
    
    public Boolean ShowTicketError{get; set;}
    public pagereference deleteTicket(){
        
       SelectedTicketId= ApexPages.currentpage().getparameters().get('TicketIdParam');
       ShowTicketError= FALSE;
       system.debug('DELETE ID 222222222222222  '+SelectedTicketId );
       TT = [SELECT Id,TT_Name__c,EV_id__c,TT_Amount__c,TT_Sold__c,Ticket_Image_URL__c,Ticket_Category__c,
             Ticket_Description__c,TT_TicketType__c,TT_Available__c, (SELECT ID FROM Dummays__r WHERE Event__c =: SelectedEventId
             AND Event_Attendee_Mapping__c != NULL)  
             FROM TicketTypes__c 
             WHERE Id =: SelectedTicketId];
       system.debug('DELETE ID 33333333333  '+TT );
       
        LIST<Dummay__c>  RegInfoList= new LIST<Dummay__c>(); 
           RegInfoList=TT.Dummays__r;
           if(RegInfoList.size() >0){
            ShowTicketError= TRUE;               
           }else{
               database.delete(TT);
               TicketPopUp = true;
               AddTicketPopUp = false;
               ticketsList();
           }
       
        return null;
    }

    public void editTicket(){
        TableHeading='Edit Ticket';
        SelectedTicketMode = true;
        TicketPopUp = false;
        AddTicketPopUp = true;
        ShowTicketError= FALSE;
        SelectedSessionIds= new LIST<String>();
        
        SelectedTicketId = ApexPages.currentpage().getparameters().get('TicketIdParam');
        TT = [SELECT Id,TT_Name__c,EV_id__c,TT_Amount__c,TT_Sold__c,Ticket_Image_URL__c,Ticket_Category__c,
              Ticket_Description__c,TT_TicketType__c,TT_Available__c, (SELECT ID, Session__c FROM Ticket_Session_Mapping__r) 
              FROM TicketTypes__c 
              WHERE Id =: SelectedTicketId];
              
        if(TT.TT_TicketType__c == 'Free'){
            ShowTicketCost= FALSE; 
        }else{
            ShowTicketCost= TRUE; 
        }
        
        LIST<Ticket_Session_Mapping__c> TSMList= new LIST<Ticket_Session_Mapping__c>();
        TSMList= TT.Ticket_Session_Mapping__r;
        system.debug(TSMList.size()+' TSM LIST '+TSMList);
        if(TSMList.size() >0){
            for(Ticket_Session_Mapping__c TSM: TSMList){
                SelectedSessionIds.add(TSM.Session__c);         
            }
        
        }

    }
    
    public LIST<SelectOption> SessionsListPick{get; set;}
    public LIST<String> SelectedSessionIds{get; set;}
    
    public void addTicket(){
    
        TableHeading='Add Ticket';
        SelectedTicketMode = true;
        ShowTicketCost= TRUE;
        ShowTicketError= FALSE;
        TicketPopUp = false;
        AddTicketPopUp = true;
        TT = new TicketTypes__c();
        TT.TT_Amount__c=0;
        SelectedSessionIds= new LIST<String>();
    }
    
       
    public String SelectedTicketType{get; set;} 
    
    public void ticketTypeVal(){
        system.debug(apexpages.currentpage().getparameters().get('ticketType')+' SELECTED TICKET TYPE '+SelectedTicketType);
        
        if(SelectedTicketType == 'Free'){
            ShowTicketCost= FALSE; 
            TT.TT_TicketType__c = SelectedTicketType; 
            TT.TT_Amount__c=0;      
        }else{
            ShowTicketCost= TRUE; 
            TT.TT_TicketType__c = SelectedTicketType;       
        }
            
    }
    
    public String SessionNames{get; set;}
        
    public void createTicket(){
        ShowTicketError= FALSE;
        myDocBool = TRUE;       
           if(Logo != null && ( LogoName != '' || LogoName != NULL )){
               if(Logo.size()!= null){
                 
               if(Logo.size() < 1048576 ){
                    mydoc = new document();
                    mydoc.body = Logo;
                    mydoc.folderid = '00lF0000001VI7Y';
                    
                    mydoc.IsPublic = True;
                    mydoc.Name = LogoName;
                    DataBase.saveResult docSaveResult = DataBase.insert(mydoc, false);
        
                    String eventold;
        
                    if(docSaveResult.isSuccess()){
                        if(TT.Ticket_Image_URL__c != null){
                            try{
                            eventold = TT.Ticket_Image_URL__c;          
                            document dd = [SELECT ID, NAME FROM document WHERE id=: eventold];
                            Database.delete(dd);
                            }
                            catch(exception ex){}
                        }
                        String imageURL='';
                        string urlbase =URL.getSalesforceBaseUrl().getHost();
                        string orgId = UserInfo.getOrganizationId();
                    
                        imageURL= 'https://'+urlbase+'/servlet/servlet.ImageServer?oid='+orgId+'&id='+docSaveResult.getId();
                        TT.Ticket_Image_URL__c = docSaveResult.getId();
                    }
                    else{
                        myDocBool = FALSE;
                        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, String.valueOf(docSaveResult.getErrors()))); 
                    } 
                }
                else{
                    myDocBool = FALSE; 
                }
               }            
         }
         TT.EV_id__c = SelectedEventId;   
         system.debug('&&&& '+TT);
         Database.UpsertResult EventupsertResult= DataBase.Upsert(TT, false);
         system.debug(' SESSION IDS  '+SelectedSessionIds);
         
         LIST<Ticket_Session_Mapping__c> upsertTSMList= new LIST<Ticket_Session_Mapping__c>();
         SessionNames='';
         integer i=0;
         if(SelectedSessionIds.size() >0){
             for(String session: SelectedSessionIds){
             
                 Ticket_Session_Mapping__c insertTSM= new Ticket_Session_Mapping__c();
                 insertTSM.Session__c= session;
                 insertTSM.Ticket__c= TT.Id;
                 insertTSM.Unique_Ids__c= session+'-'+TT.Id;
                 SessionNames= SessionNames+SessionNamesMAP.get(session)+',';
                 if(i ==0){
                     insertTSM.Is_Input__c= TRUE;
                 }   
                 i++;              
                 upsertTSMList.add(insertTSM);
             }
             LIST<Database.UpsertResult> TSMUpsert= DataBase.Upsert(upsertTSMList, Ticket_Session_Mapping__c.Unique_Ids__c, false);         
         
             LIST<Ticket_Session_Mapping__c> deleteTSMList= new LIST<Ticket_Session_Mapping__c>();
             deleteTSMList=[SELECT ID 
                            FROM Ticket_Session_Mapping__c 
                            WHERE Session__c NOT IN : SelectedSessionIds AND
                            Ticket__c =: TT.Id];
                            
             Database.delete(deleteTSMList, FALSE);
             TT.Session_Names__c= SessionNames;
             Database.Update(TT, FALSE);
         }
         TicketPopUp = true;
         AddTicketPopUp = false;
         ticketslist();
    }
    
    public void viewTicket(){
        TableHeading='Ticket Information';
        SelectedTicketMode = false;
        TicketPopUp = false;
        AddTicketPopUp = true;
        SelectedTicketId = ApexPages.currentpage().getparameters().get('TicketIdParam');
        TT = [SELECT Id,TT_Name__c,EV_id__c,TT_Amount__c,TT_Sold__c,Ticket_Image_URL__c,Ticket_Category__c,Ticket_Description__c,TT_TicketType__c,TT_Available__c 
              FROM TicketTypes__c 
              WHERE Id =: SelectedTicketId];
    }
    
    public Pagereference closeticket(){ 
        TicketPopUp = true;
        AddTicketPopUp = false;
        return null;
    }
      
// ---------------------------------------------------------- Tickets method End ---------------------------------------------------------
    public PageReference checkUserId() {
        if (userInfo.getUserType() == 'guest') {
            Pagereference pg = new pagereference('/SA_Signup');
            pg.setredirect(true);
            return pg;
        }else {
            return null;
        }
    }
}