objects/Dummay__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <label>Available Quantity</label>
        <summaryFilterItems>
            <field>Individual_Ticket_Info__c.isCancelled__c</field>
            <operation>equals</operation>
            <value>False</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Individual_Ticket_Info__c.Is_Input__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Individual_Ticket_Info__c.Registration_Info__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Event_Attendee_Mapping__c</fullName>
        <label>Event_Attendee_Mapping</label>
        <referenceTo>Event_Attendee_Mapping__c</referenceTo>
        <relationshipLabel>Registration Info</relationshipLabel>
        <relationshipName>Registration_Info</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Dummays</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Quantity__c</fullName>
        <label>Item Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>Registration Info</relationshipLabel>
        <relationshipName>Registration_Info</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Registration Info</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Dummay Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>AS_HostingCity__c</fullName>
        <label>HostingCity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_EventLogo__c</fullName>
        <label>EventLogo</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>EV_HistingAddr1__c</fullName>
        <label>HistingAddr1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_HostingLocation__c</fullName>
        <label>HostingLocation</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_HostingState__c</fullName>
        <label>HostingState</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_HostingZipcode__c</fullName>
        <label>HostingZipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EV_StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Title__c</fullName>
        <description>Changed By Phani on 09/07/2012</description>
        <label>Title</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sales Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event_Attendee_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event_Attendee_Mapping</relationshipLabel>
        <relationshipName>Event_Attendee_Mapping</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event_Attendee_Mapping</label>
    <nameField>
        <displayFormat>EA{0000000000}</displayFormat>
        <label>EA_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event_Attendee_Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <formula>Item_Quantity__c  -  Sold_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Image__c</fullName>
        <label>Item Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Item_Quantity__c</fullName>
        <label>Item Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_name__c</fullName>
        <label>Item name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <label>Sales Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sold_Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sold Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>isTaxable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isTaxable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>type</label>
        <picklist>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>old Item</label>
    <nameField>
        <displayFormat>item-{0000}</displayFormat>
        <label>iteam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MatchLeads_Days__c.object
<CustomObject>
    <description>It is save no of days Match Leads will be and the timings when the matching will be started.</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>MatchLeads_Days</relationshipLabel>
        <relationshipName>MatchLeads_Days</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MatchLeads_Days</label>
    <nameField>
        <displayFormat>D-{000}</displayFormat>
        <label>MatchLeads_Days Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MatchLeads_Days</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Profile__c.object
<CustomObject>
    <fields>
        <fullName>PR_Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Profile name</label>
    <nameField>
        <displayFormat>PR_{000}</displayFormat>
        <label>profile_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profile cus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Profile_Event__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile_id__c</fullName>
        <label>Profile</label>
        <referenceTo>Profile__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UEP_isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_id__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User_Profile_Event</label>
    <nameField>
        <displayFormat>UPE_{00000000}</displayFormat>
        <label>UPE_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Profile_Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SA_ItemsController.cls
public with sharing class SA_ItemsController {

    public PageReference SaveSalesTax() {
    
        Database.Update(SelectedEvent, FALSE);
        Event__c updateEvent= new Event__c();
        updateEvent= [SELECT ID, Sales_Tax__c FROM Event__c WHERE ID =: SelectedEvent.Id];
        if(updateEvent.Sales_Tax__c != NULL || updateEvent.Sales_Tax__c != 0){
            LIST<Item__c> ItemsList= new LIST<Item__c>();
            LIST<Item__c> updateItemsList= new LIST<Item__c>();                
            ItemsList= [SELECT ID, Sales_Tax__c FROM Item__c WHERE Event__c =: updateEvent.Id AND isTaxable__c =: TRUE];
            if(ItemsList.size() >0){
                for(Item__c item: ItemsList){
                    item.Sales_Tax__c= updateEvent.Sales_Tax__c;
                    updateItemsList.add(item);     
                }
                Database.Update(updateItemsList, FALSE);
           }
        
        } 
        itemsList();   
        ShowSalesTax= FALSE;
        ItemPopUp= TRUE;
        return null;
    }


    public PageReference UpdateSalesTax() {
        ShowSalesTax= TRUE;
        ItemPopUp= FALSE;
        return null;
    }

    
    public Boolean ShowSalesTax{get; set;}
    // Item Variables
    public String SelectedEventId{get;set;}
    public Event__c SelectedEvent{get;set;}
    public LIST<Item__c> Items{get; set;}
    public Item__c Item{get; set;}
    public Boolean ItemPopUp{get;set;}
    public Boolean AddItemPopUp{get;set;}
    public Boolean SelectedItemMode{get;set;}
    public String TableHeading{get;set;}
    public String ItemIdParam{get;set;}
    public Id SelectedItemId{get;set;}
    public transient Blob Logo{get;set;}
    public String LogoName{get;set;}
    public Boolean myDocBool{get; set;}
    public Document mydoc{get;set;}
    public Boolean isPastEvent{get; set;}     
    public Boolean isEventAdminStaffUser{get; set;}   
    
    public SA_ItemsController(){ 
        ShowSalesTax= FALSE; 
        ItemPopUp= true;
        AddItemPopUp= false;
        myDocBool = FALSE;  
        SelectedItemMode = FALSE;
        Cookie counter = ApexPages.currentPage().getCookies().get('counter');
        if(counter !=null){
            SelectedEventId  = counter.getValue(); 
            SelectedEvent= [SELECT  ID, Sales_Tax__c, EV_Title__c, EV_HostingLocation__c, EV_HistingAddr1__c, AS_HostingCity__c, 
                            EV_HostingZipcode__c, EV_EventLogo__c, EV_StartDate__c, EV_EndDate__c, EV_HostingState__c,
                            (SELECT ID FROM MatchLeads_Days__r) 
                            FROM Event__c 
                            Where Id=:SelectedEventId];

            isPastEvent= FALSE;
            if(SelectedEvent.EV_EndDate__c < system.today()){
                isPastEvent= TRUE;                
            }
            List<User_Profile_Event__c> loginUserProfile= new LIST<User_Profile_Event__c>();
            loginUserProfile= [SELECT ID, Profile_id__r.PR_Name__c 
                               FROM User_Profile_Event__c 
                               WHERE EV_id__c =: SelectedEventId AND 
                               UEP_isActive__c =: TRUE AND
                               User_id__c =: UserInfo.getUserId()];
            
            isEventAdminStaffUser= FALSE;                               
            if(loginUserProfile.size() >0){
                for(User_Profile_Event__c prof: loginUserProfile){
                    if(prof.Profile_id__r.PR_Name__c == 'EventAdmin Staff'){
                        isEventAdminStaffUser= TRUE;
                    }
                }
            }  
            itemsList();
        }
        system.debug(' EVENT ID '+SelectedEventId  );
        
        

    }
    
     public PageReference itemsList(){
     try{
        ItemPopUp = true;
        AddItemPopUp= false;
        system.debug('****** '+SelectedEventId);
        ShowItemError= FALSE;               
        Items = [SELECT ID,Name,Cost__c,Description__c,isTaxable__c,Item_Image__c,Item_name__c,
                 Item_Quantity__c,Sales_Tax__c,Sold_Quantity__c,type__c, Available_Quantity__c 
                 FROM Item__c 
                 WHERE Event__c =:SelectedEventId];
                 
       system.debug(Items.size()+' ITEMS LIST '+Items );          
       }catch(exception ex){}
        return null;    
    }
    
    public Boolean ShowItemError{get; set;}
    
    public void deleteItem(){
    
        ShowItemError= FALSE;
       SelectedItemId = ApexPages.currentpage().getparameters().get('ItemIdParam');
       if(SelectedItemId != NULL){
           Item = [SELECT ID,Name,Cost__c,Description__c,isTaxable__c,Item_Image__c,Item_name__c,Item_Quantity__c,
                   Sales_Tax__c,Sold_Quantity__c,type__c, (SELECT ID FROM Registration_Info__r WHERE Event__c =: SelectedEventId
                   AND Event_Attendee_Mapping__c != NULL) 
                   FROM Item__c 
                   WHERE Id =: SelectedItemId];
           LIST<Dummay__c>  RegInfoList= new LIST<Dummay__c>(); 
           RegInfoList=Item.Registration_Info__r;
           if(RegInfoList.size() >0){
            ShowItemError= TRUE;               
           }else{
               database.delete(Item);
               ItemPopUp = true;
               AddItemPopUp= false;
               itemsList();
           }
      
       }        
       
    }

    public void editItem(){
        TableHeading='Edit Item';
        SelectedItemMode = true;
        ShowItemError= FALSE;
        ItemPopUp = false;
        AddItemPopUp= true;

        SelectedItemId = ApexPages.currentpage().getparameters().get('ItemIdParam');
        Item= [SELECT ID,Name,Cost__c,Description__c,isTaxable__c,Item_Image__c,Item_name__c,Item_Quantity__c,
                Sales_Tax__c, Sold_Quantity__c,type__c  
                FROM Item__c 
                WHERE Id =: SelectedItemId];
                
             
    }

    public void addItem(){
        TableHeading='Add Item';
        SelectedItemMode = true;
        ItemPopUp = false;
        AddItemPopUp= true;
        Item = new Item__c();
        Item.Cost__c=0;
    }
    
    public boolean salesTaxError{get; set;}
    
    public void  validateSalesTax(){
        system.debug(Item.isTaxable__c+' ITEM IS TAXABLE '+Item.Sales_Tax__c);
        if((Item.isTaxable__c == TRUE && (Item.Sales_Tax__c == NULL)) || (Item.isTaxable__c == FALSE && Item.Sales_Tax__c != NULL)){
            salesTaxError= TRUE;
        }else{
            salesTaxError= FALSE;
            system.debug(' SALES TAX '+Item.Sales_Tax__c );
           /* if(Item.Sales_Tax__c != NULL){
                Item.Cost__c= Item.Cost__c+ ((Item.Sales_Tax__c*Item.Cost__c)/100);            
              }
            */
            createItem();
        }
    }
    
      
    public void createItem(){
        myDocBool = TRUE;       
        if(Item.isTaxable__c == TRUE){
            Item.Sales_Tax__c= SelectedEvent.Sales_Tax__c;
        }else{
            Item.Sales_Tax__c= 0;
        }
           if(Logo != null && ( LogoName != '' || LogoName != NULL )){
               if(Logo.size()!= null){
                 
               if(Logo.size() < 1048576 ){
                    mydoc = new document();
                    mydoc.body = Logo;
                    mydoc.folderid = '00lF0000001VI7Y';
                    
                    mydoc.IsPublic = True;
                    mydoc.Name = LogoName;
                    DataBase.saveResult docSaveResult = DataBase.insert(mydoc, false);
        
                    String eventold;
        
                    if(docSaveResult.isSuccess()){
                        if(Item.Item_Image__c != null){
                            try{ 
                                eventold = Item.Item_Image__c;          
                                document dd = [SELECT ID, NAME FROM document WHERE id=: eventold];
                                Database.delete(dd);
                             }catch(exception ex){}
                        }
                        String imageURL='';
                        string urlbase =URL.getSalesforceBaseUrl().getHost();
                        string orgId = UserInfo.getOrganizationId();
                    
                        imageURL= 'https://'+urlbase+'/servlet/servlet.ImageServer?oid='+orgId+'&id='+docSaveResult.getId();
                        Item.Item_Image__c = docSaveResult.getId();
                    }
                    else{
                        myDocBool = FALSE;
                        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO, String.valueOf(docSaveResult.getErrors()))); 
                    } 
                }
                else{
                    myDocBool = FALSE; 
                }
               }            
         }
         Item.Event__c = SelectedEventId;   
         system.debug('&&&& '+Item);
         Database.UpsertResult EventupsertResult = DataBase.Upsert(Item, false);
         
         
         ItemPopUp = true;
         AddItemPopUp= false;
         itemsList();
    }
    
    public void viewItem(){
        TableHeading='Item Information';
        SelectedItemMode = false;
        ItemPopUp = false;
        AddItemPopUp= true;
        SelectedItemId = ApexPages.currentpage().getparameters().get('ItemIdParam');
        Item = [SELECT ID,Name,Cost__c,Description__c,isTaxable__c,Item_Image__c,Item_name__c,Item_Quantity__c,Sales_Tax__c,Sold_Quantity__c,type__c 
                FROM Item__c 
                WHERE Id =: SelectedItemId];
    }
    
    public void closeItem(){
        ItemPopUp = true;
        ShowSalesTax= FALSE;
        AddItemPopUp= false;
        itemslist();
    }
    
    
    public PageReference checkUserId() {
        if (userInfo.getUserType() == 'guest') {
            Pagereference pg = new pagereference('/SA_Signup');
            pg.setredirect(true);
            return pg;
        }else {
            return null;
        }
    }
    
}