objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scan_Id__c</fullName>
        <label>Scan Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BLN_Scanids.cls
public with sharing class BLN_Scanids {
  // This method will return all existing scanids belongs to event
  public Static SET<integer> existingTcScanIds(String eveId) { 
    SET<integer> uniqNums = new  SET<integer>();
    for (Ticket__c tc : [SELECT Id, Scan_Id__c from Ticket__c where Event__c = :eveId]) {
      if ('' != tc.Scan_Id__c) {
        try {
          uniqNums.add(integer.valueOf(tc.Scan_Id__c));
        } catch (exception ed) {}
      }
    }
    return uniqNums;
  }
}