objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GN_User__c.object
<CustomObject>
    <description>The address fields belong to user home address
This should be the only link between gnuser and salesforce user. salesforce user table should not be accessible any where else in db except this table.</description>
    <label>BLN GN User</label>
    <nameField>
        <displayFormat>GNU-{000000}</displayFormat>
        <label>GN User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN GN Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Paid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Not Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reg_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Defaullt_Label__c</fullName>
        <label>Defaullt Label</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Included__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Reg_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Label_Name__c</fullName>
        <label>Label Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Display Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Reg Setting</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Reg Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Reg Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>tkt_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Tickets</relationshipLabel>
        <relationshipName>BLN_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tkt_profile__c.object
<CustomObject>
    <fields>
        <fullName>BLN_GN_User__c</fullName>
        <label>BLN GN User</label>
        <referenceTo>GN_User__c</referenceTo>
        <relationshipLabel>BLN TKT profile</relationshipLabel>
        <relationshipName>BLN_TKT_profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN TKT profile</label>
    <nameField>
        <displayFormat>TP-{0000000}</displayFormat>
        <label>tkt profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN TKT profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_ASC_MobileAppSettings.cls
@RestResource(urlMapping='/BLN_ASC_MobileAppSettings/*')
/***********************************************************************************************
*   Service Name : BLN_ASC_MobileAppSettings
*   Date            : 25/06/2015
*   Author          : Sai 
*   Purpose         : This class is for getting visibility for Mobile App Settings
************************************************************************************************/
  

    global with sharing class BLN_ASC_MobileAppSettings{
    
    @HttpPost  
    global static MainContainer1 doPost(string EventID,string Userid){
        RestRequest req = RestContext.request;  
      if(EventID==null){
        EventID=req.params.get('Event_Id');
        }
        if(Userid==null)
        Userid=req.params.get('User_id');
        
        boolean Seminarsflag=false;
        boolean Exhibitorflag=false;
        boolean Sponsorsflag=false;
        boolean Speakersflag=false;
        BLN_Reg_Settings_DAO regDAO;
        BLN_Ticket_DAO ticDAO;
        MainContainer1 mc=new MainContainer1();
             
        RestResponse response = RestContext.response;
        
        bln_app_settings_BAL appcon=new bln_app_settings_BAL();
        appcon.checkticdetails(EventID);
        Seminarsflag= appcon.Seminarsflag;
        Exhibitorflag= appcon.Exhibitorflag;
        Sponsorsflag= appcon.Sponsorsflag;
        Speakersflag= appcon.Speakersflag;

        
         regDAO = new BLN_Reg_Settings_DAO();
         List<Reg_Setting__c> Reg=  regDAO.getregsetlist(EventID);
         
         List<Container> container=new List<Container>();
         
         boolean leadbool=false;
         leadbool=getleadinclude(EventID,Userid);
         
         for(Reg_Setting__c tc:Reg)
         {
          Container cnt=new Container();
         
          if((tc.Defaullt_Label__c!='Speakers')&& (tc.Defaullt_Label__c!='Sponsors' ) && (tc.Defaullt_Label__c!='Exhibitors')&& (tc.Defaullt_Label__c!='Seminars' )){
          cnt.eventid = EventID;
          cnt.id = tc.id;
          cnt.ColumnName=tc.Defaullt_Label__c;
          cnt.Columnlabel=tc.Label_Name__c==null?'':tc.Label_Name__c;
          if(tc.Defaullt_Label__c=='Lead Retrieval' && leadbool==true){
              cnt.Include=tc.Included__c;
          }else if(tc.Defaullt_Label__c=='Lead Retrieval' && leadbool==false){
              cnt.Include=leadbool;
          }else{
              cnt.Include=tc.Included__c;
          }
          
          container.add(cnt); 
         }else if((tc.Defaullt_Label__c=='Speakers' && Speakersflag==true) || (tc.Defaullt_Label__c=='Sponsors' && Sponsorsflag==true) || (tc.Defaullt_Label__c=='Exhibitors' && Exhibitorflag==true) || (tc.Defaullt_Label__c=='Seminars' && Seminarsflag==true))
          {
          cnt.eventid = EventID;
          cnt.id = tc.id;
          cnt.ColumnName=tc.Defaullt_Label__c;
          cnt.Columnlabel=tc.Label_Name__c==null?'':tc.Label_Name__c;
          cnt.Include=tc.Included__c;
          
          container.add(cnt); 
         }
         }
          mc.details=new List<Container>();
         mc.details=container;
        return mc;
      }
      
      
      
      global Class Container
      {    public string EventID{get;set;}
           public String ColumnName{get;set;}
           public String Columnlabel{get;set;}
           public Boolean Include{get;set;}
           public string id{get;set;}
      }
      
  global class MainContainer1
      {
         List<Container> details{get;set;}

      }
      
      global static boolean getleadinclude(string EventID,string Userid){
          LIST<ticket__c> tlist=new LIST<ticket__C>();
          boolean leadbool=false;
          tlist=[select Item_Pool__r.Item_Type__r.Name,Item_Type__r.Name from ticket__c where Order__r.Order_Status__c IN ('Partially Paid','Fully Paid','Check Not Received') AND Ticket_Status__c!='Cancelled' and tkt_profile__r.BLN_GN_User__r.User__c=:Userid and Event__c = :EventID];
         
          for(ticket__c t:tlist){
              if(t.Item_Pool__r.Item_Type__r.Name == 'Lead Retrieval'||t.Item_Type__r.Name == 'Lead Retrieval')
                      leadbool=true;
          }
          return leadbool;
      }
      
      }