objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Item_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Paid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Not Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <label>Item Type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket_Status__c</fullName>
        <label>Ticket Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BLN_app_settings_BAL.cls
public with sharing class BLN_app_settings_BAL{
     public BLN_Ticket_DAO ticDAO{get;set;}
    public boolean MMBuyerflag{get;set;}
    public boolean MMSellerflag{get;set;}
    public boolean LeadRetrivalflag{get;set;}
    public boolean FloorMapflag{get;set;}
    public boolean Seminarsflag{get;set;}
    public boolean Exhibitorflag{get;set;}
    public boolean Sponsorsflag{get;set;}
    public boolean Speakersflag{get;set;}
    public boolean Scanattendeeflag{get;set;}
    
    public MAP<String,Boolean> checkticdetails(string eventid){
    //ticDAO=new BLN_Ticket_DAO();
     MAP<String,Boolean> mapLabelWithinc = new MAP<String,Boolean>(); 
      BLN_ItemPool_DAO ticDAO = new BLN_ItemPool_DAO();
     string selectedeventid = eventid;
     //LIST<Ticket__c> tic = ticDAO.gettlist(selectedeventid);
     //[SELECT Item_Pool__r.Item_Type__r.Name,Item_Type__r.Name,Order__r.Order_Status__c FROM Ticket__c WHERE Event__c = :selectedeventid AND Ticket_Status__c!='Cancelled'];
     LIST<Item_Pool__c> tic = ticDAO.getPoolsBlongthatevent(selectedeventid);

      MMBuyerflag = false;
      MMSellerflag = false;
      LeadRetrivalflag = false;
      FloorMapflag = false; 
      Seminarsflag = false;
      Exhibitorflag= false;
      Sponsorsflag=false;
      Speakersflag=false;
      Scanattendeeflag=false;
      
     //mapLabelWithinc.put(); 
     mapLabelWithinc.put('MatchLeads',MMBuyerflag);
     mapLabelWithinc.put('Lead Retrieval',LeadRetrivalflag);
     mapLabelWithinc.put('Floor Map',FloorMapflag);
     mapLabelWithinc.put('Seminars',Seminarsflag);
     mapLabelWithinc.put('Exhibitors',Exhibitorflag);
     mapLabelWithinc.put('Sponsors',Sponsorsflag); 
     mapLabelWithinc.put('Speakers',Speakersflag); 
     mapLabelWithinc.put('Scan Attendee',Scanattendeeflag);
     
     for(Item_Pool__c t:tic){
      
      if((t.Item_Type__r.Name == 'Scan Attendee') ){
           MMBuyerflag = true;
           Scanattendeeflag =true;
           mapLabelWithinc.put('Scan Attendee',Scanattendeeflag);
       }
     
       if((t.Item_Type__r.Name == 'MatchLeads Buyer') ){
           MMBuyerflag = true;
           mapLabelWithinc.put('MatchLeads',MMBuyerflag);
       }
       
       if((t.Item_Type__r.Name == 'MatchLeads Seller')){
           MMSellerflag = true; 
           mapLabelWithinc.put('MatchLeads',MMSellerflag);
       }
       
       if((t.Item_Type__r.Name == 'Lead Retrieval')){
           LeadRetrivalflag = true; 
           mapLabelWithinc.put('Lead Retrieval',LeadRetrivalflag);
       }
       
       if((t.Item_Type__r.Name =='Booth Map')){
           FloorMapflag = true; 
           mapLabelWithinc.put('Floor Map',FloorMapflag);
       }
           if(t.Item_Type__r.Name == 'Seminars' ){
           Seminarsflag = true;
            mapLabelWithinc.put('Seminars',Seminarsflag);
           }
           if(t.Item_Type__r.Name == 'Booths /Tables'){
               Exhibitorflag= true;
              mapLabelWithinc.put('Exhibitors',Exhibitorflag); 
           }
           if(t.Item_Type__r.Name == 'Sponsorship' ){
               Sponsorsflag=true;
               mapLabelWithinc.put('Sponsors',Sponsorsflag); 
           }
           if(t.Item_Type__r.Name == 'Speaker'){
               Speakersflag=true;
              mapLabelWithinc.put('Speakers',Speakersflag); 
           }
       
       system.debug('aaaaaaaaaaaaa'+Sponsorsflag);
     
     }
     
     return mapLabelWithinc;
    
    }

}