objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Profile_Event__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>User_Profile_Event</relationshipLabel>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_id__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Profile_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User_Profile_Event</label>
    <nameField>
        <displayFormat>UPE_{00000000}</displayFormat>
        <label>UPE_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User_Profile_Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/deactivateusersmorethan3.cls
global class deactivateusersmorethan3 implements Schedulable{
   global void execute(SchedulableContext sc) {
     date d = System.today() -30;
 List<user> users = new List<user>();
 List<Event__c> events = new List<Event__c>();
 events =[select id,createdDate from event__c where createdDate <:d];
 set<id> userids = new set<id>();
 
 for(User_Profile_Event__c UPE :[select User_id__r.id,id from User_Profile_Event__c where EV_id__c NOT IN :events]){
  userids.add(UPE.User_id__r.id); 
 }
 
 
 for (user u:[select id from user where id In :userids and profile.Name!='Event Admin' and profile.Name!='System Administrator' and isActive=true]){
  u.isActive =false;
 users.add(u);
 }

 dataBase.update(users,false);

   }
}