objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Attendee_Types__c</fullName>
        <defaultValue>&quot;Volunteer ; Small scale business; Corporate; MBE&quot;</defaultValue>
        <description>type of an attendee .</description>
        <label>Attendee Types</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EV_EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_EndTime__c</fullName>
        <label>EndTime</label>
        <picklist>
            <picklistValues>
                <fullName>12:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:05 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:10 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:20 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:25 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:35 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:40 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:50 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:55 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:05 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:10 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:20 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:25 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:35 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:40 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:50 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:55 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:05 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:10 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:20 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:25 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00 AM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EV_HostingTimeZone__c</fullName>
        <label>HostingTimeZone</label>
        <picklist>
            <picklistValues>
                <fullName>Eastern Time(USA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Time(USA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mountain Time(USA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific Time(USA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indian Standard Time(IST)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central European Time Zone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EV_StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Title__c</fullName>
        <description>Changed By Phani on 09/07/2012</description>
        <label>Title</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>StartTime</label>
        <picklist>
            <picklistValues>
                <fullName>12:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:05 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:10 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:20 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:25 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:35 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:40 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:50 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:55 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:05 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:10 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:20 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:25 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:35 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:40 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:45 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:50 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:55 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:05 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:10 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:15 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:20 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:25 AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00 AM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_BL_Registration_LinksCon.cls
@isTest
public class Test_BL_Registration_LinksCon{

 static testMethod void testRest(){
    Event__c eve = new Event__c(EV_Title__c='Global Event',EV_HostingTimeZone__c='Eastern Time(USA)',
       Attendee_Types__c ='Attendee;Exhibitor;Sponsor;Exhibitor Staff',
       EV_EndDate__c = Date.Parse('01/18/2014'),
       EV_StartDate__c = Date.Parse('01/18/2014'),
       EV_EndTime__c='09:00 AM',
       StartTime__c='11:00 AM');
       insert eve;
      BL_Registration_LinksCon reg = new BL_Registration_LinksCon(); 
     
 }
 }