objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>EV_Title__c</fullName>
        <description>Changed By Phani on 09/07/2012</description>
        <label>Title</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Pay_Pal_Account__c.object
<CustomObject>
    <fields>
        <fullName>Email_Id__c</fullName>
        <label>Email Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Pay Pal Account</relationshipLabel>
        <relationshipName>Pay_Pal_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fee_Payer__c</fullName>
        <label>Fee Payer</label>
        <picklist>
            <controllingField>Payment_Type__c</controllingField>
            <picklistValues>
                <fullName>EACHRECEIVER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRIMARYRECEIVER</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SENDER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SECONDARYONLY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Parallel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chained</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Simple</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Pay Pal Account</label>
    <nameField>
        <displayFormat>Pay-{0000}</displayFormat>
        <label>Pay Pal Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Pal Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TicketTypes__c.object
<CustomObject>
    <fields>
        <fullName>EV_id__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>TicketTypes</relationshipLabel>
        <relationshipName>TicketTypes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Tickets_per_Order__c</fullName>
        <label>Max Tickets per Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section_Name__c</fullName>
        <label>Section Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TT_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TT_Available__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TT_Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TT_TicketType__c</fullName>
        <label>TicketType</label>
        <picklist>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ticket_Category__c</fullName>
        <label>Ticket Category</label>
        <picklist>
            <picklistValues>
                <fullName>Attendee</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non – Attendee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <label>User Type</label>
        <picklist>
            <picklistValues>
                <fullName>Non-Member/Guest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSDC Member Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSDC Certified MBE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TicketTypes</label>
    <nameField>
        <displayFormat>TT_{0000000}</displayFormat>
        <label>TT_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TicketTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_NyNJNMSDCRegistrationPageCon.cls
@istest
public class Test_NyNJNMSDCRegistrationPageCon
{

  static testmethod void Testmethod_BL_BoothPersonnelsCon()
  {
  
  Event__c eve = new Event__c(EV_Title__c='TestEvent');
  insert eve;
  
  TicketTypes__c tic = new TicketTypes__c(EV_id__c=eve.id,  TT_Name__c='TestEvent',TT_TicketType__c='Paid',Ticket_Category__c='Attendee',TT_Available__c=20,User_Type__c='MSDC Member Corporation',Max_Tickets_per_Order__c=5,TT_Amount__c=500,Section_Name__c ='ONE DAY CONFERENCE ATTENDEE');
  insert tic;
  
  TicketTypes__c tic2 = new TicketTypes__c(EV_id__c=eve.id,  TT_Name__c='Diamond',TT_TicketType__c='Paid',Ticket_Category__c='Attendee',TT_Available__c=20,User_Type__c='MSDC Member Corporation',Max_Tickets_per_Order__c=5,TT_Amount__c=500);
  insert tic2;
  
  
   TicketTypes__c tic3 = new TicketTypes__c(EV_id__c=eve.id,  TT_Name__c='Platinum',TT_TicketType__c='Paid',Ticket_Category__c='Attendee',TT_Available__c=20,User_Type__c='MSDC Member Corporation',Max_Tickets_per_Order__c=5,TT_Amount__c=500);
  insert tic3;
  
  
   TicketTypes__c tic4 = new TicketTypes__c(EV_id__c=eve.id,  TT_Name__c='Gold',TT_TicketType__c='Paid',Ticket_Category__c='Attendee',TT_Available__c=20,User_Type__c='MSDC Member Corporation',Max_Tickets_per_Order__c=5,TT_Amount__c=500);
  insert tic4;
  
  
   TicketTypes__c tic5 = new TicketTypes__c(EV_id__c=eve.id,  TT_Name__c='Tuesday Breakfast',TT_TicketType__c='Paid',Ticket_Category__c='Attendee',TT_Available__c=20,User_Type__c='MSDC Member Corporation',Max_Tickets_per_Order__c=5,TT_Amount__c=500);
  insert tic5;
  
  
   TicketTypes__c tic6 = new TicketTypes__c(EV_id__c=eve.id,  TT_Name__c='Tuesday Lunch',TT_TicketType__c='Paid',Ticket_Category__c='Attendee',TT_Available__c=20,User_Type__c='MSDC Member Corporation',Max_Tickets_per_Order__c=5,TT_Amount__c=500);
  insert tic6;
  
  
   TicketTypes__c tic7 = new TicketTypes__c(EV_id__c=eve.id,  TT_Name__c='Shining Star Reception',TT_TicketType__c='Paid',Ticket_Category__c='Attendee',TT_Available__c=20,User_Type__c='MSDC Member Corporation',Max_Tickets_per_Order__c=5,TT_Amount__c=500);
  insert tic7;
  
     TicketTypes__c tic8 = new TicketTypes__c(EV_id__c=eve.id,  TT_Name__c='Wednesday Breakfast',TT_TicketType__c='Paid',Ticket_Category__c='Attendee',TT_Available__c=20,User_Type__c='MSDC Member Corporation',Max_Tickets_per_Order__c=5,TT_Amount__c=500);
  insert tic8;
    
     TicketTypes__c tic9 = new TicketTypes__c(EV_id__c=eve.id,  TT_Name__c='Wednesday Lunch',TT_TicketType__c='Paid',Ticket_Category__c='Attendee',TT_Available__c=20,User_Type__c='MSDC Member Corporation',Max_Tickets_per_Order__c=5,TT_Amount__c=500);
  insert tic9;
    
     TicketTypes__c tic10 = new TicketTypes__c(EV_id__c=eve.id,  TT_Name__c='Booth at Expo',TT_TicketType__c='Paid',Ticket_Category__c='Attendee',TT_Available__c=20,User_Type__c='MSDC Member Corporation',Max_Tickets_per_Order__c=5,TT_Amount__c=500);
  insert tic10;
  
  
   TicketTypes__c tic11 = new TicketTypes__c(EV_id__c=eve.id,  TT_Name__c='Additional Booth',TT_TicketType__c='Paid',Ticket_Category__c='Attendee',TT_Available__c=20,User_Type__c='MSDC Member Corporation',Max_Tickets_per_Order__c=5,TT_Amount__c=500);
  insert tic11;
  
  Pay_Pal_Account__c pAcc = new Pay_Pal_Account__c(Email_Id__c='test@globalnest.com',Event__c=eve.id,Payment_Type__c='Chained',Fee_Payer__c='EACHRECEIVER');
  insert pAcc ;
   List<selectOption> opt= new List<selectOption>();
  
  
    NyNJNMSDCRegistrationPageCon nynjcon = new NyNJNMSDCRegistrationPageCon();
    PageReference pg = Page.BL_Registration;
    Test.setCurrentPage(pg); 
     ApexPages.currentPage().getParameters().put('id', eve.id);
     nynjcon.getItems();
     ApexPages.currentPage().getParameters().put('pid', '');
     nynjcon.cancelTickets();
     nynjcon.selectedEvent =eve.id;
      nynjcon.userType='MSDC Member Corporation';
      nynjcon.DisplayTab2Values(); 
      nynjcon.previous1(); 
      nynjcon.previous2(); 
      nynjcon.previous3(); 
      nynjcon.enabletab4();
      nynjcon.enabletab3();
      nynjcon.enabletab2();
    
      NyNJNMSDCRegistrationPageCon.innerClass  inc = new NyNJNMSDCRegistrationPageCon.innerClass(tic,opt);
      inc.tt =tic;
      inc.quantity =1;
      nynjcon.inn.add(inc);
      nynjcon.enabletab1();
      nynjcon.onchangeAct();
      
        nynjcon.getistab0disabled();
        nynjcon.getistab1disabled();
        nynjcon.getistab2disabled();
        nynjcon.getistab3disabled();
        nynjcon.getistab4disabled();
        nynjcon.getselectedtab();
        nynjcon.paymenttypeIteam='Invoice'; 
        nynjcon.displaycheckNo();
        
        nynjcon.invoiceEmail ='test@gmail.com';
         nynjcon.Pay();
        nynjcon.testdum(); 
  }
 }