objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Event_Price__c.object
<CustomObject>
    <description>Resource Types for the event	- Default event zero has all the default values
Admissions Ticket 	$0.75		- as soon as ticket is bought
Seats Ticket 		$1.00
Seminars 		$1.00
MatchLeads Buyers 	$50.00
MatchLeads Sellers 	$15.00
Booth 		$0.50
Items 		$0.25
Package		$0.00
LeadScan 	$50.00 / booth	 - as soon as ticket is bought
Scan Attendee $299.00 /badge	 - as soon as service is added
Kiosk 	  $499.00  /event	 - as soon as service is added
BoothMap       $499.00  /event	 - as soon as service is added</description>
    <fields>
        <fullName>Active_Flag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active_Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BL_Fee_Amount__c</fullName>
        <label>BL Fee Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Event_Price</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_type__c</fullName>
        <label>Item type</label>
        <referenceTo>Item_Type__c</referenceTo>
        <relationshipName>Event_Price</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Event Price</label>
    <nameField>
        <displayFormat>EP-{000000}</displayFormat>
        <label>Event Price</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Event Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Type__c.object
<CustomObject>
    <description>Resource Types for the event== Per Ticket Chargeable 
Items ==Admissions 
Ticket
Seats 
Seminars
MatchLeads Buyers
MatchLeads Sellers
BoothPackage - Only package items can be grouped to have child items under them. (Wether is item is package. If the item is package, then individual items with count will exist in the package table. To this package you can add only  I - Individual Item pool - A - Addon Item pool )== Per Event Chargeable Items ==AttendeeScanKioskBooth MapItems== Add-on Items - only can be added to package (can not be put in item table but chargeable per ticket if necessary) ==Add-Ons (optional/non-optional)Staff AdmissionAdvertisementLeadScanBreakfastLunchDinnerCocktailWifiElectric</description>
    <fields>
        <fullName>Add_On__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Add On</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BL_Fee_Amt_per_res__c</fullName>
        <label>BL Fee Amt per res</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BL_Fee_Pct_per_res__c</fullName>
        <label>BL Fee Pct per res</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Badge_Label__c</fullName>
        <label>Badge Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Option_Desc__c</fullName>
        <label>Event Option Desc</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Option_Sort_Order__c</fullName>
        <defaultValue>0</defaultValue>
        <description>any record with sort order 0 or less does not show.</description>
        <label>Event Option Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Options_Image_URL__c</fullName>
        <label>Event Options Image URL</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Seq__c</fullName>
        <description>If this flag is set on an item pool tickets are not created in the ticket table however a new row is inserted everytime a ticket is bought.

Applicable for item_type = &quot;Addmissions&quot;

Also there is no tag on the ticket.</description>
        <label>Invoice Seq</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Item_Type_Number__c</fullName>
        <label>Item Type Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unlimited__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this flag is set on an item pool tickets are not created in the ticket table however a new row is inserted everytime a ticket is bought.

Applicable for item_type = &quot;Addmissions&quot;

Also there is no tag on the ticket.</description>
        <label>Unlimited</label>
        <type>Checkbox</type>
    </fields>
    <label>BLN Item Type</label>
    <nameField>
        <label>Item Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN Item Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order__c.object
<CustomObject>
    <label>BLN Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_ItemType_DAO.cls
public with sharing class BLN_ItemType_DAO {

/***********************************************************************************************
*   Controller Name : BLN_ItemType_DAO
*   Date            : 19/05/2014
*   Author          : Naga Mallikarjuna Rao B
*   Purpose         : This class is for Item Types Business Application Layer
*   Change History  : 19/05/2014 
*       Date                 Programmer                     Reason
*   --------------      -------------------           -------------------------
*   19/05/2014          Naga Mallikarjuna Rao B           To Create Page
**************************************************************************************************/
     
     
     //This methode gives all the item types, if user pass empty list as parameaters it will send all Item Types.
     // If User pass any parameater it will skip those list and send remaining Item Types.
    public static LIST<Item_Type__c> AllItemTypes(LIST<String> unUsedItemTypes){
        
        LIST<Item_Type__c> itemTypes = new LIST<Item_Type__c>();
        
        if(unUsedItemTypes.size() >= 1 ){
            itemTypes = [SELECT ID, NAME, Add_On__c, BL_Fee_Amt_per_res__c, BL_Fee_Pct_per_res__c, Invoice_Seq__c,Item_Type_Number__c, Unlimited__c , 
                            Event_Option_Desc__c , Event_Option_Sort_Order__c, Event_Options_Image_URL__c,  Badge_Label__c
                            FROM Item_Type__c WHERE Item_Type_Number__c NOT IN: unUsedItemTypes ORDER BY Event_Option_Sort_Order__c];
        }else{
            itemTypes = [SELECT ID, NAME, Add_On__c, BL_Fee_Amt_per_res__c, BL_Fee_Pct_per_res__c, Invoice_Seq__c,Item_Type_Number__c, Unlimited__c, 
                            Event_Option_Desc__c , Event_Option_Sort_Order__c, Event_Options_Image_URL__c,  Badge_Label__c
                            FROM Item_Type__c ORDER BY Event_Option_Sort_Order__c];
        }
         
        return itemTypes;
    }
    
     //This methode gives Event Option item types, if user pass empty list as parameaters it will give all values greater than 1 in (Event_Option_Sort_Order__c).
     // If User pass any parameater it will gives that list of Item Types.
    public static LIST<Event_Price__c> eventOptionItemTypes(LIST<String> usedItemTypes,String eventid){
        
        LIST<Event_Price__c> itemTypes = new LIST<Event_Price__c>();
        
        if(usedItemTypes.size() >= 1 ){
            itemTypes = [SELECT ID, NAME,Event__c,Active_Flag__c,BL_Fee_Amount__c, Item_type__r.Add_On__c,Item_type__r.Event_Option_Sort_Order__c,Item_type__r.Event_Options_Image_URL__c,
                          Item_type__r.Id,Item_type__r.Event_Option_Desc__c,Item_type__r.Item_Type_Number__c
                            FROM Event_Price__c WHERE Item_type__r.Item_Type_Number__c IN: usedItemTypes AND Item_type__r.Event_Option_Sort_Order__c >= 1 and Active_Flag__c=true and Event__c=:eventid ORDER BY Item_type__r.Order__c];
        }else{
            itemTypes = [SELECT ID, NAME,Event__c,Active_Flag__c,BL_Fee_Amount__c, Item_type__r.Add_On__c,Item_type__r.Event_Option_Sort_Order__c,Item_type__r.Event_Options_Image_URL__c,
                          Item_type__r.Id,Item_type__r.Event_Option_Desc__c,Item_type__r.Item_Type_Number__c
                            FROM Event_Price__c WHERE Item_type__r.Event_Option_Sort_Order__c >= 1 and Active_Flag__c=true and Event__c=:eventid ORDER BY Item_type__r.Order__c];
   }
         
        return itemTypes;
        
    }  
    
    // This is For to get Admission Ticket Type from DataBase
    public static Item_Type__c AdmissionItemTypes( String  adminItemTypes){
        
         Item_Type__c  itemTypes = new  Item_Type__c ();
        
        if(adminItemTypes != null && adminItemTypes != '' ){
            itemTypes = [SELECT ID, NAME, Add_On__c, BL_Fee_Amt_per_res__c, BL_Fee_Pct_per_res__c, Invoice_Seq__c,Item_Type_Number__c, Unlimited__c ,Badge_Label__c
                            FROM Item_Type__c WHERE Item_Type_Number__c =: adminItemTypes];
            return itemTypes;
        } 
         
        return null;
    }
    
    // This is For to get Package Ticket Type from DataBase
    public static Item_Type__c PackageItemTypes( String  PackageItemTypes){
        
         Item_Type__c itemTypes = new  Item_Type__c ();
        
        if(PackageItemTypes != null && PackageItemTypes != '' ){
            itemTypes = [SELECT ID, NAME, Add_On__c, BL_Fee_Amt_per_res__c, BL_Fee_Pct_per_res__c, Invoice_Seq__c,Item_Type_Number__c, Unlimited__c , Badge_Label__c
                            FROM Item_Type__c WHERE Item_Type_Number__c =: PackageItemTypes];
            return itemTypes;
        } 
         
        return null;
    }
    
    
    public static LIST<Item_Type__c> itemTypesforTickets(SET<String> eventOptionsItemTypes){
        
        LIST<Item_Type__c> itemTypes = new LIST<Item_Type__c>();
        
        itemTypes = [SELECT ID, NAME, Add_On__c, BL_Fee_Amt_per_res__c, BL_Fee_Pct_per_res__c, Invoice_Seq__c,Item_Type_Number__c, Unlimited__c, 
                            Event_Option_Desc__c , Event_Option_Sort_Order__c, Event_Options_Image_URL__c
                            FROM Item_Type__c WHERE Item_Type_Number__c =: eventOptionsItemTypes OR  Add_On__c = TRUE ORDER BY Order__c];
        //
        return itemTypes;
        
    }
     
     public static LIST<Event_Price__c> itemTypesforIndividualTickets(SET<String> eventOptionsItemTypes,String eventid){
        
        LIST<Event_Price__c> itemTypes = new LIST<Event_Price__c>();
        
        /*itemTypes = [SELECT ID, NAME, Add_On__c, BL_Fee_Amt_per_res__c, BL_Fee_Pct_per_res__c, Invoice_Seq__c,Item_Type_Number__c, Unlimited__c, 
                            Event_Option_Desc__c , Event_Option_Sort_Order__c, Event_Options_Image_URL__c
                            FROM Item_Type__c WHERE Item_Type_Number__c =: eventOptionsItemTypes  ORDER BY Order__c];*/
        itemTypes = [SELECT ID, NAME,Event__c,Active_Flag__c,BL_Fee_Amount__c, Item_type__r.Add_On__c,Item_type__r.Event_Option_Sort_Order__c,Item_type__r.Event_Options_Image_URL__c,
                          Item_type__r.Id,Item_type__r.Name,Item_type__r.Event_Option_Desc__c,Item_type__r.Item_Type_Number__c
                            FROM Event_Price__c WHERE Item_type__r.Item_Type_Number__c IN: eventOptionsItemTypes and Active_Flag__c=true and Event__c=:eventid ORDER BY Item_type__r.Order__c];                    
        //
        return itemTypes;
        
    }
    
    public Item_Type__c getItemtype(String typeName){
       return [SELECT id,Name from Item_Type__c Where Name=:typeName limit 1];
    }
    

}