objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>EV_Title__c</fullName>
        <description>Changed By Phani on 09/07/2012</description>
        <label>Title</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>QR_EVT_{dd}{yy}_{0000000}</displayFormat>
        <label>EV_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_BL_Special_Needs_Expos_mainPageCon.cls
@isTest
private class Test_BL_Special_Needs_Expos_mainPageCon {

    static testMethod void myUnitTest() {
      Event__c eve = new Event__c(EV_Title__c='TestEvent');
      insert eve;
  
   PageReference pg = Page.BL_Special_Needs_Expos_mainpage;
   Test.setCurrentPage(pg); 
   ApexPages.currentPage().getParameters().put('id', eve.id);
  BL_Special_Needs_Expos_mainPageCon BL_spcon = new BL_Special_Needs_Expos_mainPageCon();
  
  
    }
}