objects/Item_Pool__c.object
<CustomObject>
    <description>itempool table record, creates a pool of tickets in the ticket table. These tickets of similar kind wthin a class of item type. These pools of a single ticket class can be sold for different prices at different times e.g. Early bird,Regular, Late etc. The pricing is available in item table.for parent_addon_id 
refer to http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/</description>
    <fields>
        <fullName>Item_Pool_Name__c</fullName>
        <label>Item Pool Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BLN Item Pool</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Item Pool Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item Pools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Item_Question__c.object
<CustomObject>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Item_Question</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Level__c</fullName>
        <label>Question Level</label>
        <picklist>
            <picklistValues>
                <fullName>Ticket Level</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Event Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Retrieval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Item_Question</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Item Question</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>Item_Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Item_Question</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Question__c.object
<CustomObject>
    <label>BLN Question</label>
    <nameField>
        <displayFormat>QUE-{000000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Item_Pool__c</fullName>
        <label>Item Pool</label>
        <referenceTo>Item_Pool__c</referenceTo>
        <relationshipName>Tickets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tkt_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Tickets</relationshipLabel>
        <relationshipName>BLN_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN Ticket</label>
    <nameField>
        <displayFormat>TKT-{000000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tkt_profile__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <label>BLN TKT profile</label>
    <nameField>
        <displayFormat>TP-{0000000}</displayFormat>
        <label>tkt profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN TKT profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Item_Question__c</fullName>
        <label>Item Question</label>
        <referenceTo>Item_Question__c</referenceTo>
        <relationshipName>User_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticket__c</fullName>
        <label>Ticket</label>
        <referenceTo>Ticket__c</referenceTo>
        <relationshipName>User_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UAnswer_Text_Update__c</fullName>
        <label>UAnswer Text Update</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>BLN User Answer</label>
    <nameField>
        <displayFormat>UANS-{000000}</displayFormat>
        <label>User Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN User Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_ExportSurveyByAttendeeBatch.cls
global without sharing class BLN_ExportSurveyByAttendeeBatch implements Database.batchable <sObject> , Database.Stateful {
    global final String Query;
    global List <Ticket__c> ticCountList{get;set;}
    global string selectedEvent{get;set;}

    private static final Integer SCOPE_SIZE = 100;
    public BLN_ExportSurveyByAttendeeBatch(String q, string selEvent) {
        Query=q;
        //ticCountList= new list<ticket__c>();
        //ticCountList=ticCountList1;
        selectedEvent=selEvent;

    }
    global Iterable < sObject > start(Database.batchableContext batchableContext) {
        system.debug('query' + query);
        return Database.getQueryLocator(query);

    }
    global void execute(Database.BatchableContext batchableContext, List < sObject > scope) {

        String temp1 = 'Attendee Name,Email,Mobile No.,Level,Ticket Name,Question,Answer'; 
        temp1+='\n'; 
        list<user_answer__c> ulist=new list<user_answer__c>();
         BLN_SurveyQuestionsReportCon_BAL  surveyQuestionBAL= new BLN_SurveyQuestionsReportCon_BAL();
         ulist=surveyQuestionBAL.gnUsersForSurveyTemp(selectedEvent,scope);   
       for(user_answer__c attendee: ulist){ 
            temp1+='"'+attendee.ticket__r.tkt_profile__r.First_Name__c+' '+attendee.ticket__r.tkt_profile__r.Last_Name__c+'",';
            temp1+='"'+attendee.ticket__r.tkt_profile__r.Email__c+'",';
            temp1+='"'+attendee.ticket__r.tkt_profile__r.Mobile__c+'",';
            temp1+='"'+attendee.item_question__r.question_level__c+'",';
            if(attendee.item_question__r.question_level__c=='Ticket Level'){
                temp1+='"'+attendee.ticket__r.item_pool__r.item_pool_name__c+'",'; 
            }else{
                temp1+='"",';
            }
            temp1+='"'+attendee.Item_Question__r.Question__r.Question_Text__c+'",';
            temp1+='"'+attendee.UAnswer_Text_Update__c+'",'; 
            temp1+='\n';     
       } 

        try {
            Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
            attachment.setFileName('ExportSurveybyAttendee.csv');
            attachment.setBody(Blob.valueOf(temp1));
            attachment.setContentType('text/csv');


            String emailMessage = 'Please find attached your exported data as an attachment';
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setFileAttachments(new Messaging.EmailFileAttachment[] {
                attachment
            });

            OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where DisplayName = 'supporteventdex'];

            if (owea.size() > 0) {
                mail.setOrgWideEmailAddressId(owea.get(0).Id); 
            }

            String[] toAddresses = new String[] {userinfo.getuserid()};//
            mail.setToAddresses(toAddresses);
            mail.setReplyTo('support@eventdex.com');
            mail.setSubject('SurveybyAttendee'); 
            mail.setHtmlBody(emailMessage);


            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {
                mail
            });
        } catch (Exception e) {}
    }


    global void finish(Database.BatchableContext batchableContext) {}

}