objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <label>Paid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BLN_TKT_profile__c</fullName>
        <label>BLN TKT profile</label>
        <referenceTo>Tkt_profile__c</referenceTo>
        <relationshipLabel>BLN Orders</relationshipLabel>
        <relationshipName>BLN_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <label>Currency Code</label>
        <referenceTo>Currency__c</referenceTo>
        <relationshipLabel>BLN Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Events__c</fullName>
        <label>Events</label>
        <referenceTo>BLN_Event__c</referenceTo>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fee_Amount__c</fullName>
        <label>Fee Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Discount__c</fullName>
        <label>Order Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Paid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Not Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Sub_Total__c</fullName>
        <label>Order Sub-Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Taxes__c</fullName>
        <label>Order Taxes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Total__c</fullName>
        <label>Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>order_type__c</fullName>
        <label>order type</label>
        <picklist>
            <picklistValues>
                <fullName>EVENT ATTENDEE</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EVENT PRODUCER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EVENT EXIBITOR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BLN Order</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tkt_profile__c.object
<CustomObject>
    <fields>
        <fullName>BLN_Company__c</fullName>
        <label>BLN Company</label>
        <referenceTo>Company__c</referenceTo>
        <relationshipLabel>BLN TKT profile</relationshipLabel>
        <relationshipName>BLN_TKT_profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BLN_GN_User__c</fullName>
        <label>BLN GN User</label>
        <referenceTo>GN_User__c</referenceTo>
        <relationshipLabel>BLN TKT profile</relationshipLabel>
        <relationshipName>BLN_TKT_profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BLN TKT profile</label>
    <nameField>
        <displayFormat>TP-{0000000}</displayFormat>
        <label>tkt profile</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN TKT profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_Order_BAL.cls
public with sharing class BLN_Order_BAL {
	
  public BLN_StatusMessage ProcessOrder(Id GNUser, Id eveid, Id CmpId, String PaymentType, String PayKey, String OrderTotal, String AfterDiscountPrice, String DiscountedPrice, String FeeAmount, String OrderTaxes, String AmountPayable, String OrderStatus, String CurrencyCode ){
		Order__c ord = new Order__c();
		//ord.order_type__c = PaymentType;
		//ord.Amount_Paid__c = ;
		ord.Currency_Code__c = CurrencyCode;
		//ord.Client_User__c = uid;
        ord.bln_tkt_profile__r.bln_gn_user__c= GNUser;
        ord.bln_tkt_profile__r.bln_company__c= CmpId;
		if(OrderTotal != null)
			ord.Order_Total__c = Decimal.valueOf(OrderTotal);
		if(AfterDiscountPrice != null)
			ord.Order_Sub_Total__c = Decimal.valueOf(AfterDiscountPrice);
		if(FeeAmount != null)
			ord.Fee_Amount__c = Decimal.valueOf(FeeAmount);
		if(DiscountedPrice != null)
			ord.Order_Discount__c = Decimal.valueOf(DiscountedPrice);
		if(AmountPayable != null)
			ord.Amount_Paid__c  = Decimal.valueOf(AmountPayable);
		if(OrderTaxes != null)	
			ord.Order_Taxes__c = Decimal.valueOf(OrderTaxes);
		ord.Order_Status__c = OrderStatus;
		ord.Events__c = eveid;
   // ord.Transaction_Status__c = TransactionStatus;
		
		BLN_Order_DAO insertOrder = new BLN_Order_DAO();
		BLN_StatusMessage OrderMsg = new BLN_StatusMessage();
		OrderMsg = insertOrder.insertOrder(ord);		
		
		return OrderMsg;
	
	}
 
}