objects/Pay_Gateway__c.object
<CustomObject>
    <fields>
        <fullName>PGateway_Type__c</fullName>
        <label>PGateway Type</label>
        <referenceTo>PGateway_Type__c</referenceTo>
        <relationshipName>Pay_Gateway</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN Pay Gateway</label>
    <nameField>
        <displayFormat>PG-{00000000}</displayFormat>
        <label>Pay Gateway Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BLN Pay Gateway</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PGateway_Type__c.object
<CustomObject>
    <fields>
        <fullName>Adaptive_Type__c</fullName>
        <label>Adaptive_Type</label>
        <picklist>
            <picklistValues>
                <fullName>Direct</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Display_Type__c</fullName>
        <label>Display Type</label>
        <picklist>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Online_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Online Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Onsite_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Onsite Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ScanAttendee_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ScanAttendee Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>BLN PGateway Type</label>
    <nameField>
        <label>PGateway_Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN PGateway Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BLN_PGateway_Type_DAO.cls
public with sharing class BLN_PGateway_Type_DAO{

/***********************************************************************************************
*   Controller Name         : BLN_PGateway_Type_DAO
*   Date                    : 16/06/2014 
*   Author                  : Mahesh Sakunala
*   Purpose                 : This class is for Retrieving Gateway Type.
*  Mallikarjuna Rao         :  Placed To Save Pay_Gateway__c object to an Event (19/06/2013)
**************************************************************************************************/

    public PGateway_Type__c getGatewayType(String GatewayType){
        PGateway_Type__c PGatewaytype = new PGateway_Type__c();
        return PGatewaytype = [SELECT Id,Name FROM PGateway_Type__c WHERE Name=: GatewayType];
    }
    
    
    //By Mallik
    //Return All PGateWays Records will return 
    //Used in Events page .......................
    public LIST<PGateway_Type__c> pGateWayTypes(){
        
        LIST<PGateway_Type__c> PGatewaytypes = new LIST<PGateway_Type__c>();
        return PGatewaytypes = [SELECT Id,Name,Display_Type__c, Help_Text__c, Image_URL__c,Online_Flag__c,Onsite_Flag__c,ScanAttendee_Flag__c,Adaptive_Type__c FROM PGateway_Type__c];
    }
    
    
    public LIST<dataBase.Upsertresult> pgateWaySaves(LIST<Pay_Gateway__c> payGateWays){
        
        LIST<DataBase.Upsertresult> gateWayRes = dataBase.upsert(payGateWays);
        
        return gateWayRes;
    }
    
    
}