objects/Profile_Settings__c.object
<CustomObject>
    <description>This is to save  settings of profile(show ,Hide)</description>
    <fields>
        <fullName>Additional_Company_Brouchers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Additional Company Brouchers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Additional_Company_videos__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Additional Company videos</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BBB_Number__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BBB Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Description__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Business Description</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Duns_Number__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Duns Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Established_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Established Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Revenue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Revenue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Tax_ID__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Tax ID</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cage_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cage Code</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Certificate_Processed_by_RPO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Certificate Processed by RPO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Certifications__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Certifications</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Commodities__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Commodities</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company_Logo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Company Logo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Company Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Country</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DBA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DBA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distributors_Country__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Distributors Country</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Id__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Id</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <label>First Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GSA_Schedule_Contract_Number__c</fullName>
        <defaultValue>false</defaultValue>
        <label>GSA Schedule Contract Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Geographical_Region__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Geographical Region</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Job Title</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KeyWords__c</fullName>
        <defaultValue>false</defaultValue>
        <label>KeyWords</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Last Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Additional_Company_Brouchers_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Additional Company Brouchers Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Address_1_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Address 1 Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Address_2_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Address 2 Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Business_Description_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Business Description Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_City_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE City Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Company_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Company Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Country_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Country Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_DBA_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE DBA Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Distributors_Country_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Distributors Country Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Email_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Email Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_First_Name_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE First Name Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Job_Title_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Job Title Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_LastName_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE LastName Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Manufatures_Country_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Manufatures Country Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Mobile_Phone_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Mobile Phone Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_NAICS_CODES_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE NAICS CODES Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Procurement_Needs_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Procurement Needs Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Products_Services_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Products / Services Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Salutation_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Salutation Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Small_Business_Image_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Small Business Image Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_State_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE State Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Title_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Title Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Website_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Website Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Work_Address_Visibility__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Work Address Visibility</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Work_Phone_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Work Phone Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBE_Zip_Code_Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <label>MBE Zip Code Visible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Manufatures_Country__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manufatures Country</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NAICS_Codes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NAICS Codes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Of_Employees__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Number Of Employees</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Business_Category__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Business Category</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Products_Services__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Products / Services</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>References__c</fullName>
        <defaultValue>false</defaultValue>
        <label>References</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revenue_Range__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Revenue Range</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Salutation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secondary_Business_Category__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Secondary Business Category</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Small_Business_IMAGE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Small Business IMAGE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <defaultValue>false</defaultValue>
        <label>State</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Title</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Uploaded_Company_Brochures__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Uploaded Company Brochures</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Uploaded_Video__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Uploaded Video</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Website</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_Address__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Work Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_phone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Work phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Zip Code</label>
        <type>Checkbox</type>
    </fields>
    <label>Profile Settings</label>
    <nameField>
        <label>Profile Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profile Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipName>State</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BLN State</label>
    <nameField>
        <label>State Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BLN States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/profileDao.cls
public class profileDao{

public LIST<Profile_Settings__c> getSettings(string eventSelected,string type){
 LIST<Profile_Settings__c> Psettings = new LIST<Profile_Settings__c>();
             Psettings = [SELECT id,Business_Description__c,Company_Name__c,Title__c,Mobile__c,Email_Id__c,
             First_Name__c,KeyWords__c,Last_Name__c,NAICS_Codes__c,MBE_Work_Address_Visibility__c,
             Work_Address__c,Work_phone__c,Additional_Company_Brouchers__c,Additional_Company_videos__c,BBB_Number__c,
             Business_Duns_Number__c,Business_Established_Date__c,Business_Revenue__c,Business_Tax_ID__c,Business_Type__c,Cage_Code__c,
             Certificate_Processed_by_RPO__c,Certifications__c,Commodities__c,Country__c,DBA__c,Distributors_Country__c,Geographical_Region__c,
             GSA_Schedule_Contract_Number__c,Job_Title__c,Manufatures_Country__c,Number_Of_Employees__c,Primary_Business_Category__c,Products_Services__c,
             References__c,Revenue_Range__c,Salutation__c,Secondary_Business_Category__c,Small_Business_IMAGE__c,State__c,Uploaded_Company_Brochures__c,Uploaded_Video__c,
             Website__c,Zip_Code__c,Company_Logo__c,MBE_Products_Services_Visible__c,MBE_LastName_Visible__c,MBE_Email_Visible__c,
             MBE_Job_Title_Visible__c,MBE_First_Name_Visible__c,MBE_Work_Phone_Visible__c,MBE_Procurement_Needs_Visible__c,MBE_Business_Description_Visible__c,
             MBE_NAICS_CODES_Visible__c,MBE_Small_Business_Image_Visible__c,MBE_Title_Visible__c,MBE_Mobile_Phone_Visible__c,
             MBE_Salutation_Visible__c,MBE_Company_Visible__c,MBE_DBA_Visible__c,MBE_Website_Visible__c,MBE_Address_1_Visible__c,MBE_Address_2_Visible__c,
             MBE_City_Visible__c,MBE_Country_Visible__c,MBE_Zip_Code_Visible__c,MBE_State_Visible__c,MBE_Additional_Company_Brouchers_Visible__c,
             MBE_Manufatures_Country_Visible__c,MBE_Distributors_Country_Visible__c,MBE_Uploaded_Company_Brochures_Visible__c,MBE_Company_Logo_Visible__c,
             MBE_Business_Duns_Number_Visible__c,MBE_Business_Established_Date_Visible__c,MBE_BBB_Number_Visible__c,MBE_Additional_Company_videos_Visible__c,
             MBE_Business_Revenue_Visible__c,MBE_Revenue_Range_Visible__c,MBE_Business_Tax_ID_Visible__c,MBE_Cage_Code_Visible__c,
             MBE_GSA_Schedule_Contract_Number_Visible__c,MBE_Number_Of_Employees_Visible__c,MBE_Primary_Business_Category_Visible__c,MBE_Certifications_Visible__c,
             MBE_Secondary_Business_Category_Visible__c,MBE_Certificate_Processed_by_RPO_Visible__c,MBE_Geographical_Region_Visible__c,MBE_References_Visible__c,
             MBE_Business_Type_Visible__c,MBE_Commodities_Visible__c,MBE_Uploaded_Video_Visible__c ,
             Year_in_Business__c,
             MBE_Year_in_Business_Visible__c,
             Business_Structure__c,
             Business_Structure_Visible__c,
             FaxNumber__c,
             FaxNumber_Visible__c,
             Ethnicity__c,
            MBE_Ethnicity_Visible__c,
            MBEAny_non_WBENC_awards_received_visible__c,
            MBECompanyhavefacility_partneroutsideUSA__c,
            Secondary_Email__c,
            MBE_Secondary_Email_Visible__c,
            Reference2__c,
            MBE_References2_Visible__c,
            Scope_of_Work__c,
            MBEScope_of_Work__c,
            MBEScope_of_Work2_Visible__c,
            Scope_of_Work2__c
             FROM Profile_Settings__c WHERE Event__r.id =: eventSelected AND Name=:type ];
        
     return Psettings;
}



}